### ISSUE TITLE
Debug stop working with modules on version 2018.10.x

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1008]
_From @sharkguto on November 12, 2018 12:9_

Copied from original issue: Microsoft/vscode-python#3309

## Environment data

- VS Code version: 
```
code --version
1.28.2
7f3ce96ff4729c91352ae6def877e59c561f4850
x64
``` 
or 
```
code-insiders --version
1.29.0-insider
5f24c93878bd4bc645a4a17c620e2487b11005f9
x64
```

- Extension version (available under the Extensions sidebar): - OS and version: ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A 
- Relevant/affected Python packages and their versions: 

## Actual behavior

debugger not working with modules

![image](https://user-images.githubusercontent.com/3118165/48346056-04b53200-e661-11e8-858d-36692a326e90.png)

## Expected  behavior

debugger should work with modules back again.... like in version 2018.09. ~~ I am not able to rollback python ext, in current vscode stable and insiders version.~~

## Steps to reproduce:
1. ```{
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "qconsumer",
            "console": "integratedTerminal"
        },```
or 
```
{
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/qconsumer/__main__.py",
            "console": "integratedTerminal",
        },```

2. press f5

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

output

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.60.0
Initializing for /usr/bin/python3
##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

terminal

```
cd /home/gustavo/github/consumerq-svc ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /usr/bin/python3 /home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py --client --host localhost --port 41131 /home/gustavo/github/consumerq-svc/qconsumer/__main__.py
Traceback (most recent call last):
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py", line 38, in <module>
    main(sys.argv)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 140, in _run
    _pydevd.main()
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1925, in main
    debugger.connect(host, port)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1290, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/gustavo/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gustavo/github/consumerq-svc/qconsumer/__main__.py", line 13, in <module>
    from qconsumer.runnables import runnable
ModuleNotFoundError: No module named 'qconsumer'
```

insiders

```
Traceback (most recent call last):
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py", line 38, in <module>
    main(sys.argv)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 140, in _run
    _pydevd.main()
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1925, in main
    debugger.connect(host, port)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1290, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/gustavo/.vscode-insiders/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gustavo/github/consumerq-svc/qconsumer/__main__.py", line 13, in <module>
    from qconsumer.runnables import runnable
ModuleNotFoundError: No module named 'qconsumer'
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
workbench.main.js:sourcemap:225 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```


Copied from original issue: Microsoft/vscode-python#3309

**Comment by DonJayamanne** [comment]
_From @sharkguto on November 12, 2018 12:23_

![image](https://user-images.githubusercontent.com/3118165/48347229-cd488480-e664-11e8-9dbe-dc6d3cf79081.png)

i installed manually the version 2018.9.1 and it working again \o/
https://github.com/Microsoft/vscode-python/releases/download/2018.9.1/ms-python-release-2018.9.vsix

**Comment by int19h** [comment]
Is this related to #991, perhaps?

**Comment by DonJayamanne** [comment]
Yes, in deed. Closing as a dup.

**Comment by karthiknadig** [comment]
It seems to work if i have PYTHONPATH set:
```
        {
            "name": "Module: foo",
            "type": "python",
            "request": "launch",
            "console": "integratedTerminal",
            "module": "foo",
            "cwd": "${workspaceFolder}",
            "env": {"PYTHONPATH": "${workspaceFolder}"}
        },
```

**Comment by karthiknadig** [comment]
Dupe #991
