### ISSUE TITLE
Debugger Failed to Connect - Connection Refused 

### ISSUE THREAD

**Issue by iamchairs** [Microsoft/ptvsd#1015]
**Edit**

Problem was resolved by reverting from version 4.2.0 to 4.1.4
Go to [releases](https://github.com/Microsoft/ptvsd/releases), download v 4.1.4, replace `ptvsd` in `ms-python.python-***/pythonFiles/experimental/`

## Environment data

- PTVSD version: 4.2.0
- OS and version: OSX 10.14
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When starting the debugger, I see the command it's trying to make, but nothing happens. The debugger doesn't exit, or continue.

Running the same command in terminal gives `Connection Refused`. Not sure if this is related.

```
cd /Users/micah/.../do_stuff ; "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 /Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py --client --host localhost --port 59013 /Library/Frameworks/Python.framework/Versions/3.6/bin/python-lambda-local -t 100000 -f lambda_handler /Users/micah/.../event.json
Could not connect to localhost: 59013
Traceback (most recent call last):
  File "/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1925, in main
    debugger.connect(host, port)
  File "/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 484, in connect
    s = start_client(host, port)
  File "/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/pydevd_hooks.py", line 125, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/pydevd_hooks.py", line 71, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/daemon.py", line 211, in start_client
    connect(client, addr)
  File "/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd/ptvsd/socket.py", line 197, in connect
    sock.connect(addr)
ConnectionRefusedError: [Errno 61] Connection refused
```

Debug logs-

```
9:38:11 AM, 11/14/2018
Started @ Wed Nov 14 2018 09:38:11 GMT-0600 (CST)
From Client:
Content-Length: 313

{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"python","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
To Client:
Content-Length: 687

{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsExceptionInfoRequest":true,"supportsConfigurationDoneRequest":true,"supportsConditionalBreakpoints":true,"supportsSetVariable":true,"supportsExceptionOptions":true,"supportsEvaluateForHovers":true,"supportsModulesRequest":true,"supportsValueFormattingOptions":true,"supportsHitConditionalBreakpoints":true,"supportsSetExpression":true,"supportsLogPoints":true,"supportTerminateDebuggee":true,"supportsCompletionsRequest":true,"exceptionBreakpointFilters":[{"filter":"raised","label":"Raised Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":true}]}}
From Client:
Content-Length: 992

{"command":"launch","arguments":{"name":"lambda_handler","type":"python","request":"launch","program":"/Library/Frameworks/Python.framework/Versions/3.6/bin/python-lambda-local","logToFile":true,"args":["-t","100000","-f","lambda_handler","/Users/micah/dev/.../lambda_function.py","/Users/micah/dev/.../test/fixtures/event.json"],"env":{},"pythonPath":"/Library/Frameworks/Python.framework/Versions/3.6/bin/python3","cwd":"/Users/micah/dev/.../do_stuff","envFile":"/Users/micah/dev/.../.env","stopOnEntry":false,"showReturnValue":false,"console":"integratedTerminal","internalConsoleOptions":"neverOpen","debugOptions":["RedirectOutput"],"workspaceFolder":"/Users/micah/dev/.../do_stuff","__sessionId":"0fc90b12-e51d-4d56-8ff0-f591225f0533"},"type":"request","seq":2}
To Client:
Content-Length: 810

{"command":"runInTerminal","arguments":{"kind":"integrated","title":"Python Debug Console","cwd":"/Users/micah/dev/.../do_stuff","args":["/Library/Frameworks/Python.framework/Versions/3.6/bin/python3","/Users/micah/.vscode/extensions/ms-python.python-2018.10.1/pythonFiles/experimental/ptvsd_launcher.py","--client","--host","localhost","--port","59512","/Library/Frameworks/Python.framework/Versions/3.6/bin/python-lambda-local","-t","100000","-f","lambda_handler","/Users/micah/dev/.../lambda_function.py","/Users/micah/dev/.../test/fixtures/event.json"],"env":{"PYTHONIOENCODING":"UTF-8","PYTHONUNBUFFERED":"1"}},"type":"request","seq":2}
From Client:
Content-Length: 94

{"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{}}
To Client:
Content-Length: 992


To Client:
{"command":"launch","arguments":{"name":"lambda_handler","type":"python","request":"launch","program":"/Library/Frameworks/Python.framework/Versions/3.6/bin/python-lambda-local","logToFile":true,"args":["-t","100000","-f","lambda_handler","/Users/micah/dev/.../lambda_function.py","/Users/micah/dev/.../test/fixtures/event.json"],"env":{},"pythonPath":"/Library/Frameworks/Python.framework/Versions/3.6/bin/python3","cwd":"/Users/micah/dev/.../do_stuff","envFile":"/Users/micah/dev/.../.env","stopOnEntry":false,"showReturnValue":false,"console":"integratedTerminal","internalConsoleOptions":"neverOpen","debugOptions":["RedirectOutput"],"workspaceFolder":"/Users/micah/dev/.../do_stuff","__sessionId":"0fc90b12-e51d-4d56-8ff0-f591225f0533"},"type":"request","seq":2}
To Client:
Content-Length: 313


To Client:
{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"python","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
To Client:
Content-Length: 130

{"type": "event", "seq": 0, "event": "output", "body": {"category": "telemetry", "output": "ptvsd", "data": {"version": "4.2.0"}}}
To Client:
Content-Length: 113

{"type": "response", "seq": 1, "request_seq": 2, "success": true, "command": "launch", "message": "", "body": {}}
To Client:
Content-Length: 787

{"type": "response", "seq": 2, "request_seq": 1, "success": true, "command": "initialize", "message": "", "body": {"supportsCompletionsRequest": true, "supportsConditionalBreakpoints": true, "supportsConfigurationDoneRequest": true, "supportsDebuggerProperties": true, "supportsEvaluateForHovers": true, "supportsExceptionInfoRequest": true, "supportsExceptionOptions": true, "supportsHitConditionalBreakpoints": true, "supportsLogPoints": true, "supportsModulesRequest": true, "supportsSetExpression": true, "supportsSetVariable": true, "supportsValueFormattingOptions": true, "supportTerminateDebuggee": true, "exceptionBreakpointFilters": [{"filter": "raised", "label": "Raised Exceptions", "default": false}, {"filter": "uncaught", "label": "Uncaught Exceptions", "default": true}]}}Content-Length: 63

{"type": "event", "seq": 3, "event": "initialized", "body": {}}
From Client:
Content-Length: 99

{"command":"setExceptionBreakpoints","arguments":{"filters":["uncaught"]},"type":"request","seq":4}
To Client:
Content-Length: 130


To Client:
{"type": "response", "seq": 4, "request_seq": 4, "success": true, "command": "setExceptionBreakpoints", "message": "", "body": {}}
From Client:
Content-Length: 56

{"command":"configurationDone","type":"request","seq":5}
To Client:
Content-Length: 124

{"type": "response", "seq": 5, "request_seq": 5, "success": true, "command": "configurationDone", "message": "", "body": {}}
From Client:
Content-Length: 46

{"command":"threads","type":"request","seq":6}
To Client:
Content-Length: 92

{"type": "event", "seq": 6, "event": "thread", "body": {"reason": "started", "threadId": 1}}Content-Length: 158

{"type": "response", "seq": 7, "request_seq": 6, "success": true, "command": "threads", "message": "", "body": {"threads": [{"id": 1, "name": "MainThread"}]}}
To Client:
Content-Length: 217

{"type": "event", "seq": 8, "event": "process", "body": {"name": "/Library/Frameworks/Python.framework/Versions/3.6/bin/python-lambda-local", "systemProcessId": 11373, "isLocalProcess": true, "startMethod": "launch"}}
From Client:
Content-Length: 46

{"command":"threads","type":"request","seq":7}
To Client:
Content-Length: 158

{"type": "response", "seq": 9, "request_seq": 7, "success": true, "command": "threads", "message": "", "body": {"threads": [{"id": 1, "name": "MainThread"}]}}
```

I've tried uninstalling and reinstalling the extension multiple times. Closing and opening vs code. And even rebooting. I've been using this debugger for months. This is a new issues as of yesterday.

## Expected  behavior

The debugger runs

## Steps to reproduce:

Run the debugger

**Comment by felipeferri** [comment]
I'm having the same issue. Unfortunately reverting ptvsd to 4.1.4 didn't help.

**Comment by iamchairs** [comment]
@felipeferri Doesn't work for me now either. Did you find any solution to this? I'm getting it again.

**Comment by karthiknadig** [comment]
@iamchairs Can you share the logs again? the one in the bug is incomplete. Based on the log in the bug, the debugger is operating.
If you run the debugger directly in the terminal using the same command line as the one used by VSCode then you will get Connection refused error. The debugger expects to connect to a server, and since it is not available it fails.

If possible please share minimal code that is failing.

### To run the debugger in terminal:
you could run your code like this under the debugger and connect to it from VSCode:
`python -m ptvsd --host localhost  --port 5678 --wait your_code.py`
Then in VSC launch.json:
```json
        {
            "name": "Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "${workspaceFolder}"
                }
            ],
        },
```
This should allow you to attach to the debugger running your code.

**Comment by karthiknadig** [comment]
Please reopen when more information is available.

**Comment by ivankorn** [comment]
@karthiknadig, the issue seem to be reproducible with the latest ms-python extension.

`  File "~/.vscode-oss/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/socket.py", line 197, in connect
    sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused`
