### ISSUE TITLE
ptvsd and Celery worker raises RuntimeError: already started

### ISSUE THREAD

**Issue by gegenschall** [Microsoft/ptvsd#1046]
## Environment data

- PTVSD version: 4.2.0
- OS and version: Arch Linux
- Python version: 3.7 (Docker python:3.7)
- Using VS Code or Visual Studio: VS Code

## Actual behavior
`ptvsd.enable_attach` raises `RuntimeError: already started` when used within a Django+Celery app. Code used to start ptvsd:

```
from django.conf import settings
if settings.DEBUG:
    import ptvsd
    ptvsd.enable_attach(address=('0.0.0.0', 5678), redirect_output=True)
```

Command-line used to start celery worker: 
```
watchmedo auto-restart --signal SIGTERM -R -d /app -p '*.py' -i '*.pyc' -- celery -A app_name worker -l info --concurrency=4
```

Actual exception raised (4 times):
```
celery_1_d89f110b2f29 | [2018-11-20 13:32:28,143: CRITICAL/MainProcess] Unrecoverable error: RuntimeError('already started')
celery_1_d89f110b2f29 | Traceback (most recent call last):
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
celery_1_d89f110b2f29 |     self.blueprint.start(self)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
celery_1_d89f110b2f29 |     step.start(parent)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
celery_1_d89f110b2f29 |     return self.obj.start()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/base.py", line 131, in start
celery_1_d89f110b2f29 |     self.on_start()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 112, in on_start
celery_1_d89f110b2f29 |     **self.options)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 432, in __init__
celery_1_d89f110b2f29 |     super(AsynPool, self).__init__(processes, *args, **kwargs)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1007, in __init__
celery_1_d89f110b2f29 |     self._create_worker_process(i)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 449, in _create_worker_process
celery_1_d89f110b2f29 |     return super(AsynPool, self)._create_worker_process(i)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1116, in _create_worker_process
celery_1_d89f110b2f29 |     w.start()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
celery_1_d89f110b2f29 |     self._popen = self._Popen(self)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
celery_1_d89f110b2f29 |     return Popen(process_obj)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
celery_1_d89f110b2f29 |     self._launch(process_obj)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/billiard/popen_fork.py", line 72, in _launch
celery_1_d89f110b2f29 |     self.pid = os.fork()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 488, in new_fork
celery_1_d89f110b2f29 |     _on_forked_process()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 56, in _on_forked_process
celery_1_d89f110b2f29 |     pydevd.settrace_forked()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1723, in settrace_forked
celery_1_d89f110b2f29 |     patch_multiprocessing=True,
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1488, in settrace
celery_1_d89f110b2f29 |     stop_at_frame,
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1536, in _locked_settrace
celery_1_d89f110b2f29 |     debugger.connect(host, port)  # Note: connect can raise error.
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 484, in connect
celery_1_d89f110b2f29 |     s = start_client(host, port)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/pydevd_hooks.py", line 125, in <lambda>
celery_1_d89f110b2f29 |     _start_client = (lambda h, p: start_client(daemon, h, p))
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_remote.py", line 72, in <lambda>
celery_1_d89f110b2f29 |     start_client=(lambda daemon, h, port: start_daemon()),
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/_remote.py", line 64, in start_daemon
celery_1_d89f110b2f29 |     _, next_session = daemon.start_server(addr=(host, port))
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/daemon.py", line 154, in start_server
celery_1_d89f110b2f29 |     with self.started():
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
celery_1_d89f110b2f29 |     return next(self.gen)
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/daemon.py", line 109, in started
celery_1_d89f110b2f29 |     self.start()
celery_1_d89f110b2f29 |   File "/usr/local/lib/python3.7/site-packages/ptvsd/daemon.py", line 144, in start
celery_1_d89f110b2f29 |     raise RuntimeError('already started')
celery_1_d89f110b2f29 | RuntimeError: already started
```

**Comment by pbechliv** [comment]
I have the exact same issue

**Comment by catexis** [comment]
I have the exact same issue

PTVSD version: 4.2.0  
OS and version: Ubuntu 18.04  
Python version: 2.7.15  
Using VS Code 1.29.1  
Python extension: 2018.11.0
<details><summary>launch.json</summary>

```JSON
{
    "name": "Beat",
    "type": "python",
    "request": "launch",
    "pythonPath": "/home/MyName/job/MyProject/venv/bin/python",
    "program": "/home/MyName/job/MyProject/venv/bin/celery",
    "console": "integratedTerminal",
    "args": [
        "-A",
        "bgp",
        "beat",
        "-l",
        "info"
    ]
},
{
    "name": "Celery",
    "type": "python",
    "request": "launch",
    "pythonPath": "/home/MyName/job/MyProject/venv/bin/python",
    "program": "/home/MyName/job/MyProject/venv/bin/celery",
    "console": "integratedTerminal",
    "args": [
        "-A",
        "bgp",
        "worker",
        "-l",
        "info",
        "-Q",
        "ssh",
        "--concurrency=1",
    ]
},
```  

</details>
<details><summary>traceback</summary>

```python
[2018-11-30 15:49:04,979: INFO/MainProcess] Connected to amqp://project:**@127.0.0.1:5672/project
[2018-11-30 15:49:05,031: INFO/MainProcess] mingle: searching for neighbors
[2018-11-30 15:49:04,909: CRITICAL/MainProcess] Unrecoverable error: RuntimeError('already started',)
Traceback (most recent call last):
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 112, in on_start
    **self.options)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 432, in __init__
    super(AsynPool, self).__init__(processes, *args, **kwargs)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/billiard/pool.py", line 1007, in __init__
    self._create_worker_process(i)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 449, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/billiard/pool.py", line 1116, in _create_worker_process
    w.start()
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
  File "/home/MyName/job/MyProject/venv/lib/python2.7/site-packages/billiard/popen_fork.py", line 72, in _launch
    self.pid = os.fork()
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 488, in new_fork
    _on_forked_process()
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 56, in _on_forked_process
    pydevd.settrace_forked()
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1723, in settrace_forked
    patch_multiprocessing=True,
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1488, in settrace
    stop_at_frame,
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1536, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 484, in connect
    s = start_client(host, port)
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/pydevd_hooks.py", line 125, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/pydevd_hooks.py", line 71, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/daemon.py", line 208, in start_client
    with self.started():
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/daemon.py", line 109, in started
    self.start()
  File "/home/MyName/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/daemon.py", line 144, in start
    raise RuntimeError('already started')
RuntimeError: already started
[2018-11-30 15:49:06,178: INFO/MainProcess] mingle: all alone
[2018-11-30 15:49:06,315: WARNING/MainProcess] /home/MyName/job/MyProject/venv/lib/python2.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2018-11-30 15:49:06,316: INFO/MainProcess] celery@MyName-vm ready.
```

</details>

**Comment by karthiknadig** [comment]
This should be addressed by #943. The debugger currently does not support `os.fork`, it can handle `os.spawn*()`.

**Comment by catexis** [comment]
@gegenschall , @pbechliv as a solution - you cat try attach vscode to debug celery process ([attach to local script](https://code.visualstudio.com/docs/python/debugging#_attach-to-a-local-script)). It will be like [celery's rdb](http://docs.celeryproject.org/en/latest/userguide/debugging.html).  
Just put this code into your celery's task:  
```python
import ptvsd
print("Waiting for debugger attach")
ptvsd.enable_attach(address=('localhost', 5678), redirect_output=True)
ptvsd.wait_for_attach()
```  

Breakpoints will be work!

**Comment by kirtangajjar** [comment]
@karthikananth Any updates on this?

**Comment by karthiknadig** [comment]
@kirtangajjar we are working on refactoring the debugger, which is part of getting it fork safe. This issue is not fixed yet.

**Comment by gegenschall** [comment]
In the meantime you can use Celery with another pool implementation:

`celery worker --app=<appname> --pool=solo` should do the job for local development/debugging just fine.

**Comment by fabioz** [comment]
This issue (supporting fork in the debugger) is being tracked in https://github.com/Microsoft/ptvsd/issues/943, so, closing this one as a duplicate.
