### ISSUE TITLE
AttributeError: module 'builtins' has no attribute 'interpreter' when you do anything in the debug console

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#1072]
@lovettchris commented on [Thu Dec 13 2018](https://github.com/Microsoft/vscode-python/issues/3698)

**Repro**
1) Create test.py containing:
```python
print("Hello World")
```
2) then run "code hello.py" from a console that is configured with an Anaconda version of Python 3.6.
3) put a breakpoint on that line and press F5
4) click "Debug Console" and type in "import os"

**Actual**
```
Traceback (most recent call last):
  File "c:\Users\clovett\.vscode\extensions\ms-python.python-2018.12.0\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevconsole.py", line 449, in get_interpreter
    interpreterInterface = getattr(__builtin__, 'interpreter')
AttributeError: module 'builtins' has no attribute 'interpreter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\Users\clovett\.vscode\extensions\ms-python.python-2018.12.0\pythonFiles\lib\python\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 1381, in do_it
    msg = _pydev_completer.generate_completions_as_xml(frame, self.act_tok)
  File "c:\Users\clovett\.vscode\extensions\ms-python.python-2018.12.0\pythonFiles\lib\python\ptvsd\_vendored\pydevd\_pydev_bundle\_pydev_completer.py", line 167, in generate_completions_as_xml
    completions = pydevconsole.get_completions(act_tok, act_tok, updated_globals, frame.f_locals)
  File "c:\Users\clovett\.vscod...
```

**Comment by fabioz** [comment]
@lovettchris can you post the full stack trace? It's strange because in the code that `AttributeError: module 'builtins' has no attribute 'interpreter'` is protected (https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/pydevconsole.py#L449), so, trying to make sense of it (maybe the full stack trace can help).

Also, do you know which version of IPython are you using? -- sometimes the console breaks because of changes/issues in IPython.

**Comment by awav** [comment]
@fabioz, Here is a full stack trace:

```
Traceback (most recent call last):
  File "/Users/artemav/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevconsole.py", line 449, in get_interpreter
    interpreterInterface = getattr(__builtin__, 'interpreter')
AttributeError: module 'builtins' has no attribute 'interpreter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/artemav/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1381, in do_it
    msg = _pydev_completer.generate_completions_as_xml(frame, self.act_tok)
  File "/Users/artemav/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydev_bundle/_pydev_completer.py", line 167, in generate_completions_as_xml
    completions = pydevconsole.get_completions(act_tok, act_tok, updated_globals, frame.f_locals)
  File "/Users/artemav/.vscode/extens...
```

```
$ ipython --version
6.2.1
```
