### ISSUE TITLE
gevent 'BlockingSwitchOutError' exception after updating

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#1073]
@mkimberling commented on [Fri Dec 14 2018](https://github.com/Microsoft/PTVS/issues/4922)

After updating VisualStudio to 15.9.4 yesterday, I'm experiencing an unhandled exception from `gevent` when I perform operations in my application:
```
 Traceback (most recent call last):
   File "c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 649, in trace_dispatch
     self.do_wait_suspend(thread, frame, event, arg)
   File "c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
     self._args[0].do_wait_suspend(*args, **kwargs)
   File "c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 821, in do_wait_suspend
     time.sleep(0.01)
   File "Q:\t8\tools\lang\python2.7\lib\site-packages\gevent\hub.py", line 159, in sleep
     hub.wait(t)
   File "src\gevent\_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   File "src\gevent\_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
   File "src\gevent\_waiter.py", line 151, in gevent.__waiter.Waiter.get
   File "src\gevent\_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   File "src\gevent\_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   File "src\gevent\_greenlet_primitives.py", line 62, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
   File "src\gevent\_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
   File "src\gevent\_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
 BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

Updating gevent & greenlet to the latest version doesn't address the issue.

---

@mkimberling commented on [Fri Dec 14 2018](https://github.com/Microsoft/PTVS/issues/4922#issuecomment-447425983)

I do not get this when the "Use legacy debugger" checkbox in Options:Python:Debugging is checked.

---

@huguesv commented on [Fri Dec 14 2018](https://github.com/Microsoft/PTVS/issues/4922#issuecomment-447426267)

Can you try updating to the latest ptvsd? There's been updates to it since it was bundled with 15.9.

You can do that by "pip install ptvsd" in your python environment. VS knows to use the one in the environment if found.

---

@mkimberling commented on [Fri Dec 14 2018](https://github.com/Microsoft/PTVS/issues/4922#issuecomment-447427036)

I tried that out just now and still get the same error after disabling the legacy debugger.  I installed the latest debugger with pip, restarted visual studio, disabled the legacy debugger, started up my python app, and reproduced the unhandled exception

---

@huguesv commented on [Fri Dec 14 2018](https://github.com/Microsoft/PTVS/issues/4922#issuecomment-447427533)

Thanks! I'll move this to ptvsd issue tracker.

**Comment by karthiknadig** [comment]
@mkimberling Can you try this after setting environment variable `GEVENT_SUPPORT = 'True'`?
If you continue to experience this, can you share minimal code that repros this issue?

**Comment by karthiknadig** [comment]
Please reopen when more information is available. Not enough detail to repro.

**Comment by johaven** [comment]
Same problem for me using gevent.

**Code**
```python
import os
os.environ["GEVENT_SUPPORT"] = "True"
import atexit

from apscheduler.schedulers.gevent import BlockingScheduler

from webapp import app
from webapp.mod_users.jobs import update_users_quota


def add_jobs():
    scheduler.add_job(update_users_quota, 'cron', minute=0)

def show_jobs():
    for job in scheduler.get_jobs():
        app.logger.info(str(job))

def terminate():
    print('TERMINATEEEEEEEE')
    scheduler.shutdown()

if __name__ == '__main__':
    scheduler = BlockingScheduler(daemon=True)
    add_jobs()
    show_jobs()
    atexit.register(terminate)
    try:
        scheduler.start()
    except KeyboardInterrupt:
        pass
```
**Logs**
```
^CSIGINT/SIGQUIT received...killing workers...
Brutally killing worker 1 (pid: 4630)...
TERMINATEEEEEEEE
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Web/venv/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 191, in shutdown
Sun Apr 26 16:18:20 2020 - stopping gevent signals watchers for worker 1 (pid: 4630)...
gateway "uWSGI http 1" has been buried (pid: 4632)
Sun Apr 26 16:18:20 2020 - stopping gevent sockets watchers for worker 1 (pid: 4630)...
    executor.shutdown(wait)
  File "/Web/venv/lib/python3.7/site-packages/apscheduler/executors/pool.py", line 26, in shutdown
    self._pool.shutdown(wait)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 216, in shutdown
Sun Apr 26 16:18:20 2020 - main gevent watchers stopped for worker 1 (pid: 4630)...
goodbye to the gevent Hub on worker 1 (pid: 4630)
    t.join()
  File "/Web/venv/lib/python3.7/site-packages/gevent/threading.py", line 189, in join
    self._greenlet.join(timeout=timeout)
  File "src/gevent/greenlet.py", line 711, in gevent._greenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 737, in gevent._greenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 726, in gevent._greenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 726, in gevent._greenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
mule 1 (pid: 4631) annihilated
```

**Comment by johaven** [comment]
Resolved with:

```python
gevent.signal(signal.SIGTERM, terminate)
gevent.signal(signal.SIGINT, terminate)
```
