### ISSUE TITLE
IOError triggered in ptvsd

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#1094]
@peer2peer commented on [Wed Jan 09 2019](https://github.com/Microsoft/vscode-python/issues/3956)
```
Traceback (most recent call last):
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\__main__.py", line 265, in main
    wait=args.wait)
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\__main__.py", line 256, in handle_args
    run_main(addr, name, kind, *extra, **kwargs)
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_local.py", line 52, in run_main
    runner(addr, name, kind == 'module', *extra, **kwargs)
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\runner.py", line 32, in run
    set_trace=False)
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 1290, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "c:\Users\MyName\Desktop\eth.py", line 139, in <module>
    print t
  File "c:\Users\MyName\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_io.py", line 30, in write
    r.write(s)
IOError: [Errno 0] Error
```

**Comment by fabioz** [comment]
@peer2peer can you give more details on how did you get this error to happen? 

Which code did you use?

What's the Python version you're using? (please add up to the minor version i.e.: 2.7.12)

**Comment by karthiknadig** [comment]
Please reopen when you have more details.
