### ISSUE TITLE
妈呀，怎么会有那么多Bug？Oops, so much bug on this project.

### ISSUE THREAD

**Issue by YLinXin** [Microsoft/ptvsd#1106]
## Environment data

- PTVSD version: 4.2.0
- OS and version: Linux 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.15+ (default, Oct  2 2018, 22:12:08) 
[GCC 8.2.0] on linux2

- Using VS Code or Visual Studio: VS Code 

## Actual behavior

same as the #987 

## Expected  behavior

everything is all right.

## Steps to reproduce:
1. change to 4.2.0+64.g274cf88
2. 
```
sudo python -m ptvsd --host localhost --port 7777 --pid `pgrep -f "/usr/bin/python ./manage.py"`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/__main__.py", line 269, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/__main__.py", line 254, in handle_args
    attach_main(addr, name, *extra, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_attach.py", line 42, in attach_main
    run_python_code(pid, code, connect_debugger_tracing=True)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 400, in run_python_code_linux
    assert '\'' not in python_code, 'Having a single quote messes with our command.'
AssertionError: Having a single quote messes with our command.

```

comment the line and run command below
```

sudo python -m ptvsd --host localhost --port 7777 --pid `pgrep -f "/usr/bin/python ./manage.py"`
Attaching with arch: i386:x86-64
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/__main__.py", line 269, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/__main__.py", line 254, in handle_args
    attach_main(addr, name, *extra, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_attach.py", line 42, in attach_main
    run_python_code(pid, code, connect_debugger_tracing=True)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 419, in run_python_code_linux
    raise RuntimeError('Could not find dll file to inject: %s' % target_dll)
RuntimeError: Could not find dll file to inject: /usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so

```

add code to views.py
```
import ptvsd
ptvsd.enable_attach(address=('0.0.0.0', 7777), redirect_output=True)

ptvsd.wait_for_attach()

```

```
sudo python ./manage.py runserver --settings=web_admin.settings "0.0.0.0:8005"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py", line 686, in process_net_command
    py_db.on_breakpoints_changed(remove=True)
TypeError: on_breakpoints_changed() got an unexpected keyword argument 'remove'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py", line 686, in process_net_command
    py_db.on_breakpoints_changed(remove=True)
TypeError: on_breakpoints_changed() got an unexpected keyword argument 'remove'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py", line 686, in process_net_command
    py_db.on_breakpoints_changed(remove=True)
TypeError: on_breakpoints_changed() got an unexpected keyword argument 'remove'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py", line 686, in process_net_command
    py_db.on_breakpoints_changed(remove=True)
TypeError: on_breakpoints_changed() got an unexpected keyword argument 'remove'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py", line 686, in process_net_command
    py_db.on_breakpoints_changed(remove=True)
TypeError: on_breakpoints_changed() got an unexpected keyword argument 'remove'

```

**Comment by karthiknadig** [comment]
Try running django with, `--noreload` and `--nothreading`.
`sudo python -m ptvsd --host 0.0.0.0 --port 7777 ./manage.py runserver --noreload --nothreading --settings=web_admin.settings "0.0.0.0:8005"`

When using `--wait` debugger will wait for you to attach before running your code.

Also `pathMapping` should not have `program`. use this:
```js
"configurations": [
        {
            "name": "Attach (Remote Debug) Django",
            "type": "python",
            "request": "attach",
            "port": 7777,
            "host": remoteIP, 
            "django": true,
            "pathMappings": [
                {
                    "localRoot": "${workspaceRoot}",   // Local root  (where source and debugger running)
                    "remoteRoot": nfsSharedDirectory,  // Remote root (where remote code is running)
                }
            ]
        }
    ]
```

**Comment by karthiknadig** [comment]
Closing this for now, please reopen if needed.
