### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by missingdaysqxy** [Microsoft/ptvsd#1113]
I want to know if there are any methods to set a unlimited connection for a long time debugging? Because of my unfamiliarity to the project, I need to check the variables one by one, and this will take a lot of time.

Terminal Report as follows:
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 6.4.0
Exception in thread ptvsd.Server:
Traceback (most recent call last):
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 315, in process_one_message
    msg = self.__message.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/wrapper.py", line 921, in process_messages
    raise exc
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/wrapper.py", line 906, in process_messages
    self.process_messages()
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 305, in process_messages
    self.process_one_message()
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 318, in process_one_message
    self._wait_for_message()
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 172, in _wait_for_message
    line = self._buffered_read_line_as_ascii()
  File "/home/liuqixuan_i/anaconda3/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 131, in _buffered_read_line_as_ascii
    temp = self.__socket.recv(1024)
TimeoutError: [Errno 110] Connection timed out
```

**Comment by fabioz** [comment]
Just wanted to note that on plain `pydevd` there are some socket configurations which help to keep the connection alive:

See: https://github.com/fabioz/PyDev.Debugger/blob/master/_pydevd_bundle/pydevd_comm.py#L418

Maybe that could be used for the `ptvsd` connection too...

**Comment by karthiknadig** [comment]
We should set `SO_KEEPALIVE` on the socket ptvsd uses.

**Comment by int19h** [comment]
So SO_KEEPALIVE is something different. If it is not set, then there's no intrinsic timeout for a TCP socket (firewalls etc can still close it, but we don't control that). In that mode, if the other end is forcibly disconnected, we will only detect said disconnect after we try to send some packet to it. 
 
If the flag is set, then it does periodic pings, but those pings are specifically for the purpose of determining whether the other side is down without sending some meaningful packet. In other words, setting SO_KEEPALIVE enables TCP timeouts. And then those other settings, like TCP_KEEPCNT, define various parameters, like how often it should ping.

And we set all that stuff already (see socket.py).
 
But anyway, it means that with those settings, TimeoutError indicates that the other side of the connection actually timed out. To be specific, our current settings mean that keepalive pings are sent every 3 seconds on an otherwise idle connection, and it takes 5 failed pings before the connection is considered abandoned. So, 15 seconds of not responding... I'm pretty sure that indicates a network problem somewhere else, like maybe the firewall is killing those silently after a while.

**Comment by int19h** [comment]
Closing this for now, since we don't have enough info to investigate further - please reopen if this proves to be not a network issue after all.

**Comment by harshitazilen** [comment]
Hi, I am facing the same issue. I am debugging in local machine only yet it says "time out". Can you guide me how to resolve it ?
