### ISSUE TITLE
Got "Address already in use" exception even with different port. 

### ISSUE THREAD

**Issue by Anakin-Hao** [Microsoft/ptvsd#1131]
## Environment data

- PTVSD version: 4.2.2
- OS and version: Docker Python3.7 
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VS Code (not used yet)

## Actual behavior
My code is this
```
from flask import Flask
import ptvsd
import os

ptvsd_port = os.environ.get('ptvsd_port', 11911)
print(ptvsd_port)
app = Flask(__name__)


@app.route('/')
@app.route('/healthcheck')
def hello_world():
    return 'Flask Dockerized'
    

if __name__ == '__main__':
    # Allow other computers to attach to ptvsd at this IP address and port.
    ptvsd.enable_attach(address=('127.0.0.1', ptvsd_port), redirect_output=True)
    app.run(debug=True, host='0.0.0.0', port=8080)
```
Starting the code throws this error:
```
11911
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
11911
Traceback (most recent call last):
  File "./app.py", line 18, in <module>
    ptvsd.enable_attach(address=('127.0.0.1', ptvsd_port), redirect_output=True)
  File "/usr/local/lib/python3.7/site-packages/ptvsd/attach_server.py", line 74, in enable_attach
    redirect_output=redirect_output,
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_remote.py", line 92, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1658, in settrace
    stop_at_frame,
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1708, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 687, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/site-packages/ptvsd/pydevd_hooks.py", line 125, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_remote.py", line 78, in <lambda>
    start_client=(lambda daemon, h, port: start_daemon()),
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_remote.py", line 70, in start_daemon
    _, next_session = daemon.start_server(addr=(host, port))
  File "/usr/local/lib/python3.7/site-packages/ptvsd/daemon.py", line 157, in start_server
    self._server = create_server(addr.host, addr.port)
  File "/usr/local/lib/python3.7/site-packages/ptvsd/socket.py", line 79, in create_server
    server.bind((host, port))
OSError: [Errno 98] Address already in use
```

## Expected  behavior
Should start with no such exception as i m binding to a different port.

## Steps to reproduce:
Create a docker image using the code i posted above should be able to reproduce the exception.

**Comment by karthiknadig** [comment]
Can you share the `docker run` command that you use?

**Comment by karthiknadig** [comment]
I see what is going on here. since you are running `python myapp.py` this is loading the app twice. You can see the port is printed twice. So the debug server gets initialized twice.

You can run it using debugger CLI to run module: `python -m ptvsd --host 0.0.0.0 --port 5678 -m flask run`. This is how we launch it when running directly from VSC.

If you have to run this way, add `try ... except` around `ptvsd.enable_attach`.

**Comment by karthiknadig** [comment]
@int19h we should add a check to prevent `enable_attach` from executing multiple times in the same process.

**Comment by int19h** [comment]
I think we already do that. But is this the same process? Note that debug mode is on, which implies a second process for live code reload. I think what's happening here is that the child process tries to use the same port?

**Comment by karthiknadig** [comment]
@int19h you are right. 
@Anakin-Hao Ensure that you have  `flask` running with `--no-reload`:
```
python -m ptvsd --host 0.0.0.0 --port 5678 -m flask run --no-reload --with-threads
```
Or start the debugger with `--multiprocess`:
```
python -m ptvsd --host 0.0.0.0 --port 5678 --multiprocess -m flask run
```
try those methods to launch `flask` than using `enable_attach`
