### ISSUE TITLE
Attatch via pid fails on automated runs with missing dbghelp.dll error

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1144]
## Environment data

- PTVSD version: master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): any
- Using VS Code or Visual Studio: N/A

## Actual behavior

```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.4\x64\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\hostedtoolcache\windows\Python\3.6.4\x64\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\__main__.py", line 365, in <module>
    main(sys.argv)
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\__main__.py", line 353, in main
    run()
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\__main__.py", line 336, in attach_to_pid
    run_python_code(pid, code, connect_debugger_tracing=True)
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_attach_to_process\add_code_to_python_process.py", line 272, in run_python_code_windows
    from winappdbg import compat
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\__init__.py", line 234, in <module>
    from winappdbg.breakpoint import *
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\breakpoint.py", line 65, in <module>
    from winappdbg import win32
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\__init__.py", line 45, in <module>
    from winappdbg.win32 import dbghelp
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\dbghelp.py", line 79, in <module>
    _load_latest_dbghelp_dll()
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\dbghelp.py", line 63, in _load_latest_dbghelp_dll
    "dbghelp.dll")
  File "d:\a\1\s\.tox\py36\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Expected  behavior

Should attach to the process.

**Comment by fabioz** [comment]
Loading `dbghelp.dll` from that location is actually optional (the problem was that the `ProgramFiles` environment variable wasn't available in your case -- not sure why thought).

So, just created a pull request that will provide a default value if that environment variable cannot be found.

As a note, you could install the latest `dbghelp.dll` following: http://msdn.microsoft.com/en-us/library/windows/desktop/ms679294(v=vs.85).aspx, but it's only needed if you want to have the latest version as each version of windows ships with a default version which will be used if it can't be loaded from the program files.

So, please try again in your env after that pull request is merged.
