### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1183]
## Environment data

- PTVSD version: master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

```
Traceback (most recent call last):
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 271, in handle_exception
    self.do_wait_suspend(thread, frame, event, arg)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 78, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1265, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1281, in _do_wait_suspend
    self.process_internal_commands()
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1004, in process_internal_commands
    int_cmd.do_it(self)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 484, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 654, in internal_get_variable_json
    for child_var in variable.get_children_variables(fmt=fmt):
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_suspended_frames.py", line 97, in get_children_variables
    lst = resolver.get_contents_debug_adapter_protocol(self.value)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_resolver.py", line 93, in get_contents_debug_adapter_protocol
    lst = sorted(dict_iter_items(dct), key=sorted_attributes_key)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_resolver.py", line 65, in sorted_attributes_key
    if attr_name.startswith('__'):
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by fabioz** [comment]
Will take a look at this.
