### ISSUE TITLE
ValueError: stat: path too long for Windows

### ISSUE THREAD

**Issue by zooba** [Microsoft/ptvsd#119]
```
Traceback (most recent call last):
  File "C:\Users\stevdo\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1\env1\lib\site-packages\ptvsd\wrapper.py", line 456, in done
    fut.result()
  File "C:\Users\stevdo\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1\env1\lib\site-packages\ptvsd\futures.py", line 39, in result
    reraise(self._exc_info)
  File "C:\Users\stevdo\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1\env1\lib\site-packages\ptvsd\reraise3.py", line 11, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\stevdo\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1\env1\lib\site-packages\ptvsd\futures.py", line 154, in callback
    x = it.send(fut.result())
  File "C:\Users\stevdo\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1\env1\lib\site-packages\ptvsd\wrapper.py", line 623, in on_variables
    xml = untangle.parse(resp_args).xml
  File "C:\Users\stevdo\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1\env1\lib\site-packages\ptvsd\untangle.py", line 188, in parse
    if is_string(filename) and (os.path.exists(filename) or is_url(filename)):
  File "C:\Users\stevdo\AppData\Local\Programs\Python\Python36\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: path too long for Windows
```

**Comment by int19h** [comment]
The relevant untangle bug: https://github.com/stchris/untangle/issues/45

**Comment by longrobert** [comment]
you can fix it very easily. I have the personal suggestion for you, you can use the LongPathTool program. I am also using this tools. Hope your all problem will solve very fast.

**Comment by karthiknadig** [comment]
@longrobert This was a issue with the untangle API and has nothing to do with actual file paths.

**Comment by DavidGaller** [comment]
I have faced this problem once upon a time but when knowing about the LongPathTool program, at that time I am using this tools and all problem solve. so my personal suggestion you can use the LongPathTool program
