### ISSUE TITLE
Error seen on disconnect from remote machine

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1202]
## Environment data

- PTVSD version: master
- OS and version: Windows local, Linux remote
- Python version (& distribution if applicable, e.g. Anaconda): Conda
- Using VS Code or Visual Studio: VSC

## Actual behavior

```
Traceback (most recent call last):
              File "/azureml-envs/azureml_/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 279, in process_one_message
                msg = self.__message.pop(0)
            IndexError: pop from empty list
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "/azureml-envs/azureml_/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 284, in process_one_message
                msg = self.__message.pop(0)
            IndexError: pop from empty list
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "/azureml-envs/azureml_/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 268, in process_messages
                self.process_one_message()
              File "/azureml-envs/azureml_/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 290, in process_one_message
                raise EOFError('no more messages')
            EOFError: no more messages
```

**Comment by int19h** [comment]
Should be fixed by 4d4a572ca291aa9ae6f4e3c85440b8700ab52199
