### ISSUE TITLE
Having Json parsing problem with ptvsd

### ISSUE THREAD

**Issue by nazmulhasan85** [Microsoft/ptvsd#1231]
## Environment data

- PTVSD version: 4.2.4
- OS and version: Ubuntu 18.04, but code was running on docker.
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.9
- Using VS Code or Visual Studio: VS Code

## Actual behavior

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/wrapper.py", line 885, in process_messages
    self.process_messages()
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/ipcjson.py", line 268, in process_messages
    self.process_one_message()
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/ipcjson.py", line 282, in process_one_message
    self._wait_for_message()
  File "/usr/local/lib/python2.7/dist-packages/ptvsd/ipcjson.py", line 167, in _wait_for_message
    "Malformed header, expected 'name: value'\n" + line)
InvalidHeaderError: Malformed header, expected 'name: value'

```

## Expected  behavior

It was working fine with python 3.6.

## Steps to reproduce:
Use python 2.7.9

**Comment by karthiknadig** [comment]
Can you provide more details on how to reproduce this? Also, would it be possible to try with 2.7.15 or 2.7.16?

**Comment by karthiknadig** [comment]
Repro code is required here. Please reopen with the requested details.
