### ISSUE TITLE
Attach to process fails with "RuntimeError: Could not find dll file" on Ubuntu 14.04

### ISSUE THREAD

**Issue by sunew** [microsoft/ptvsd#1239]
## Environment data

- PTVSD version: 4.2.4
- OS and version: Ubuntu 14.04.5 LTS
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.6, virtualenv
- Using VS Code or Visual Studio: vscode

## Actual behavior

With virtualenv acitvated:

`python2.7 -m ptvsd --host 10.5.10.5 --port 3000 --pid 27723`

Gives this traceback: 

```

Attaching with arch: i386:x86-64
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/elasticbox/working/elasticbox/lib/python2.7/site-packages/ptvsd/__main__.py", line 369, in <module>
    main(sys.argv)
  File "/opt/elasticbox/working/elasticbox/lib/python2.7/site-packages/ptvsd/__main__.py", line 357, in main
    run()
  File "/opt/elasticbox/working/elasticbox/lib/python2.7/site-packages/ptvsd/__main__.py", line 340, in attach_to_pid
    run_python_code(pid, code, connect_debugger_tracing=True)
  File "/opt/elasticbox/working/elasticbox/local/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 419, in run_python_code_linux
    raise RuntimeError('Could not find dll file to inject: %s' % target_dll)
RuntimeError: Could not find dll file to inject: /opt/elasticbox/working/elasticbox/local/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so

```

## Expected  behavior

A successful attachment, making it possible to connect from vscode on the ip and port.

## Steps to reproduce:
See above.

**Comment by karthiknadig** [comment]
Similar to #863, but it fails in a different area. @sunew I recommend using ptvsd to directly launch the code you want to debug, or use `ptvsd.enable_attach()` in your script. We are currently working on other areas of the debugger and will get to the attach to pid issue later.

**Comment by sunew** [comment]
@karthiknadig thanks, yes I use `ptvsd.enable_attach()` for now. Will be very practical when we get attach to process to work:)

**Comment by fabioz** [comment]
Closing this one in favor of: https://github.com/microsoft/ptvsd/issues/863 (issue seems different but it's actually the same problem).
