### ISSUE TITLE
I cant launch python file in integrated or external terminal.

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1258]
@erkus-circus commented on [Thu Mar 21 2019](https://github.com/Microsoft/vscode-python/issues/4877)
```
Traceback (most recent call last):
  File "c:\Users\eric\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\eric\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\eric\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\_vendored\force_pydevd.py", line 40, in <module>
    'pydevd',
  File "c:\Users\eric\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 123, in preimport
    import_module(name)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\eric\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd_plugins\__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

**Comment by karthiknadig** [comment]
@erkus-circus can you share your launch.json settings. If possible share a minimal repro for this.

**Comment by erkus-circus** [comment]
Here is my launch.json:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Terminal (integrated)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Terminal (external)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "externalTerminal"
        }
    ]
}`

**Comment by karthiknadig** [comment]
This does not looks like it is related to ptvsd. Can you try following the instructions here to fix it?
https://stackoverflow.com/questions/44761958/using-pip3-module-importlib-bootstrap-has-no-attribute-sourcefileloader

**Comment by karthiknadig** [comment]
Please reopen if you feel this is still a debugger issue.
