### ISSUE TITLE
KeyError when using latest VSCode Python extension

### ISSUE THREAD

**Issue by jessey-git** [Microsoft/ptvsd#1285]
## Environment data

- PTVSD version: 4.2.0
- OS and version: Win10 1803
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.1 installed on system
- Using VS Code or Visual Studio: VSCode 1.32.3 (Python extension 2019.3.6215)

## Actual behavior
The latest Python extension for VSCode seems to have broken debugging:
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\ptvsd\wrapper.py", line 1339, in done
    fut.result()
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\ptvsd\futures.py", line 149, in callback
    x = next(it)
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\ptvsd\wrapper.py", line 1958, in on_evaluate
    pyd_tid, pyd_fid = self.frame_map.to_pydevd(vsc_fid)
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\ptvsd\wrapper.py", line 283, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
KeyError: 1
```

## Expected  behavior
This was fine with Python extension 2019.2.5433.  

## Steps to reproduce:
1. Install latest VSCode + Python extension
2. Attempt to debug some python running in an external process
3. The debugger will stop at breakpoints but Watch/Locals/etc. don't work

**Comment by karthiknadig** [comment]
@jessey-git Make sure you are using the latest ptvsd which is v4.2.5. If you want to debug processes launched by your code, make sure that in your launch configuration has `"subProcess": true,`, and `pathMappings`.

```js
"pathMappings": [{
    "localRoot": "${workspaceFolder}",
    "remoteRoot": "."
}],
"subProcess": true,
```

If the above does not works for you, please provide a minimal repro.

**Comment by karthiknadig** [comment]
#1286 should help with the watch and hover. Is there anything else that is not working?

**Comment by karthiknadig** [comment]
Use 4.2.6, it contains fix for watch and hover issue.
