### ISSUE TITLE
Partial socket reads in test_deep_stacks

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#1303]
This happens in `test_deep_stacks` sporadically. 
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\messaging.py", line 430, in _process_incoming_messages
    message = self.stream.read_json()
  File "D:\a\1\s\tests\helpers\messaging.py", line 53, in read_json
    value = self.stream.read_json()
  File "d:\a\1\s\.tox\py36\lib\site-packages\ptvsd\messaging.py", line 118, in read_json
    body = json.loads(body)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 14596 (char 14595)
```
The message, as expected for this test, is the `stackTrace` response, that just happens to be cut off in the middle of a string literal.

I believe the problem is that `JsonIOStream.read_json` assumes that once it has the length, it can just pass it to `read` and get that many bytes back - which works with files, but with sockets you can get a partial read, and it's more likely with very large messages that span multiple packets.

Note that this isn't strictly a test issue, since we also use this code in the product for multiproc - but it's unlikely to manifest, because all messages there tend to be small.

**Comment by karthiknadig** [comment]
Does this mean, potentially source reference can fail as well. due to the size if content it can return?

**Comment by int19h** [comment]
On the test side, yes, it looks like it could.
