### ISSUE TITLE
Giving error while importing webdriver from selenium

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1350]
@maazhussaini commented on [Tue Apr 09 2019](https://github.com/Microsoft/vscode-python/issues/5175)

DevTools listening on ws://127.0.0.1:59339/devtools/browser/32428de5-5c5f-48dd-a12d-b792b479158a
```
Traceback (most recent call last):
  File "c:\Users\skr25\.vscode\extensions\ms-python.python-2019.3.6352\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\skr25\.vscode\extensions\ms-python.python-2019.3.6352\pythonFiles\lib\python\ptvsd\__main__.py", line 391, in main
    run()
  File "c:\Users\skr25\.vscode\extensions\ms-python.python-2019.3.6352\pythonFiles\lib\python\ptvsd\__main__.py", line 272, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\skr25\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\skr25\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\skr25\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\Python OOP\Lab\facebook.py", line 8, in <module>
    driver = webdriver.Chrome(path)
  File "C:\Users\skr25\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\skr25\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\skr25\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\skr25\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\skr25\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)
```

**Comment by fabioz** [comment]
@maazhussaini can you give more details? From the stack trace this doesn't seem like there's anything actually caused by `ptvsd`.

**Comment by karthiknadig** [comment]
Please reopen when more details are available.
