### ISSUE TITLE
Exception when debugging code with multiprocessing module

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1357]
@hubitor commented on [Sun Apr 14 2019](https://github.com/Microsoft/vscode-python/issues/5251)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.3.6558
- OS and version: Arch Linux (x64 4.19.34-1-lts)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.2 (Anaconda 3-.5.0.0)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
- Relevant/affected Python packages and their versions: 

## Expected behaviour

Complete debugging without exceptions

## Actual behaviour

An exception occurs during debugging python script with multiprocessing (see below). The code runs fine with "Code Runner". I've tried with different python interpreters and also without any virtual environment with the same result. I'm using the default debug configuration (launch.json):

```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
```

## Steps to reproduce:
1. Debug any python script with multiprocessing package imported. E.g. :

```
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

[Info  - 4:26:35 PM] GetCurrentSearchPaths /home/user/.pyenv/versions/anaconda3-5.0.0/bin/python 
[Info  - 4:26:35 PM] Python search paths:
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/lib-dynload
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages
[Info  - 4:26:35 PM] Configuration search paths:
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python36.zip
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/lib-dynload
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages
[Info  - 4:26:35 PM]     /home/user/.pyenv/versions/anaconda3-5.0.0/bin
[Info  - 4:26:37 PM] Microsoft Python Language Server version 0.2.47.0
[Info  - 4:26:37 PM] Initializing for /home/user/.pyenv/versions/anaconda3-5.0.0/bin/python
##########Linting Output - pylint##########
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
(I couldn't find it...)
```

Output from terminal:

```
cd /home/user/workspace/python/pythonv3/Multiprocessing ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/user/.pyenv/versions/anaconda3-5.0.0/bin/python /home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 45251 /home/user/workspace/python/pythonv3/Multiprocessing/mp06.py 
E00000.272: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/contextlib.py", line 81, in __enter__
                return next(self.gen)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

E00000.300: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/contextlib.py", line 81, in __enter__
                return next(self.gen)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

E00000.301: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/contextlib.py", line 81, in __enter__
                return next(self.gen)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

E00000.334: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/user/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/contextlib.py", line 81, in __enter__
                return next(self.gen)
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/user/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

[1]    12744 terminated  env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1   --default --client --host   
```

---

@cspwizard commented on [Mon Apr 15 2019](https://github.com/Microsoft/vscode-python/issues/5251#issuecomment-483347475)

I've the same exception with vanilla python 3.7

**Comment by fabioz** [comment]
@hubitor
@cspwizard

This issue (supporting fork in the debugger) is being tracked in https://github.com/Microsoft/ptvsd/issues/943, so, closing this one as a duplicate.

Please see: https://github.com/Microsoft/ptvsd/issues/943#issuecomment-480782087 for a possible workaround (it may or may not work depending on your use-case).

**Comment by karthiknadig** [comment]
![image](https://user-images.githubusercontent.com/3840081/56156320-e0dc7c00-5f71-11e9-9947-ea25f8933cc4.png)
