### ISSUE TITLE
Internal error detected

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1411]
@wencan commented on [Sun May 05 2019](https://github.com/microsoft/vscode-python/issues/5557)

Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64

cd /home/user/Projects/company/project ; env FLASK_APP=manager:app PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/local/bin/python3 /home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 39073 -m flask run --no-reload --host 0.0.0.0 
```
^CTraceback (most recent call last):
  File "/home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "/home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__init__.py", line 15, in <module>
    from ptvsd.attach_server import (  # noqa
  File "/home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/attach_server.py", line 8, in <module>
    from ptvsd._remote import (
  File "/home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_remote.py", line 15, in <module>
    from ptvsd.pydevd_hooks import install
  File "/home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 16, in <module>
    from ptvsd.daemon import Daemon, DaemonStoppedError, DaemonClosedError
  File "/home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 10, in <module>
    from ptvsd import wrapper, options, multiproc
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
KeyboardInterrupt
```

**Comment by int19h** [comment]
The error in the log is `KeyboardInterrupt`, which occurred because Ctrl+C was pressed (hence `^C` at the beginning) - this is intended behavior. It just happened to be inside debugger code when that happened, which also happens. 

I suspect that the real problem was whatever prompted Ctrl+C to begin with. @wencan, can you please clarify?

**Comment by wencan** [comment]
I pressed Ctrl+C, vscode outputted this prompt and asked me to post the information to https://github.com/microsoft/vscode-python/issues

**Comment by int19h** [comment]
Ah, so it wasn't because the debugger was stuck or something like that? Just an expected interruption, with misleading error reporting afterwards?

**Comment by karthiknadig** [comment]
Please reopen if this issue occurs again.
