### ISSUE TITLE
subProcess launch configuration option does not work for multiprocessing.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1441]
@derekgorcz commented on [Sun May 19 2019](https://github.com/microsoft/vscode-python/issues/5687)

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv

## Expected behaviour

multiprocessing should work with "subProcess" set to true.

## Actual behaviour

Debugger crashes when calling `start()` on a process object created with ` multiprocessing.Process()`.

## Steps to reproduce:
1. Given the python source:
```
import multiprocessing
import time

def sub_proc():
    print('Starting: ' + multiprocessing.current_process().name)
    time.sleep(2)
    print('Exiting : ' + multiprocessing.current_process().name)

if __name__ == '__main__':
    p = multiprocessing.Process(name='sub_proc', target=sub_proc)

    p.start()
    time.sleep(1)

    p.join()
```
And launch configuration
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "subProcess": true,
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```
2. Run above with given configuration.
## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
E00000.015: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 217, in start_client
                connect(client, addr)
              File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/socket.py", line 197, in connect
                sock.connect(addr)
            ConnectionRefusedError: [Errno 111] Connection refused
            

Traceback (most recent call last):
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 410, in main
    run()
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 275, in run_file
    setup_connection()
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 266, in setup_connection
    daemon = ptvsd._remote.attach(addr)
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_remote.py", line 120, in attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1844, in settrace
    stop_at_frame,
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1894, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 855, in connect
    s = start_client(host, port)
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 132, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
    return f(*args, **kwargs)
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 217, in start_client
    connect(client, addr)
  File "/home/derek/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/socket.py", line 197, in connect
    sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by karthiknadig** [comment]
@derekgorcz Try these instructions to get multi-process working with Ubuntu:
https://github.com/microsoft/ptvsd/blob/master/TROUBLESHOOTING.md#1-multiprocessing-on-linuxmac

**Comment by derekgorcz** [comment]
Using spawn fixes the issue; however, spawn does not always provide the same functionality. This slightly more complex example won't work using the spawn method.
```python
import multiprocessing
import time
import sys
import os

multiprocessing.set_start_method('spawn', True)

def sub_proc(newstdin):
    sys.stdin = newstdin
    print('Starting: ' + multiprocessing.current_process().name)
    print(input('--> '))
    print('Exiting : ' + multiprocessing.current_process().name)

if __name__ == '__main__':
    newstdin = os.fdopen(os.dup(sys.stdin.fileno()))
    p = multiprocessing.Process(name='sub_proc', target=sub_proc, args=(newstdin,))

    p.start()
    time.sleep(1)

    p.join()
```
It will fail with the following error.
```
python3.6 blah.py                                                                                                                                                            
Traceback (most recent call last):
  File "blah.py", line 18, in <module>
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
```

**Comment by karthiknadig** [comment]
We plan on having support for `fork` see #943. We are currently refactoring the debugger to support that.
