### ISSUE TITLE
Starting debugger fails with KeyError

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1483]
@zaro commented on [Thu May 30 2019](https://github.com/microsoft/vscode-python/issues/5843)

## Environment data
- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 2019.5.17059
- OS and version: Fedora 30
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 installed from system rpm
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): direnv
- Relevant/affected Python packages and their versions: Flask==1.0.3

## Expected behaviour

I have a flask app, and in the last months I've been using the debugger to debug the app occasionally and everything was working as expected. 

## Actual behaviour
Since today ( or  maybe yesterday ) The debugger won't start anymore. Debugging single tests (pytest) also doesn't work.

## Steps to reproduce:

1. Open python flask project
2. Press F5 to debug the project

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
$ cd /home/zaro/dev/my-api ; env FLASK_DEBUG=1 FLASK_ENV=development FLASK_APP=app.main FLASK_RUN_PORT=3000 ...MORE_ENV_VARS... PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/zaro/dev/my-api/.direnv/python-3.6.8/bin/python /home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 43077 -m flask run --no-debugger --no-reload 
Traceback (most recent call last):
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 574, in _norm_file_to_server
    return cache[filename]
KeyError: 'git:/home/zaro/dev/my-api/pack/db/base/filter.py?%7B%22path%22%3A%22%2Fhome%2Fzaro%2Fdev%2Fmy-api%2Fpack%2Fdb%2Fbase%2Ffilter.py%22%2C%22ref%22%3A%22~%22%7D'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 277, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 199, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 468, in on_setbreakpoints_request
    filename = self.api.filename_to_server(filename)
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 251, in filename_to_server
    return pydevd_file_utils.norm_file_to_server(filename)
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 607, in _norm_file_to_server
    (filename, ', '.join(['"%s"' % (x[0],) for x in paths_from_eclipse_to_python])))
  File "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_log.py", line 96, in error_once
    message = msg % args
TypeError: not enough arguments for format string
```

**Comment by DonJayamanne** [comment]
@karthiknadig Possibly another P0

**Comment by karthiknadig** [comment]
@zaro Can you add `"PTVSD_LOG_DIR": "<path to log directory>"` to "env" in launch json. and share the debugger logs?

**Comment by karthiknadig** [comment]
@zaro Can you also share `launch.json` for this?

**Comment by AW2Temp** [comment]
I get a similar error, with my VS Code stating it cannot open "ptvsd_launcher.py".  When I ran the file alone it gave me "list index out of range".

![image](https://user-images.githubusercontent.com/38325685/58689238-c118e000-8386-11e9-9e28-13f8293cf649.png)

If you check the image the highlighted lines causes errors

**Comment by AW2Temp** [comment]
Roll back to an older version.

**Comment by zaro** [comment]
@karthiknadig 
my launch.json 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost"
        },
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "enter-your-module-name-here",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        },
        {
            "name": "Python: Celery",
            "type": "python",
            "request": "launch",
            "module": "celery",
            "env": {
            },
            "args": [
                "--app=tasks",
                "worker"
            ],
            "jinja": true
        }
    ]
}
```

And here is a debug log generated as you suggested:
```
I00000.019: Linux-5.0.17-300.fc30.x86_64-x86_64-with-fedora-30-Thirty x86_64
            CPython 3.6.8 (64-bit)
            ptvsd 4.2.10

I00000.020: main(['/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py', '--client', '--host', 'localhost', '--port', '33607', '-m', 'flask', 'run', '--no-debugger', '--no-reload'])

I00000.020: sys.argv after parsing: ['/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py', 'run', '--no-debugger', '--no-reload']

D00000.020: sys.prefix: ('/home/zaro/dev/gid-api/.direnv/python-3.6.8',)

D00000.020: sys.base_prefix: /home/zaro/dev/gid-api/.direnv/python-3.6.8

D00000.020: sys.real_prefix: /usr

D00000.020: Folder with "site-packages" in sys.path: /home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages

D00000.022: sysconfig platlib: /home/zaro/dev/gid-api/.direnv/python-3.6.8/lib64/python3.6/site-packages

D00000.022: sysconfig stdlib: /home/zaro/dev/gid-api/.direnv/python-3.6.8/lib64/python3.6

D00000.022: sysconfig platstdlib: /home/zaro/dev/gid-api/.direnv/python-3.6.8/lib64/python3.6

D00000.023: sysconfig purelib: /home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages

D00000.023: os dir: /home/zaro/dev/gid-api/.direnv/python-3.6.8/lib64/python3.6

D00000.023: threading dir: /usr/lib64/python3.6

D00000.023: sys.argv after patching: ['/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/flask/__init__.py', 'run', '--no-debugger', '--no-reload']

D00000.024: Installing pydevd hooks.

D00000.024: Monkey-patching multiprocess functions.

D00000.024: pydevd.settrace()

D00000.026: Starting client daemon on ('localhost', 33607).

D00000.028: IDE <-- {
                "type": "event",
                "seq": 0,
                "event": "output",
                "body": {
                    "category": "telemetry",
                    "output": "ptvsd",
                    "data": {
                        "version": "4.2.10"
                    }
                }
            }

D00000.030: IDE --> {
                "command": "launch",
                "arguments": {
                    "name": "Python: Flask",
                    "type": "python",
                    "request": "launch",
                    "module": "flask",
                    "env": {
                        "FLASK_APP": "app.py",
                        "PTVSD_LOG_DIR": "/home/zaro/dev/gid-api/debug_log"
                    },
                    "args": [
                        "run",
                        "--no-debugger",
                        "--no-reload"
                    ],
                    "jinja": true,
                    "pythonPath": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/bin/python",
                    "cwd": "/home/zaro/dev/gid-api",
                    "envFile": "/home/zaro/dev/gid-api/.env",
                    "stopOnEntry": false,
                    "showReturnValue": true,
                    "console": "integratedTerminal",
                    "internalConsoleOptions": "neverOpen",
                    "debugOptions": [
                        "ShowReturnValue",
                        "Jinja",
                        "RedirectOutput"
                    ],
                    "justMyCode": true,
                    "workspaceFolder": "/home/zaro/dev/gid-api",
                    "pathMappings": [
                        {
                            "localRoot": "/home/zaro/dev/gid-api",
                            "remoteRoot": "."
                        }
                    ],
                    "__sessionId": "8f0d8dcb-ad9b-4ba1-b738-6742c56b619b"
                },
                "type": "request",
                "seq": 2
            }

D00000.038: (while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            PYD <-- CMD_SET_PROTOCOL 1000000000 json

D00000.038: (while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            PYD <-- {
                "command": "setDebuggerProperty",
                "arguments": {
                    "dontTraceStartPatterns": [
                        "/home/zaro/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/lib/python/ptvsd/"
                    ],
                    "dontTraceEndPatterns": [
                        "ptvsd_launcher.py"
                    ],
                    "skipSuspendOnBreakpointException": [
                        "BaseException"
                    ],
                    "skipPrintBreakpointException": [
                        "NameError"
                    ],
                    "multiThreadsSingleNotification": true,
                    "ideOS": "UNIX"
                },
                "type": "request",
                "seq": 1000000001
            }

D00000.039: (requested while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            PYD --> CMD_SET_PROTOCOL 1000000000
            

D00000.040: (while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            IDE <-- {
                "type": "response",
                "seq": 1,
                "request_seq": 2,
                "success": true,
                "command": "launch",
                "message": "",
                "body": {}
            }

D00000.041: (requested while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            PYD --> {
                "type": "response",
                "request_seq": 1000000001,
                "success": true,
                "command": "setDebuggerProperty",
                "seq": 2,
                "body": {},
                "pydevd_cmd_id": 502
            }

D00000.041: IDE --> {
                "command": "initialize",
                "arguments": {
                    "clientID": "vscode",
                    "clientName": "Visual Studio Code",
                    "adapterID": "python",
                    "pathFormat": "path",
                    "linesStartAt1": true,
                    "columnsStartAt1": true,
                    "supportsVariableType": true,
                    "supportsVariablePaging": true,
                    "supportsRunInTerminalRequest": true,
                    "locale": "en-gb"
                },
                "type": "request",
                "seq": 1
            }

D00000.042: (while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            PYD <-- {
                "command": "launch",
                "arguments": {
                    "name": "Python: Flask",
                    "type": "python",
                    "request": "launch",
                    "module": "flask",
                    "env": {
                        "FLASK_APP": "app.py",
                        "PTVSD_LOG_DIR": "/home/zaro/dev/gid-api/debug_log"
                    },
                    "args": [
                        "run",
                        "--no-debugger",
                        "--no-reload"
                    ],
                    "jinja": true,
                    "pythonPath": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/bin/python",
                    "cwd": "/home/zaro/dev/gid-api",
                    "envFile": "/home/zaro/dev/gid-api/.env",
                    "stopOnEntry": false,
                    "showReturnValue": true,
                    "console": "integratedTerminal",
                    "internalConsoleOptions": "neverOpen",
                    "debugOptions": [
                        "ShowReturnValue",
                        "Jinja",
                        "RedirectOutput"
                    ],
                    "justMyCode": true,
                    "workspaceFolder": "/home/zaro/dev/gid-api",
                    "pathMappings": [
                        {
                            "localRoot": "/home/zaro/dev/gid-api",
                            "remoteRoot": "."
                        }
                    ],
                    "__sessionId": "8f0d8dcb-ad9b-4ba1-b738-6742c56b619b"
                },
                "type": "request",
                "seq": 1000000002
            }

D00000.042: (while handling {'command': 'initialize', 'type': 'request', 'seq': 1})
            IDE <-- {
                "type": "response",
                "seq": 2,
                "request_seq": 1,
                "success": true,
                "command": "initialize",
                "message": "",
                "body": {
                    "supportsCompletionsRequest": true,
                    "supportsConditionalBreakpoints": true,
                    "supportsConfigurationDoneRequest": true,
                    "supportsDebuggerProperties": true,
                    "supportsDelayedStackTraceLoading": true,
                    "supportsEvaluateForHovers": true,
                    "supportsExceptionInfoRequest": true,
                    "supportsExceptionOptions": true,
                    "supportsHitConditionalBreakpoints": true,
                    "supportsLogPoints": true,
                    "supportsModulesRequest": true,
                    "supportsSetExpression": true,
                    "supportsSetVariable": true,
                    "supportsValueFormattingOptions": true,
                    "supportTerminateDebuggee": true,
                    "supportsGotoTargetsRequest": true,
                    "exceptionBreakpointFilters": [
                        {
                            "filter": "raised",
                            "label": "Raised Exceptions",
                            "default": false
                        },
                        {
                            "filter": "uncaught",
                            "label": "Uncaught Exceptions",
                            "default": true
                        }
                    ]
                }
            }

D00000.043: PYD --> {
                "type": "event",
                "event": "process",
                "body": {
                    "name": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/flask/__init__.py",
                    "systemProcessId": 9370,
                    "isLocalProcess": true,
                    "startMethod": "launch"
                },
                "seq": 4,
                "pydevd_cmd_id": 204
            }

D00000.043: (while handling {'command': 'initialize', 'type': 'request', 'seq': 1})
            IDE <-- {
                "type": "event",
                "seq": 3,
                "event": "initialized",
                "body": {}
            }

D00000.044: (while handling ('CMD_PROCESS_EVENT', 4))
            IDE <-- {
                "type": "event",
                "seq": 4,
                "event": "process",
                "body": {
                    "name": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/flask/__init__.py",
                    "systemProcessId": 9370,
                    "isLocalProcess": true,
                    "startMethod": "launch"
                }
            }

D00000.044: (requested while handling {'command': 'launch', 'type': 'request', 'seq': 2})
            PYD --> {
                "type": "response",
                "request_seq": 1000000002,
                "success": true,
                "command": "launch",
                "seq": 6,
                "pydevd_cmd_id": 502
            }

D00000.102: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "app.py",
                        "path": "/home/zaro/dev/gid-api/app/app.py"
                    },
                    "lines": [],
                    "breakpoints": [],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 4
            }

D00000.103: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 4})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "app.py",
                        "path": "/home/zaro/dev/gid-api/app/app.py"
                    },
                    "lines": [],
                    "breakpoints": [],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000003
            }

D00000.108: (requested while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 4})
            PYD --> {
                "type": "response",
                "request_seq": 1000000003,
                "success": true,
                "command": "setBreakpoints",
                "body": {
                    "breakpoints": []
                },
                "seq": 8,
                "pydevd_cmd_id": 502
            }

D00000.109: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 4})
            IDE <-- {
                "type": "response",
                "seq": 5,
                "request_seq": 4,
                "success": true,
                "command": "setBreakpoints",
                "message": "",
                "body": {
                    "breakpoints": []
                }
            }

D00000.110: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "change_status.py",
                        "path": "/home/zaro/dev/gid-api/gid/job_status/admin/change_status.py"
                    },
                    "lines": [
                        89
                    ],
                    "breakpoints": [
                        {
                            "line": 89
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 5
            }

D00000.110: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 5})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "change_status.py",
                        "path": "/home/zaro/dev/gid-api/gid/job_status/admin/change_status.py"
                    },
                    "lines": [
                        89
                    ],
                    "breakpoints": [
                        {
                            "line": 89
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000004
            }

D00000.111: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "conftest.py",
                        "path": "/home/zaro/dev/gid-api/tests/conftest.py"
                    },
                    "lines": [],
                    "breakpoints": [],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 6
            }

D00000.111: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 6})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "conftest.py",
                        "path": "/home/zaro/dev/gid-api/tests/conftest.py"
                    },
                    "lines": [],
                    "breakpoints": [],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000005
            }

D00000.112: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "connection.py",
                        "path": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/kombu/connection.py"
                    },
                    "lines": [
                        197
                    ],
                    "breakpoints": [
                        {
                            "line": 197
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 7
            }

D00000.112: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 7})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "connection.py",
                        "path": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/kombu/connection.py"
                    },
                    "lines": [
                        197
                    ],
                    "breakpoints": [
                        {
                            "line": 197
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000006
            }

D00000.113: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "filter.py",
                        "path": "git:/home/zaro/dev/gid-api/gid/db/base/filter.py?%7B%22path%22%3A%22%2Fhome%2Fzaro%2Fdev%2Fgid-api%2Fgid%2Fdb%2Fbase%2Ffilter.py%22%2C%22ref%22%3A%22~%22%7D"
                    },
                    "lines": [
                        42
                    ],
                    "breakpoints": [
                        {
                            "line": 42
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 8
            }

D00000.116: (requested while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 5})
            PYD --> {
                "type": "response",
                "request_seq": 1000000004,
                "success": true,
                "command": "setBreakpoints",
                "body": {
                    "breakpoints": [
                        {
                            "id": 0,
                            "verified": true,
                            "line": 88
                        }
                    ]
                },
                "seq": 10,
                "pydevd_cmd_id": 502
            }

D00000.117: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 8})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "filter.py",
                        "path": "git:/home/zaro/dev/gid-api/gid/db/base/filter.py?%7B%22path%22%3A%22%2Fhome%2Fzaro%2Fdev%2Fgid-api%2Fgid%2Fdb%2Fbase%2Ffilter.py%22%2C%22ref%22%3A%22~%22%7D"
                    },
                    "lines": [
                        42
                    ],
                    "breakpoints": [
                        {
                            "line": 42
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000007
            }

D00000.118: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 5})
            IDE <-- {
                "type": "response",
                "seq": 6,
                "request_seq": 5,
                "success": true,
                "command": "setBreakpoints",
                "message": "",
                "body": {
                    "breakpoints": [
                        {
                            "id": 0,
                            "verified": true,
                            "line": 88
                        }
                    ]
                }
            }

D00000.118: (requested while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 6})
            PYD --> {
                "type": "response",
                "request_seq": 1000000005,
                "success": true,
                "command": "setBreakpoints",
                "body": {
                    "breakpoints": []
                },
                "seq": 12,
                "pydevd_cmd_id": 502
            }

D00000.119: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "flaskparser.py",
                        "path": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/webargs/flaskparser.py"
                    },
                    "lines": [
                        58,
                        75
                    ],
                    "breakpoints": [
                        {
                            "line": 58
                        },
                        {
                            "line": 75
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 9
            }

D00000.119: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 6})
            IDE <-- {
                "type": "response",
                "seq": 7,
                "request_seq": 6,
                "success": true,
                "command": "setBreakpoints",
                "message": "",
                "body": {
                    "breakpoints": []
                }
            }

D00000.121: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 9})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "flaskparser.py",
                        "path": "/home/zaro/dev/gid-api/.direnv/python-3.6.8/lib/python3.6/site-packages/webargs/flaskparser.py"
                    },
                    "lines": [
                        58,
                        75
                    ],
                    "breakpoints": [
                        {
                            "line": 58
                        },
                        {
                            "line": 75
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000008
            }

D00000.130: (requested while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 7})
            PYD --> {
                "type": "response",
                "request_seq": 1000000006,
                "success": true,
                "command": "setBreakpoints",
                "body": {
                    "breakpoints": [
                        {
                            "id": 1,
                            "verified": true,
                            "line": 197
                        }
                    ]
                },
                "seq": 14,
                "pydevd_cmd_id": 502
            }

D00000.131: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 7})
            IDE <-- {
                "type": "response",
                "seq": 8,
                "request_seq": 7,
                "success": true,
                "command": "setBreakpoints",
                "message": "",
                "body": {
                    "breakpoints": [
                        {
                            "id": 1,
                            "verified": true,
                            "line": 197
                        }
                    ]
                }
            }

D00000.131: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "job_status_transition.py",
                        "path": "/home/zaro/dev/gid-api/gid/job_status/job_status_transition.py"
                    },
                    "lines": [
                        439
                    ],
                    "breakpoints": [
                        {
                            "line": 439
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 10
            }

D00000.132: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 10})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "job_status_transition.py",
                        "path": "/home/zaro/dev/gid-api/gid/job_status/job_status_transition.py"
                    },
                    "lines": [
                        439
                    ],
                    "breakpoints": [
                        {
                            "line": 439
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000009
            }

D00000.133: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "json_encoder.py",
                        "path": "/home/zaro/dev/gid-api/gid/util/json_encoder.py"
                    },
                    "lines": [
                        31
                    ],
                    "breakpoints": [
                        {
                            "line": 31
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 11
            }

D00000.133: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 11})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "json_encoder.py",
                        "path": "/home/zaro/dev/gid-api/gid/util/json_encoder.py"
                    },
                    "lines": [
                        31
                    ],
                    "breakpoints": [
                        {
                            "line": 31
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000010
            }

D00000.134: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "orders.py",
                        "path": "/home/zaro/dev/gid-api/gid/importer/orders.py"
                    },
                    "lines": [
                        200
                    ],
                    "breakpoints": [
                        {
                            "line": 200
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 12
            }

D00000.134: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 12})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "orders.py",
                        "path": "/home/zaro/dev/gid-api/gid/importer/orders.py"
                    },
                    "lines": [
                        200
                    ],
                    "breakpoints": [
                        {
                            "line": 200
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000011
            }

D00000.135: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "orders.py",
                        "path": "/home/zaro/dev/gid-api/app/v2/brand/orders.py"
                    },
                    "lines": [
                        333
                    ],
                    "breakpoints": [
                        {
                            "line": 333
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 13
            }

D00000.136: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 13})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "orders.py",
                        "path": "/home/zaro/dev/gid-api/app/v2/brand/orders.py"
                    },
                    "lines": [
                        333
                    ],
                    "breakpoints": [
                        {
                            "line": 333
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000012
            }

D00000.137: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "phones.py",
                        "path": "/home/zaro/dev/gid-api/gid/util/phones.py"
                    },
                    "lines": [
                        12
                    ],
                    "breakpoints": [
                        {
                            "line": 12
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 14
            }

D00000.138: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 14})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "phones.py",
                        "path": "/home/zaro/dev/gid-api/gid/util/phones.py"
                    },
                    "lines": [
                        12
                    ],
                    "breakpoints": [
                        {
                            "line": 12
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000013
            }

D00000.138: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "rejected_jobs.py",
                        "path": "/home/zaro/dev/gid-api/gid/db/partner/rejected_jobs.py"
                    },
                    "lines": [
                        42
                    ],
                    "breakpoints": [
                        {
                            "line": 42
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 15
            }

D00000.139: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 15})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "rejected_jobs.py",
                        "path": "/home/zaro/dev/gid-api/gid/db/partner/rejected_jobs.py"
                    },
                    "lines": [
                        42
                    ],
                    "breakpoints": [
                        {
                            "line": 42
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000014
            }

D00000.139: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "test_order_import.py",
                        "path": "/home/zaro/dev/gid-api/tests/gid-lib/import/test_order_import.py"
                    },
                    "lines": [
                        141
                    ],
                    "breakpoints": [
                        {
                            "line": 141
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 16
            }

D00000.141: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 16})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "test_order_import.py",
                        "path": "/home/zaro/dev/gid-api/tests/gid-lib/import/test_order_import.py"
                    },
                    "lines": [
                        141
                    ],
                    "breakpoints": [
                        {
                            "line": 141
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000015
            }

D00000.141: IDE --> {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "test_v1.py",
                        "path": "/home/zaro/dev/gid-api/tests/gid-lib/api/test_v1.py"
                    },
                    "lines": [
                        62
                    ],
                    "breakpoints": [
                        {
                            "line": 62
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 17
            }

D00000.142: (while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 17})
            PYD <-- {
                "command": "setBreakpoints",
                "arguments": {
                    "source": {
                        "name": "test_v1.py",
                        "path": "/home/zaro/dev/gid-api/tests/gid-lib/api/test_v1.py"
                    },
                    "lines": [
                        62
                    ],
                    "breakpoints": [
                        {
                            "line": 62
                        }
                    ],
                    "sourceModified": false
                },
                "type": "request",
                "seq": 1000000016
            }


```

**Comment by karthiknadig** [comment]
@zaro Can you try this with `"pathMappings": []` in launch.json? see comment here https://github.com/microsoft/ptvsd/issues/1480#issuecomment-497392812 . I suspect this is a manifestation of that. 

However, we do need to address this case in the debugger.

**Comment by zaro** [comment]
@karthiknadig with this setting starting the debugger works as expected. Debugging single test doesn't but I guess I need to add the same setting somewhere else.

**Comment by karthiknadig** [comment]
@zaro 

> Debugging single test doesn't but I guess I need to add the same setting somewhere else.

That should be addressed when the extension makes the fix on their end.

**Comment by karthiknadig** [comment]
Closing this since the extension has addressed this on their end.

**Comment by michaeljquinn** [comment]
I am getting exactly the same issue
Windows 10 - 6.1.7601
VS Code 1.38.0
Electron 4.2.10
Chrome 69.0.3497.128
Node.js 10.11.0
V8 6.9.427.31-electron.0

No evidence of the python extension fixing this :-(

setting "justMyCode" false in launch config results in the following stack trace (same behaviour in unitTest as well)

removing the catching Raised and Uncaught Exceptions removes this error
and stepping into non user code inside a unit test (python unittest fwk) is not possible either


`
Exception has occurred: KeyError
'F:\\SCM\\git\\acuritycodescanner/src/test/nonUnit_TestParse.py'
  File "C:\Users\MichaelQui\AppData\Local\Programs\Python\Python37-32\Lib\pkgutil.py", line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
  File "C:\Users\MichaelQui\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 252, in run_path
    importer = get_importer(path_name)


Exception has occurred: ZipImportError
not a Zip file: 'F:\\SCM\\git\\acuritycodescanner\\src\\test\\nonUnit_TestParse.py'
  File "C:\Users\MichaelQui\AppData\Local\Programs\Python\Python37-32\Lib\pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "C:\Users\MichaelQui\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 252, in run_path
    importer = get_importer(path_name)


`

**Comment by karthiknadig** [comment]
@michaeljquinn This looks like a different issue. Can you create a separate bug? Also share your launch json.

**Comment by michaeljquinn** [comment]
I will share the launch.json , but I cant find a launch.json when running/debugging a unitTest ?

**Comment by karthiknadig** [comment]
@michaeljquinn  for tests a default launch.json config is used. You can add one yourself like this. You can also disable just my code wile debugging tests this way. Try with this.
```js
        {
            "name": "Debug Unit Test",
            "type": "python",
            "request": "test",
            "justMyCode": false,
        },
```

**Comment by ManPython** [comment]
I metting this case with new VSC ;/

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by fabioz** [comment]
@ManPython this is a really old issue on ptvsd, if you have an error, please create a new report on https://github.com/microsoft/debugpy/issues with your current KeyError traceback.
