### ISSUE TITLE
Internal error detected

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1508]
@garytyler commented on [Mon Jun 10 2019](https://github.com/microsoft/vscode-python/issues/5955)

```py
Traceback (most recent call last):
  File "/home/g/.vscode-server/extensions/ms-python.python-2019.5.18875/pythonFiles/ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "/home/g/.vscode-server/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "/home/g/.vscode-server/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/_vendored/force_pydevd.py", line 18, in <module>
    pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/g/.vscode-server/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 180, in <module>
    from _pydev_imps._pydev_saved_modules import thread
  File "/home/g/.vscode-server/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_saved_modules.py", line 20, in <module>
    import queue as _queue
  File "/mnt/c/Users/g/proj/eventvr-web/eventvr/queue.py", line 1, in <module>
    from django.contrib.sessions.models import Session
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/contrib/sessions/models.py", line 1, in <module>
    from django.contrib.sessions.base_session import (
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/contrib/sessions/base_session.py", line 26, in <module>
    class AbstractBaseSession(models.Model):
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 103, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/apps/registry.py", line 134, in check_apps_ready
    settings.INSTALLED_APPS
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/g/proj/eventvr-web/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'project'

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new
```

---

@garytyler commented on [Mon Jun 10 2019](https://github.com/microsoft/vscode-python/issues/5955#issuecomment-500433334)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

System Info

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (16 x 2998)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.91GB (113.03GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (16 x 3001)|
|Memory (System)|127.91GB (113.03GB free)|
|VM|0%|

**Comment by karthiknadig** [comment]
@fabioz Looking at the stack it seems like it is picking up the wrong `queue`?
```py
  File "/home/g/.vscode-server/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_saved_modules.py", line 20, in <module>
    import queue as _queue
  File "/mnt/c/Users/g/proj/eventvr-web/eventvr/queue.py", line 1, in <module>
    from django.contrib.sessions.models import Session
```

**Comment by fabioz** [comment]
@karthiknadig yeap, that seems to be it...

@garytyler, the problem is that the debugger relies on having some Python modules available and as your project is shadowing one of those (queue.py in /mnt/c/Users/g/proj/eventvr-web/eventvr/queue.py), so, the debugger can't start properly. 

The actual solution would be renaming your own `queue` module to something else as you're not expected to shadow the Python standard library modules.

**Comment by garytyler** [comment]
Ah, yes of course! Sorry to bother you with it. Thanks!

**Comment by int19h** [comment]
@fabioz, @karthiknadig 

We're seeing this occasionally, and it's very confusing when it happens. Python stdlib is huge, and if you name your own modules sensibly, the chances of a name clash are pretty high.

Can we do something to detect it and clearly report what's going on?

E.g. in ptvsd, have a module that just imports all the stdlib modules that the debugger will need at some point, and checks their paths?

We could write a Python script that walks our code and makes such a list automatically, just by looking at import statements.

**Comment by fabioz** [comment]
@int19h I agree this is a good idea, there's already a main place where those are loaded (`_pydev_imps._pydev_saved_modules`), and it should be the proper place to load with a try..except and check for conditions afterwards (if something is not loaded from there, it should be moved to that place).

I'll reopen this issue and use it to track that.

**Comment by fabioz** [comment]
@int19h @DonJayamanne @karthiknadig 

As a note, maybe this is something that the code analysis on the client should be also doing (usually the user is expected to create its own namespace and put things there -- so, having `my_project.queue` wouldn't be a problem, whereas having `queue` as the top level or `threading` would not be ok). 

Handling it in the client is a different issue, so, just raising the issue here to see whether a ticket should be opened for that in the client.

**Comment by int19h** [comment]
@Anapo14, take a look at the comment above.

I don't know how often this happens in general. But it depends on how many stdlib modules the project imports, directly or indirectly (including any stdlib or third-party package they import).

We hit it here more often than most, I bet, because ptvsd and pydevd need to import a lot of things, many of them solely because we need to specifically support that package or module (e.g. lots of stuff in stdlib itself, numpy, Qt...). And those in turn are large packages that import tons of stdlib modules as well. Hence why our stdlib dependency graph is pretty big, and the chances of user code inadvertently clashing with it are high.

Past examples:
https://github.com/microsoft/ptvsd/issues/773
https://github.com/microsoft/ptvsd/issues/1428

(Probably more, because they're usually reported as random issues. There may still be some undiagnosed ones in the backlog.)
