### ISSUE TITLE
ImportError: No module named importlib

### ISSUE THREAD

**Issue by byzhangkui** [microsoft/ptvsd#1522]
Traceback (most recent call last):
  File "c:\Users\koryz\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\koryz\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\koryz\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 2, in <module>
    from importlib import import_module
ImportError: No module named importlib

**Comment by karthiknadig** [comment]
@byzhangkui Can you provide the following details?
## Environment data

- PTVSD version: 
- OS and version: 
- Python version (& distribution if applicable, e.g. Anaconda): 
- Using VS Code or Visual Studio:


## Steps to reproduce:
1.

**Comment by karthiknadig** [comment]
Please provide requested details and reopen.
