### ISSUE TITLE
Issue with tracebacks

### ISSUE THREAD

**Issue by vladeziegler** [microsoft/ptvsd#1526]
Traceback (most recent call last):
  File "/Users/vladimirdeziegler/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/vladimirdeziegler/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/Users/vladimirdeziegler/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/vladimirdeziegler/Desktop/Exercise Files/Ch5/htmlparsing_start.py", line 21, in <module>
    main();
  File "/Users/vladimirdeziegler/Desktop/Exercise Files/Ch5/htmlparsing_start.py", line 15, in main
    f = open("samplehtml.html")
FileNotFoundError: [Errno 2] No such file or directory: 'samplehtml'
➜  Exercise Files cd "/Users/vladimirdeziegler/Desktop/Exercise Files" ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 /Users/vladimirdeziegler/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 55595 "/Users/vladimirdeziegler/Desktop/Exercise Files/Ch5/htmlparsing_start.py"

**Comment by karthiknadig** [comment]
@vladeziegler Can you make sure that `samplehtml.html` is in `/Users/vladimirdeziegler/Desktop/Exercise Files`?

**Comment by karthiknadig** [comment]
Please reopen with requested details.
