### ISSUE TITLE
Concurrent Test Execution Failure in pydevd

### ISSUE THREAD

**Issue by bryant-finney** [microsoft/ptvsd#1527]
## Environment data

- PTVSD version: 2019.5.18875
- OS and version: Ubuntu 18.04.2 LTS
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7 (distributed through pypi)
- Using VS Code or Visual Studio: code-insiders 1.36.0-insider

## Actual behavior

Launching a parallel test run through Django's built-in test runner fails after system checks are performed, producing the following error message and traceback:

```python
E00014.869: Exception escaped from start_client
            
Traceback (most recent call last):
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
    return f(*args, **kwargs)
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
    with self.started():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
    self.start()
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
    raise RuntimeError('already started')
RuntimeError: already started
```

This is followed by (what appears to be) additional exceptions triggered in the `atexit` functions of four separate processes:

```python
Traceback (most recent call last):
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
    py_db.notify_thread_not_alive(get_current_thread_id(t))
  File "/home/bryant/.vscode-insiders/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
    was_notified = thread.additional_info.pydev_notify_kill
AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
```

## Steps to reproduce:
1. Excerpts from Workspace Settings (*note*: the Django project root directory is nested inside of the VSCode workspace root in directory `pliny`) 

```json
{
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Django Unit Tests",
                "type": "python",
                "request": "launch",
                "module": "manage",
                "cwd": "${workspaceFolder}/pliny",
                "args": [
                    "test",
                    "--parallel",
                    "4",
                    "--keepdb",
                    "--verbosity",
                    "3"
                ],
                "console": "integratedTerminal",
                "django": true
            }
        ]
    }
}
```
2. Launch the above configuration through the Debug view

**Comment by karthiknadig** [comment]
@bryant-finney `--parallel` starts separate processes, can you add `"subProcess": true`. Since this is linux, you might want to set `spawn` mode. See here:
https://github.com/microsoft/ptvsd/blob/master/TROUBLESHOOTING.md#1-multiprocessing-on-linuxmac

If this does not help, please share a minimal repro.

**Comment by bryant-finney** [comment]
I added the `"subProcess": true` to the launch configuration, but no observable changes. I also stuck the multiprocessing call into `manage.py`, but spawning instead of forking introduces the issue of the Django apps no longer being loaded in the subprocesses.

Also of note: debugging individual test modules and packages works as expected, even with parallel processes enabled. It looks like this only happens when launching `manage.py test --parallel` without args.

I'll post an example repo first chance, though I don't have an eta for when (so it might be a couple of days) :smile_cat:
