### ISSUE TITLE
AttributeError: '_pydevd_bundle.pydevd_cython.PyDBAdditionalThreadInfo' object has no attribute 'pydev_original_step_cmd'

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1531]
## Environment data

- PTVSD version: master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VS

## Steps to reproduce:
1. Stepping causes this exception
```console
Traceback (most recent call last):
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 603, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 97, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1488, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1516, in _do_wait_suspend
    self.process_internal_commands()
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1224, in process_internal_commands
    int_cmd.do_it(self)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 502, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 622, in internal_step_in_thread
    info.pydev_original_step_cmd = cmd_id
AttributeError: '_pydevd_bundle.pydevd_cython.PyDBAdditionalThreadInfo' object has no attribute 'pydev_original_step_cmd'
Traceback (most recent call last):
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 485, in __call__
    ).trace_dispatch(frame, event, arg)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 603, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 97, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1488, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1516, in _do_wait_suspend
    self.process_internal_commands()
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 1224, in process_internal_commands
    int_cmd.do_it(self)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 502, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 622, in internal_step_in_thread
    info.pydev_original_step_cmd = cmd_id
AttributeError: '_pydevd_bundle.pydevd_cython.PyDBAdditionalThreadInfo' object has no attribute 'pydev_original_step_cmd'
```

**Comment by karthiknadig** [comment]
This seems to only occur on 3.6.

**Comment by fabioz** [comment]
@karthiknadig did you get this on a release or on your machine with a local version?

The only way I can think of for this to trigger is that somehow the binaries haven't been properly compiled.

**Comment by karthiknadig** [comment]
I ran into this with `master`, i just used PYTHONPATH and ran it from `./src`.

**Comment by fabioz** [comment]
It should be a local problem then... if you recompile your cython extensions (or erase them), things should work again (please reopen if that's not the case).
