### ISSUE TITLE
Error when trying to debug in VS Code with Python 3.7

### ISSUE THREAD

**Issue by atehortua1907** [microsoft/ptvsd#1569]
```shell
Traceback (most recent call last):
  File "c:\Users\Gohan\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\Gohan\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\Gohan\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\_vendored\force_pydevd.py", line 37, in <module>
    'pydevd',
  File "c:\Users\Gohan\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 123, in preimport
    import_module(name)
  File "C:\Users\Gohan\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ValueError: source code string cannot contain null bytes
```

**Comment by karthiknadig** [comment]
@atehortua1907  Can you provide some details about the environment that this is running in? Can you provide the results of `sys.getdefaultencoding()` and `sys.getfilesystemencoding()` for that environment.

**Comment by int19h** [comment]
This code is literally just calling `importlib.import_module("pydevd")`. I don't think it's an encoding issue - seems more like a corrupt installation to me, if it says there are null bytes in pydevd source...

@atehortua1907, can you please try uninstalling and then reinstalling the Python extension for VSCode?

**Comment by karthiknadig** [comment]
Please reopen if you have more info.
