### ISSUE TITLE
PTVSD fails to import

### ISSUE THREAD

**Issue by Robertina123** [microsoft/ptvsd#1591]
## Environment data

- PTVSD version: 2019.6.24221 (9 July 2019)
- OS and version: macOS Mojave, 10.14.5
- Python version: 3.7.3 64-bit
- Using VS Code or Visual Studio: VS Code 1.36.1

## Expected  behavior

When F5 is pressed, the debugger should initialise itself and run the code in the current file.

## Actual behavior

The debugger fails to launch at all across multiple trials, and the Terminal prints the following message:

```
cd "/Users/Me/Documents/Hello World" ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 /Users/Me/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 59471 "/Users/Me/Documents/Hello World/main.py" 
Traceback (most recent call last):
  File "/Users/Me/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "/Users/Me/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "/Users/Me/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
    'pydevd',
  File "/Users/Me/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/__init__.py", line 123, in preimport
    import_module(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/Me/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd_plugins/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
AttributeError: module 'pkg_resources' has no attribute 'declare_namespace'

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new
```

## Steps to reproduce:

1. Create a 'Hello World' folder with a file 'main.py' inside
2. Launch VS Code and open this folder
3. Insert trivial code into `main.py` such as `print('Hello, World!')`
4. Press `F5` (or `Fn` + `F5`) to start the debugger
5. Choose 'Python File' in debug configuration prompt
6. Debugging session times out and the terminal prints the above response

**Comment by int19h** [comment]
It looks like you have a very old version of `setuptools`, or else a broken Python install.

For starters, do this:
```
python3 -m pip install --upgrade setuptools
```

If it doesn't help, then try reinstalling Python. 

(this issue is similar to #1076 and #1258 in spirit)

**Comment by Robertina123** [comment]
@int19h Thank you very much, it worked again after updating the package. And yes, #1076 does look very similar to what I've encountered, thanks for pointing that out
