### ISSUE TITLE
Internal error when executing a python file.

### ISSUE THREAD

**Issue by zegevlier** [microsoft/ptvsd#1604]
Hello! 
I got an internal error and it said I should report it here, I tried to fix it myself but reinstalling Python, Visual Studio Code and removing all other python interpreters all didn't work.
I also tried reinstalling the python extension in Visual Studio Code, that didn't work either.

This is the error I got:

```
Traceback (most recent call last):
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\force_pydevd.py", line 37, in <module>
    'pydevd',
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 123, in preimport
    import_module(name)
  File "C:\Users\[My PC username]\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd_plugins\__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "C:\Users\[My PC username]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .

PS Z:\Python\flaskServerSocketIO> cd 'z:\Python\flaskServerSocketIO'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\[My PC username]\AppData\Local\Programs\Python\Python37-32\python.exe' 'c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '56287' 'z:\Python\flaskServerSocketIO\main.py'
Traceback (most recent call last):
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\force_pydevd.py", line 37, in <module>
    'pydevd',
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 123, in preimport
    import_module(name)
  File "C:\Users\[My PC username]\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\[My PC username]\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd_plugins\__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "C:\Users\[My PC username]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

I got this error when trying to execute any python file.

Thanks in advance for your help! I apologize if this is an obvious error, I couldn't find a solution anywhere online.

Edit: Just thought it would help:
I'm on an up to date installation of Windows 10 64 bit, running python 3.7 32-bit. If there is anything else that I need to add please tell me!

**Comment by int19h** [comment]
It's either a broken Python install, or an out-of-date pip. Try this in your Python install:
```
python -m pip install --upgrade pip setuptools
```

**Comment by zegevlier** [comment]
I'll try it!
This is the output:
```
Requirement already up-to-date: pip in c:\users\[My username]\appdata\local\programs\python\python37-32\lib\site-packages (19.1.1)
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 3.3
    Uninstalling setuptools-3.3:
      Successfully uninstalled setuptools-3.3
Successfully installed setuptools-41.0.1
```

That seems to have fixed it!
Thank you, really appreciate it!
