### ISSUE TITLE
Unexpected exception while debugging

### ISSUE THREAD

**Issue by ftrofin** [microsoft/ptvsd#1625]
## Environment data

- VS Code version: 1.36.1 (1.36.1)
- Extension version (available under the Extensions sidebar): 2019.6.24221
Version: 2019.6.24221
- OS and version: MacOS Mojave 10.14.5 (18F132)
- Python version (& distribution if applicable, e.g. Anaconda): System Python (2.7.10)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: Don't know
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): jediEnabled: YES.

## Expected behaviour

No failure

## Actual behaviour

Debugging exits abruptly due to unhandled exception.

## Steps to reproduce:

I debugged a Python script that I'm working on it. I've did this multiple times in the past and this didn't come up before, so I'm not sure how reproducible is. Hopefully the trace below can help:
```
E-0000.592: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
                return self.gen.next()
              File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
    py_db.notify_thread_not_alive(get_current_thread_id(t))
  File "/Users/ftrofin/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
    was_notified = thread.additional_info.pydev_notify_kill
AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
[INFO/MainProcess] process shutting down
Traceback (most recent call last):
Error in atexit._run_exitfuncs:Error in sys.exitfunc:
Error in sys.exitfunc:
Traceback (most recent call last):

Traceback (most recent call last):
  File <redacted>, line 869, in include
    exec code_object in globals()
  File "<string>", line 169, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '('/usr/bin/python', '<redacted>/somescript.py', '-v', 'rebuild', 'output.txt')' returned non-zero exit status 1
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
XXX
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by int19h** [comment]
Can you please tell more about the code that you're running?

In particular, are you using `os.fork` or `multiprocessing` in any way?

**Comment by ftrofin** [comment]
I don't think the problem is with multiprocessing, I think it has to do with spawning of the child python process:
`CalledProcessError:` Command '('/usr/bin/python', '<redacted>/somescript.py', '-v', 'rebuild', 'output.txt')' returned non-zero exit status 1`

**Comment by karthiknadig** [comment]
In your script are you importing `ptvsd` and calling `enable_attach`? Can you share your script or a minimal repro?

**Comment by int19h** [comment]
`CallProcessError` is simply telling you that some process (not itself debugger-related, judging by its command line) exited with an error. The real error is above that, and by the looks of it, it does kinda resemble what we've seen before with `fork` - hence why I'm curious.

It would be particularly helpful to see the code that starts `somescript.py`.

**Comment by karthiknadig** [comment]
This looks like a multiprocessing issue. See the troubleshooting.md on how to address these for Mac. You may want to enable `"subProcess": true` in your launch json to make use of the multiprocessing features in VSCode. Please reopen if you need additional help.
