### ISSUE TITLE
Django Tutorial

### ISSUE THREAD

**Issue by TK786** [microsoft/ptvsd#1639]
```
Microsoft Windows [Version 10.0.17134.885]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\tahir\hello_django>c:/Users/tahir/hello_django/env/Scripts/activate.bat

(env) C:\Users\tahir\hello_django>cd c:\Users\tahir\hello_django && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\tahir\hello_django\env\Scripts\python.exe c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py --default --nodebug --client --host localhost --port 51834 C:\Users\tahir\hello_django/manage.py runserver --noreload --nothreading "
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21
    import ptvsd
    ^
IndentationError: expected an indented block

(env) C:\Users\tahir\hello_django>cd c:\Users\tahir\hello_django && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\tahir\hello_django\env\Scripts\python.exe c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py --default --nodebug --client --host localhost --port 51881 C:\Users\tahir\hello_django/manage.py runserver --noreload --nothreading "
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 20
    try:
      ^
SyntaxError: invalid syntax

(env) C:\Users\tahir\hello_django>cd c:\Users\tahir\hello_django && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\tahir\hello_django\env\Scripts\python.exe c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 51888 C:\Users\tahir\hello_django/manage.py runserver --noreload --nothreading "
Traceback (most recent call last):
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 2, in <module>
    from importlib import import_module
  File "C:\Users\tahir\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127
    return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^
SyntaxError: 'return' outside function

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .
```

```
(env) C:\Users\tahir\hello_django>cd c:\Users\tahir\hello_django && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\tahir\hello_django\env\Scripts\python.exe c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py --default --nodebug --client --host localhost --port 51896 C:\Users\tahir\hello_django/manage.py runserver --noreload --nothreading "
Traceback (most recent call last):
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 2, in <module>
    from importlib import import_module
  File "C:\Users\tahir\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127
    return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^
SyntaxError: 'return' outside function

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .
```

```
(env) C:\Users\tahir\hello_django>c:/Users/tahir/hello_django/env/Scripts/activate.bat(env) C:\Users\tahir\hello_django>cd c:\Users\tahir\hello_django && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\tahir\hello_django\env\Scripts\python.exe c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py --default --nodebug --client --host localhost --port 51924 C:\Users\tahir\hello_django/manage.py runserver --noreload --nothreading "
Traceback (most recent call last):
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\__init__.py", line 2, in <module>
    from importlib import import_module
  File "C:\Users\tahir\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127
    return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^
SyntaxError: 'return' outside function

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .
```

```
(env) C:\Users\tahir\hello_django>cd c:\Users\tahir\hello_django && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\tahir\hello_django\env\Scripts\python.exe c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 51927 C:\Users\tahir\hello_django/manage.py runserver --noreload --nothreading "
Traceback (most recent call last):
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\tahir\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\_vendored\force_pydevd.py", line 20, in <module>
    pydevd_constants.CYTHON_SUPPORTED = False
AttributeError: 'NoneType' object has no attribute 'CYTHON_SUPPORTED'

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new
```

**Comment by karthiknadig** [comment]
@TK786 can you provide some more details. Is this a consistent repro? if so can you provide a link to the tutorial that you were using. Any steps that you took while setting up your environment etc.

**Comment by TK786** [comment]
https://code.visualstudio.com/docs/python/tutorial-django I was using this tutorial when the problems started. It is a consistent repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by int19h** [comment]
It looks like a corrupt Python installation.

Can you check if a simple console app works for you? Also, does the problem only occurs with the debugger, or do you also see it when running without the debugger (from command line) using the same Python version?

**Comment by TK786** [comment]
Hello World works for me when I run it in visual studio code

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fabioz** [comment]
Closing due to inactivity in the bug. Please reopen if you feel this still needs to be addressed.
