### ISSUE TITLE
python3 environment error

### ISSUE THREAD

**Issue by nan10921p** [microsoft/ptvsd#1646]
Traceback (most recent call last):
  File "/root/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "/root/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "/root/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/_vendored/force_pydevd.py", line 42, in <module>
    'pydevd',
  File "/root/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/_vendored/__init__.py", line 123, in preimport
    import_module(name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd_plugins/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

**Comment by karthiknadig** [comment]
@nan10921p Looks like you might have a broken python install.

**Comment by int19h** [comment]
Try:
```
python3 -m pip install --upgrade setuptools
```

**Comment by nan10921p** [comment]
@int19h 
I try your command 
   python3 -m pip install --upgrade setuptools
Then problem solved perfectly.
Thank you.

**Comment by int19h** [comment]
You're welcome!
