### ISSUE TITLE
import daemon error

### ISSUE THREAD

**Issue by LucasBois1** [microsoft/ptvsd#1683]
# VS CODE Terminal error
```
PS C:\Users\Lucas\Desktop\Python> & 'F:\Python27\python.exe' 'c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '52361' 'c:\Users\Lucas\Desktop\Python\RPS.py'
Traceback (most recent call last):
  File "c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\lib\python\ptvsd\__init__.py", line 15, in <module>
    from ptvsd.attach_server import (  # noqa
  File "c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\lib\python\ptvsd\attach_server.py", line 5, in <module>
    from ptvsd._remote import (
  File "c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\lib\python\ptvsd\_remote.py", line 14, in <module>
    from ptvsd.pydevd_hooks import install
  File "c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\lib\python\ptvsd\pydevd_hooks.py", line 15, in <module>
    from ptvsd.daemon import Daemon, DaemonStoppedError, DaemonClosedError
  File "c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\lib\python\ptvsd\daemon.py", line 212
SyntaxError: Non-ASCII character '\xe6' in file c:\Users\Lucas\.vscode\extensions\geecode.geecode-python-2019.5.10\pythonFiles\lib\python\ptvsd\daemon.py on line 212, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .
```

**Comment by fabioz** [comment]
@LucasBois1 that version of the extension seems outdated and this should be fixed in the latest release... Please ask the maintainers of your extension (geecode) to update it.
