### ISSUE TITLE
Value error during state transitions

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1692]
```
Traceback (most recent call last):
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\messaging.py", line 733, in _handle
                 result = handler(self)
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\adapter\messages.py", line 309, in _disconnect_or_terminate_request
                 state.change("shutting_down")
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\adapter\state.py", line 58, in change
                 State().state = new_state
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\singleton.py", line 163, in __setattr__
                 return object.__setattr__(self, name, value)
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\singleton.py", line 185, in lock_and_call
                 return func(self, *args, **kwargs)
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\adapter\state.py", line 45, in state
                 if STATES.index(state) >= STATES.index(new_state):
             ValueError: tuple.index(x): x not in tuple
```

**Comment by int19h** [comment]
It sounds like the name of the state was mistyped somewhere.

**Comment by karthiknadig** [comment]
full error:
```
E+00010.360: Fatal error in channel server while handling disconnect:

             Traceback (most recent call last):
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\messaging.py", line 1497, in _handle_disconnect
                 handler()
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\adapter\messages.py", line 507, in disconnect
                 state.change("shutting_down")
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\adapter\state.py", line 58, in change
                 State().state = new_state
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\singleton.py", line 163, in __setattr__
                 return object.__setattr__(self, name, value)
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\singleton.py", line 185, in lock_and_call
                 return func(self, *args, **kwargs)
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\adapter\state.py", line 45, in state
                 if STATES.index(state) >= STATES.index(new_state):
             ValueError: tuple.index(x): x not in tuple

             During handling of the above exception, another exception occurred:

             Traceback (most recent call last):
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\messaging.py", line 1467, in _run_handlers
                 handler()
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\messaging.py", line 1502, in _handle_disconnect
                 self.channel,
             AttributeError: 'JsonMessageChannel' object has no attribute 'channel'

             Stack where logged:
               File "C:\Python37\lib\threading.py", line 885, in _bootstrap
                 self._bootstrap_inner()
               File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
                 self.run()
               File "C:\Python37\lib\threading.py", line 865, in run
                 self._target(*self._args, **self._kwargs)
               File "C:\GIT\ptvsd\src\ptvsd\adapter/../..\ptvsd\common\messaging.py", line 1470, in _run_handlers
                 "Fatal error in channel {0} while handling {1}:", self, what
```
