### ISSUE TITLE
Refactor branch: Restore attach to pid tests

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1737]

**Comment by karthiknadig** [comment]
Blocked currently due to `The parameter is incorrect.` error when injecting code:
```
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\process.py", line 710, in is_wow64
                 wow64 = self.__wow64
             AttributeError: 'Process' object has no attribute '_Process__wow64'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
               File "C:\GIT\ptvsd\src\ptvsd/..\ptvsd\server\main.py", line 319, in attach_to_pid
                 setup['pid'], python_code, connect_debugger_tracing=True, show_debug_info=show_debug_info_on_target_process)
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\add_code_to_python_process.py", line 284, in run_python_code_windows
                 bits = process.get_bits()
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\process.py", line 767, in get_bits
                 if self.is_wow64():
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\process.py", line 719, in is_wow64
                 hProcess = self.get_handle(dwAccess)
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\process.py", line 257, in get_handle
                 self.open_handle(dwDesiredAccess)
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\process.py", line 206, in open_handle
                 hProcess = win32.OpenProcess(dwDesiredAccess, win32.FALSE, self.dwProcessId)
               File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\kernel32.py", line 3960, in OpenProcess
                 raise ctypes.WinError()
             OSError: [WinError 87] The parameter is incorrect.
             
             Stack where logged:
               File "C:\GIT\ptvsd\src\ptvsd\__main__.py", line 45, in <module>
                 main.main()
               File "C:\GIT\ptvsd\src\ptvsd/..\ptvsd\server\main.py", line 347, in main
                 run()
               File "C:\GIT\ptvsd\src\ptvsd/..\ptvsd\server\main.py", line 321, in attach_to_pid
                 log.exception()
```
