### ISSUE TITLE
python debug报错

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1777]
@Troot8550 commented on [Tue Sep 17 2019](https://github.com/microsoft/vscode-python/issues/7429)

f5调试 直接报错

Traceback (most recent call last):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 440, in __call__
    file_type = py_db.get_file_type(frame, abs_path_real_path_and_base)  # we don't want to debug threading or anything related to pydevd
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 705, in get_file_type
    if self.dont_trace_external_files(abs_real_path_and_basename[0]):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 758, in custom_dont_trace_external_files
    return abs_path.startswith(start_patterns) or abs_path.endswith(end_patterns)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 10: ordinal not in range(128)

**Comment by karthiknadig** [comment]
Please reopen the bug with [additional details](https://github.com/microsoft/ptvsd/issues/new?template=bug_report.md). Also include output of `sys.getdefaultencoding()` and `sys.getfilesystemencoding()` for your environment.

**Comment by kizylirio** [comment]
This error occurs when your project is located in a long path. 
Try put your project in your user directory
