### ISSUE TITLE
add_dap_messages_listener fails with PyDB.reader is still not setup

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1783]
```
Traceback (most recent call last):
  File "test_import.py", line 4, in <module>
    ptvsd.enable_attach(("127.0.0.1", 0))
  File "C:\GIT\ptvsd\src\ptvsd\__init__.py", line 78, in enable_attach
    return api.enable_attach(address, log_dir)
  File "C:\GIT\ptvsd\src\ptvsd\server\api.py", line 97, in debug
    return func(start_patterns, end_patterns)
  File "C:\GIT\ptvsd\src\ptvsd\server\api.py", line 112, in enable_attach
    _DAPMessagesListener.initialize()
  File "C:\GIT\ptvsd\src\ptvsd\server\api.py", line 50, in initialize
    pydevd.add_dap_messages_listener(_dap_listener)
  File "C:\GIT\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 2111, in add_dap_messages_listener
    raise AssertionError('PyDB.reader is still not setup.')
AssertionError: PyDB.reader is still not setup.
```

**Comment by karthiknadig** [comment]
@fabioz Is there a way to ensure everything is ready before setting the listener?

**Comment by karthiknadig** [comment]
The problem is we need to set this listener up before we start the OOP adapter in the enable_attach case. At that point the reader is not set up because it is waiting for a connection. Alternate option is to append the listeners to a list on pydb. And have both the writer and reader threads access it.
