### ISSUE TITLE
Socket timeout: timed out

### ISSUE THREAD

**Issue by ArchanaGurav** [microsoft/ptvsd#1790]
I am facing the following issue. After waiting for 30sec while in debug session on. its time out error is thrown. Not sure  why is this happening.

Exception in thread ptvsd.Server:
Traceback (most recent call last):
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\ipcjson.py", line 269, in process_one_message
    msg = self.__message.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Autodesk\webdeploy\staging\a9aea700c5a49af148ed9b39c4342a305dd495f6\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Autodesk\webdeploy\staging\a9aea700c5a49af148ed9b39c4342a305dd495f6\Python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\wrapper.py", line 536, in process_messages
    raise exc
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\wrapper.py", line 521, in process_messages
    self.process_messages()
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\ipcjson.py", line 258, in process_messages
    self.process_one_message()
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\ipcjson.py", line 272, in process_one_message
    self._wait_for_message()
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\ipcjson.py", line 154, in _wait_for_message
    line = self._buffered_read_line_as_ascii()
  File "C:\Users\gurava\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\ipcjson.py", line 113, in _buffered_read_line_as_ascii
    temp = self.__socket.recv(1024)
socket.timeout: timed out

**Comment by karthiknadig** [comment]
@ArchanaGurav Can you set these and generate debugger logs? 
You can enable debugger logging using the following environment variables:
```
PTVSD_LOG_DIR=C:\logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=C:\logs\pydevd.log
```
These can be set using "env" field in the launch json. Ensure that the `C:\logs` directory exists before running. Note that this will generate several log files. Please share the most recent one.

Also, please share the launch config you are using.

**Comment by fabioz** [comment]
Closing due to inactivity in the issue.
