### ISSUE TITLE
test_attach fails on windows

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#181]
Run with `py -3.6 -m tests -v -f`
```
======================================================================
ERROR: test_attach (tests.highlevel.test_lifecycle.LifecycleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\highlevel\test_lifecycle.py", line 49, in test_attach
    req_disconnect = self.send_request('disconnect')
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\protocol.py", line 93, in __exit__
    self.close()
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\protocol.py", line 110, in close
    self.fake.close()
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\protocol.py", line 180, in close
    self._close()
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\vsc\_fake.py", line 136, in _close
    self._adapter.close()
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\protocol.py", line 110, in close
    self.fake.close()
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\protocol.py", line 180, in close
    self._close()
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\protocol.py", line 267, in _close
    socket.close(self._sock)
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\socket.py", line 59, in close
    sock.shutdown(socket.SHUT_RDWR)
  File "C:\Projects\GitHub\microsoft\ptvsd\tests\helpers\socket.py", line 89, in shutdown
    self.server.shutdown(*args, **kwargs)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
```

**Comment by karthiknadig** [comment]
This is fixed. There is another issue with attach that is tracked by this bug https://github.com/Microsoft/ptvsd/issues/289
