### ISSUE TITLE
test_flask_breakpoint_multiproc fails with run=attach_by_socket

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1886]
Python 3.7, Win32.

Logs are unclear - needs investigation.

**Comment by int19h** [comment]
When this happens, the session logs some error output coming from inside pydevd in the subprocess (that Flask spawns to perform auto-reload):
```
I+06.356: Debuggee-80 stderr:
          'Traceback (most recent call last):'

I+06.356: Debuggee-80 stderr:
          '\r\n'

I+06.357: Debuggee-80 stderr:
          '  File "d:\\a\\1\\s\\.tox\\py27\\lib\\site-packages\\ptvsd\\_vendored\\pydevd\\pydevd.py", line 3108, in <module>'

I+06.357: Debuggee-80 stderr:
          '\r\n'

I+06.361: Debuggee-80 stderr:
          '    '

I+06.361: Debuggee-80 stderr:
          'main()'

I+06.361: Debuggee-80 stderr:
          '\r\n'

I+06.361: Debuggee-80 stderr:
          '  File "d:\\a\\1\\s\\.tox\\py27\\lib\\site-packages\\ptvsd\\_vendored\\pydevd\\pydevd.py", line 3101, in main\r\n'

I+06.366: Debuggee-80 stderr:
          '    '

I+06.366: Debuggee-80 stderr:
          "globals = debugger.run(setup['file'], None, None, is_module)"

I+06.366: Debuggee-80 stderr:
          '\r\n'

I+06.366: Debuggee-80 stderr:
          '  File "d:\\a\\1\\s\\.tox\\py27\\lib\\site-packages\\ptvsd\\_vendored\\pydevd\\pydevd.py", line 2174, in run\r\n'

I+06.372: Debuggee-80 stderr:
          '    '

I+06.373: Debuggee-80 stderr:
          'return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)'

I+06.373: Debuggee-80 stderr:
          '\r\n'

I+06.373: Debuggee-80 stderr:
          '  File "d:\\a\\1\\s\\.tox\\py27\\lib\\site-packages\\ptvsd\\_vendored\\pydevd\\pydevd.py", line 2181, in _exec\r\n'

I+06.376: Debuggee-80 stderr:
          '    '

I+06.376: Debuggee-80 stderr:
          'pydev_imports.execfile(file, globals, locals)  # execute the script\r\n'

I+06.376: Debuggee-80 stderr:
          'IOErro'

I+06.376: Debuggee-80 stderr:
          'r'

I+06.376: Debuggee-80 stderr:
          ': '

I+06.376: Debuggee-80 stderr:
          "[Errno 2] No such file or directory: 'D:\\\\a\\\\1\\\\s\\\\tests\\\\test_data\\\\flask1\\\\-m'"

I+06.376: Debuggee-80 stderr:
          '\r\n'
```
And here's the corresponding part of pydevd log for the parent process, where it patches the arguments before the subprocess gets spawned:
```
File not traced (not in project - force_check_project_scope): c:\hostedtoolcache\windows\python\2.7.16\x64\lib\subprocess.py
File traced: <werkzeug routing>
Patching args: [u'd:\\a\\1\\s\\.tox\\py27\\scripts\\python.exe', u'D:\\a\\1\\s\\tests\\test_data\\flask1\\-m', u'flask', u'run', u'--no-debugger', u'--with-threads', u'--reload', u'--port', u'7006']
File not traced (not in project - force_check_project_scope): d:\a\1\s\.tox\py27\lib\site-packages\jinja2\ext.py
sending cmd -->      CMD_THREAD_KILL {"type": "event", "event": "thread", "pydevd_cmd_id": 104, "seq": 32, "body": {"threadId": 2, "reason": "exited"}}

New args: d:\a\1\s\.tox\py27\scripts\python.exe d:\a\1\s\.tox\py27\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py --port 4511 --client 127.0.0.1 --multiprocess --json-dap-http --file D:\a\1\s\tests\test_data\flask1\-m flask run --no-debugger --with-threads --reload --port 7006
File not traced (not in project - force_check_project_scope): c:\hostedtoolcache\windows\python\2.7.16\x64\lib\traceback.py
sending cmd -->      CMD_THREAD_KILL {"type": "event", "event": "thread", "pydevd_cmd_id": 104, "seq": 34, "body": {"threadId": 1, "reason": "exited"}}
```
Note that the mangled `-m` argument was already there _before_ pydevd did anything - it came from Flask. So, it looks like something that ptvsd did to `sys.argv` caused Flask to misinterpret it like that.
