### ISSUE TITLE
Cannot debug python code using 'current file' configuration

### ISSUE THREAD

**Issue by Yossarian0916** [microsoft/ptvsd#1895]
Here is my configuration for python file:
```
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
```

When I launch debugger, I got following error:
```
Traceback (most recent call last):
  File "/home/yossarian42/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "/home/yossarian42/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/__init__.py", line 15, in <module>
    from ptvsd.attach_server import (  # noqa
  File "/home/yossarian42/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/attach_server.py", line 9, in <module>
    from ptvsd._remote import (
  File "/home/yossarian42/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/_remote.py", line 14, in <module>
    from ptvsd.pydevd_hooks import install
  File "/home/yossarian42/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 14, in <module>
    from ptvsd import multiproc
  File "/home/yossarian42/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/multiproc.py", line 40, in <module>
    subprocess_queue = queue.Queue()
TypeError: __init__() missing 1 required positional argument: 'length'
```

**Comment by int19h** [comment]
Do you have a file in your project named queue.py, by chance?

**Comment by Yossarian0916** [comment]
Oh!!! Thank you so much.

**Comment by karthiknadig** [comment]
I am assuming this is addressed.
