### ISSUE TITLE
Using Ctrl+C causes launcher to print traceback

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1896]
## Environment data

- PTVSD version: master
- OS and version: linux
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

```console
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kanadig/GIT/ptvsd/src/ptvsd/launcher/__main__.py", line 74, in <module>
    main()
  File "/home/kanadig/GIT/ptvsd/src/ptvsd/launcher/__main__.py", line 37, in main
    adapter.channel.wait()
  File "/home/kanadig/GIT/ptvsd/src/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1231, in wait
    parser_thread.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

## Expected  behavior

This is normal way to shutdown the servers. Show not print exception in launcher.

**Comment by int19h** [comment]
To be more specific, we should be catching and suppressing `KeyboardInterrupt` at top level in the launcher (what's observed is the default behavior for Python). The debuggee will get that exception as well, and can do whatever it wants about it. But even in the default case, it means that both launcher and debuggee will print the traceback, and we only want the debuggee to do this.

**Comment by int19h** [comment]
For attach scenarios, adapter has the same issue, because it is spawned by the debuggee, and thus shares the console/tty.
