### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by albertcruzeyork** [microsoft/ptvsd#1897]
```
Traceback (most recent call last):
  File "c:\Users\cy\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\cy\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\cy\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\force_pydevd.py", line 18, in <module>
    pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
  File "C:\Users\cy\Anaconda3\envs\tensor\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\cy\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_constants.py", line 5, in <module>
    import platform
  File "C:\Users\cy\Anaconda3\envs\tensor\lib\platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "C:\Users\cy\Anaconda3\envs\tensor\lib\subprocess.py", line 614
    pass_fds=(), *, encoding=None, errors=None):
           ^
SyntaxError: invalid syntax
```

**Comment by int19h** [comment]
It looks like the Conda virtual environment that you're trying to run this code in is broken. Another possibility is that it's an environment created from Python 3, but it somehow ended up running with a Python 2 interpreter.

Can you provide more information about how the code was launched? launch.json, details about the virtual environment etc.

**Comment by albertcruzeyork** [comment]
Here is the launch.json
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: 当前文件",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}

**Comment by albertcruzeyork** [comment]
here is the launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: 当前文件",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}

**Comment by albertcruzeyork** [comment]
I copy the subprocess.py in other virtual environment to cover the current one and it doesn't report error anymore.

**Comment by int19h** [comment]
That would, indeed, indicate a broken environment. It's probably best to just re-create it from scratch using your requirements.txt or equivalent, since there may be other standard modules there that are affected in a similar way.
