### ISSUE TITLE
timeout waiting for debugger connection

### ISSUE THREAD

**Issue by magur2017** [microsoft/ptvsd#1906]
Microsoft Windows [Version 10.0.17134.1006]
(c) 2018 Microsoft Corporation. All rights reserved.

c:\Users\dino_\Desktop\python_lessons>C:\Users\dino_\AppData\Local\Programs\Python\Python37-32\python.exe c:\Users\dino_\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 51290 c:\Users\dino_\Desktop\python_lessons\itertools.py
Traceback (most recent call last):
  File "c:\Users\dino_\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\dino_\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\dino_\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\force_pydevd.py", line 18, in <module>
    pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
  File "C:\Users\dino_\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\dino_\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_constants.py", line 205, in <module>
    from _pydev_imps._pydev_saved_modules import thread
  File "c:\Users\dino_\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_saved_modules.py", line 21, in <module>
    import xmlrpc.client as xmlrpclib
  File "C:\Users\dino_\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 135, in <module>
    from decimal import Decimal
  File "C:\Users\dino_\AppData\Local\Programs\Python\Python37-32\lib\decimal.py", line 3, in <module>
    from _decimal import *
AttributeError: module 'numbers' has no attribute 'Number'

**Comment by int19h** [comment]
Does your project have a script named "numbers.py" in it somewhere, by chance? If so, it ends up shadowing the Python standard module `numbers`, which is an indirect dependency for the debugger.

**Comment by int19h** [comment]
Please reopen if the reason wasn't as described above. If it was, then this behavior is by design - having modules that conflict with Python stdlib can break things due to the way imports work in Python.
