### ISSUE TITLE
Improve error reporting when ptvsd port is already in use

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1917]
With the new adapter, in an attach scenario where the adapter is spawned by the server, if it's told to listen on a port that's already in use, the error is very hard to parse. The adapter itself will crash with "OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted", and log it to stderr - which is fine.

But then the debug server will try to read and parse the JSON packet from the adapter with host/port information, which fails because the adapter doesn't send one. Thus, the last error that the user sees is `JSONDecodeError` that has nothing about it indicating its cause:
```
          b'Traceback (most recent call last):\r\n'
          b'  File "C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-unknown\\pytest-0\\popen-gw3\\test_stack_format_program_atta0\\code_to_debug.py", line 1, in <module>\r\n'
          b'    import debug_me  # noqa\r\n'
          b'  File "D:\\a\\1\\s\\tests\\DEBUGGEE_PYTHONPATH\\debug_me\\__init__.py", line 44, in <module>\r\n'
          b'    eval(_code, {})\r\n'
          b'  File "<PTVSD_TEST_DEBUG_ME>", line 3, in <module>\r\n'
          b'  File "d:\\a\\1\\s\\.tox\\py36\\lib\\site-packages\\ptvsd\\__init__.py", line 81, in enable_attach\r\n'
          b'    return api.enable_attach(address, log_dir)\r\n'
          b'  File "d:\\a\\1\\s\\.tox\\py36\\lib\\site-packages\\ptvsd\\server\\api.py", line 73, in debug\r\n'
          b'    raise log.exception("{0}() failed:", func.__name__)\r\n'
          b'  File "d:\\a\\1\\s\\.tox\\py36\\lib\\site-packages\\ptvsd\\server\\api.py", line 71, in debug\r\n'
          b'    return func(start_patterns, end_patterns)\r\n'
          b'  File "d:\\a\\1\\s\\.tox\\py36\\lib\\site-packages\\ptvsd\\server\\api.py", line 110, in enable_attach\r\n'
          b'    connection_details = json.JSONDecoder().decode(line)\r\n'
          b'  File "C:\\hostedtoolcache\\windows\\Python\\3.6.8\\x64\\Lib\\json\\decoder.py", line 339, in decode\r\n'
          b'    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n'
          b'  File "C:\\hostedtoolcache\\windows\\Python\\3.6.8\\x64\\Lib\\json\\decoder.py", line 357, in raw_decode\r\n'
          b'    raise JSONDecodeError("Expecting value", s, err.value) from None\r\n'
          b'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\n'
```

(The same can happen with any other error can happen while setting up a listener socket in the adapter - i.e. anything that `socket()`, `bind()`, or `listen()` can throw.)

At the very least, the server code should be hardened to treat an empty string read from the adapter as a valid possibility, and to raise an error out of `enable_attach` with a clear message indicating that the adapter couldn't be spawned, and directing to the actual error logged by the adapter.

Ideally, we should catch those errors on the adapter side, and communicate them via JSON to the server before exiting, so that the error message can be incorporated into the exception that the server raises.

**Comment by int19h** [comment]
The adapter catches exception and passes the error text back now, and the server propagates it to the API user as `RuntimeError`.
