### ISSUE TITLE
Debugging with new_ptvsd is crashing because of TypeError: Struct()

### ISSUE THREAD

**Issue by duduz** [microsoft/ptvsd#1941]
## Environment data

- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar): 2019.11.49689
- OS and version: RH7.6
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.5

## Expected behaviour

Debugger works fine

## Actual behaviour

It crashes..
stack:
```
[root@rh01 ~]# /usr/bin/python /root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher /root/helloworld/helloworld.py 
E+00000.020: /handling microsoft/vscode-python#1 request "launch" from Adapter-1/
             Handler 'launch_request' (file u'/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/adapter.py', line 35)
             couldn't handle microsoft/vscode-python#1 request "launch" from Adapter-1:
             
             Traceback (most recent call last):
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 763, in _handle
                 result = handler(self)
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/adapter.py", line 147, in launch_request
                 debuggee.spawn(process_name, cmdline, cwd, env, redirect_output)
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/debuggee.py", line 76, in spawn
                 "pointerSize": struct.calcsize("P") * 8,
             TypeError: Struct() argument 1 must be string, not unicode
             
             Stack where logged:
               File "/usr/lib64/python2.7/threading.py", line 785, in __bootstrap
                 self.__bootstrap_inner()
               File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
                 self.run()
               File "/usr/lib64/python2.7/threading.py", line 765, in run
                 self.__target(*self.__args, **self.__kwargs)
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1520, in _run_handlers
                 handler()
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 809, in _handle
                 self.describe(),
```

## Steps to reproduce:

1. Just F5 to debug.
2. Getting this error
3. also getting an error to check launch,json - Launcher[1] disconnected unexpectedly
4. launcher is somehow still listening in the background

ps x | grep ptvsd
```
 9815 pts/3    S      0:00 /usr/bin/python /root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd --client --host 127.0.0.1 --port 41995 /root/helloworld/helloworld.py
 9869 pts/3    S      0:00 /usr/bin/python /root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd --client --host 127.0.0.1 --port 39855 /root/helloworld/helloworld.py

```
5. **it is verified to be working with the previous release of python extension** which does not make use of ptvsd_new

launch.json contents:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by int19h** [comment]
This is a limitation of an older Python version - for Python 2, `struct` [added](http://python-future.org/stdlib_incompatibilities.html#struct-pack) support for Unicode strings to define the format in Python 2.7.7, to be consistent with Python 3. 

Is it possible for you to upgrade your Python version? The most recent release for Python 2.x is 2.7.17.

**Comment by duduz** [comment]
I think not, since not all all of the enterprise distributions provides newer versions of python
since vscode-python extension contains the old ptvsd in the new version, it would be ideal if we can choose to use it through a setting configuration.

Thanks!

**Comment by fabioz** [comment]
@duduz if you just change locally to use bytes in calcsize, do you have any other issues?

i.e.: use `struct.calcsize(b"P")` in `/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/debuggee.py", line 76, in spawn`

**Comment by duduz** [comment]
@fabioz I don't mind doing so. i think we're good. thank you.
i'll give it a try and close the issue later on.

**Comment by duduz** [comment]
@fabioz it worked, thank you.
any advantage to use `struct.calcsize("P")` instead of `struct.calcsize(b"P")` to support older versions of python?

**Comment by int19h** [comment]
@duduz The problem is that `b"P"` won't work on Python 3. We have a helper function that'll do the right thing on either version, in `ptvsd.common.compat`.

**Comment by duduz** [comment]
@int19h i understand, i've seen `ptvsd.common.compat` and it doesn't seems to cover this use case, it seems hardcoded in `ptvsd/launcher/debuggee.py`.

**Comment by int19h** [comment]
There's a function there, `force_str`, that will produce the right type of object depending on the Python version.

**Comment by duduz** [comment]
@int19h the function is there, but still it won't be working with python 2.7.5 without editing `debuggee.py`
editing the file fixed it for me, if there's no point of creating fix for it, i don't mind closing the issue.

**Comment by fabioz** [comment]
I just provided a pull request.

I think the major issue is that in the future `ptvsd` may still break with older versions of Python because there are no plans to check older versions of Python 2.7 in the ci (but given that the fix seems pretty simple in this case, I think that we should include it).

**Comment by duduz** [comment]
@fabioz thank you, i just tested it and it works well. as far as i am concerned we can close this issue.

**Comment by fabioz** [comment]
@duduz when we integrate the pull request it should be automatically closed ;)
