### ISSUE TITLE
Debugging Python in VS Code crashes when creating iterator on Dataloader object

### ISSUE THREAD

**Issue by drewkerwin** [microsoft/ptvsd#1948]
## Environment data

**Note: I do not believe the circumstances of this error are similar to other posts in this repo.**

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

Python 3.7.3
conda 4.7.12
ptvsd==4.3.2

## Actual behavior

When creating an iterator on a Dataloader object, the debugger crashes with the following:

`  the_dataset = torchvision.datasets.ImageFolder(root=rootdir,
                                            transform=data_transform)
    dataset_loader = torch.utils.data.DataLoader(the_dataset,
                                                batch_size=64, shuffle=False,
                                                num_workers=4)
    dataiter = iter(dataset_loader)    #crash occurs here with the below output
`

E00014.845: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/Users/dkerwin/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
                return next(self.gen)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line E00014.846: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/Users/dkerwin/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
                return next(self.gen)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

110, in started
                self.start()
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):
Traceback (most recent call last):

Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

E00014.852: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/Users/dkerwin/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
                return next(self.gen)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

E00014.857: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/Users/dkerwin/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
                return next(self.gen)
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/dkerwin/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in <module>

Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

Terminated: 15

## Expected  behavior

Create an iterator

## Steps to reproduce:
1. Create a Dataloader object with Datasets object, then try to create an iterator - all way in debug mode in VSCode. The error described above does not occur when running scripts in python from command line - i.e. no debugger attached

Also, I tried running your pytest test scripts, but there are too many failures associated with that to include output here.

**Comment by int19h** [comment]
While the circumstances are different, this particular code path is specific to ptvsd 4.x, and is gone entirely in ptvsd 5. 

Judging by the paths, this is a recent vscode-python build that has both versions of ptvsd in it. @karthiknadig, is there any way to force it to use the new one, to confirm that it is no longer an issue there?

**Comment by int19h** [comment]
Please use the instructions in https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267 to try this on the new debugger, and re-open if it still reproduces.
