### ISSUE TITLE
Allow non-string values in "env"

### ISSUE THREAD

**Issue by meandmymind** [microsoft/ptvsd#1950]
## Environment data
- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Ubuntu 19.10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.5 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: None
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): None

## Expected behaviour
Integer environment values are parsed OK as they are valid json value.
## Actual behaviour
Launch failes with message `Invalid message: 'env' Unknown conversion specifier j` with following traceback:
```
/usr/bin/python3 /home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher /home/lain/Documents/some/some.py 
E+00000.026: /handling microsoft/vscode-python#1 request "launch" from Adapter-1/
             Traceback (most recent call last):
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/json.py", line 260, in validate
                 value[k] = validate_value(v)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/json.py", line 108, in validate
                 raise TypeError("must be " + " or ".join(t.__name__ for t in classinfo))
             TypeError: must be str
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 413, in __call__
                 value = validate(value)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/json.py", line 262, in validate
                 raise type(exc)("[{0!j}] {1}".format(k, exc))
             ValueError: Unknown conversion specifier j
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1078, in __init__
                 raise self
             ptvsd.common.messaging.InvalidMessageError: Invalid message: 'env' Unknown conversion specifier j
             
             Stack where logged:
               File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
                 self._bootstrap_inner()
               File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
                 self.run()
               File "/usr/lib/python3.7/threading.py", line 870, in run
                 self._target(*self._args, **self._kwargs)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1520, in _run_handlers
                 handler()
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 763, in _handle
                 result = handler(self)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/launcher/adapter.py", line 123, in launch_request
                 env.update(request("env", json.object(unicode)))
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 500, in __call__
                 return self.payload(*args, **kwargs)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 416, in __call__
                 raise message.isnt_valid("{0!r} {1}", key, exc)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 564, in isnt_valid
                 return args[0].error(InvalidMessageError, *args[1:], **kwargs)
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 552, in error
                 exc = exc_type(reason, cause, silent)  # will log it
               File "/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1080, in __init__
                 log.exception()
             

E+00000.038: /handling microsoft/vscode-python#1 request "launch" from Adapter-1/
             Handler 'Handlers.launch_request' (file '/home/lain/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/launcher/adapter.py', line 35)
             couldn't handle microsoft/vscode-python#1 request "launch" from Adapter-1:
             Invalid message: 'env' Unknown conversion specifier j
```
## Steps to reproduce:
1. Create workspace with file "hello.py" with any content.
2. Create debug configuration "Python: Current File"
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "env": {
                "Hello": 10
            },
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by int19h** [comment]
The behavior in general is by design - environment variables have string values, so using something else is an error. However, the error message is incorrect - it should clearly spell out what the expected type was. 

(And it tries to do exactly that, but there's a bug in the code generating that error message, which ends up producing the error message that you actually see...)

**Comment by xarpy** [comment]
I have the same problem to debug some apps with framework Flask and Django. Any solutions for this?

**Comment by int19h** [comment]
You have to use strings as variable values. The specific offender here is `"FLASK_DEBUG": true` - it should be `"FLASK_DEBUG": "true"`. With the fix, the error message will tell both the expected type (always str for "env"), and the name of the variable that is mistyped.

**Comment by meandmymind** [comment]
@int19h when this restriction on values type was added? I've been using VSCode for 2 years now and encoutered this problem the first time.

**Comment by int19h** [comment]
It boils down to the environment itself being a mapping of strings to strings, from the OS perspective. The old implementation didn't typecheck that well, but it never advertised that, and there was no documented process for how exactly a non-string value might get converted to a string; the docs never even mentioned the possibility of non-string values. The new implementation tries to enforce the schema, hence why it's complaining about this.

That said - we discussed this, and decided to allow numbers and booleans as values, since they were already de facto allowed before. To make this reliable, we'll document the behavior precisely, including how they get converted to strings.

**Comment by int19h** [comment]
BTW, here's an interesting question - *what* do you expect the conversion behavior to be?

For integers, it's pretty straightforward, of course. But floating point has some options - e.g. scientific notation. If we just use the default Python behavior, you will end up with something like `5.4321654321e-08`. If the value is being parsed by calling `float()` on it, that's fine, but I'm curious if there are any cases where this is not satisfactory.

Then there is the same question wrt booleans, except there are more options here. If we stringify them Python-style, you get "True" and "False". Or JS-style, and then it's "true" and "false". Or we could treat them as 1 and 0, which is the usual convention for apps in C. The problem is that there's no consistent pattern of how Python apps handle boolean env vars - some do `int()`, some just directly compare string values (and vary on case sensitivity).

**Comment by meandmymind** [comment]
@int19h According to schema available at [json.org](json.org), scientific notation is absoultely OK.
![image](https://user-images.githubusercontent.com/24773652/69912887-83def900-1462-11ea-937f-8e8a755d0c43.png)

Same with booleans, values in `env` field should be valid JSON objects, so booleans are `true` and `false` only.

About Python handling of boolean env vars, I'm curious how it was stringified before, because I used `true` as value in my launch.json, and Python code parsed this env value OK.

**Comment by int19h** [comment]
To clarify, this isn't about what JSON allows. The problem is that environment variables themselves are fundamentally strings - at the most basic level, the C API for them is `char* getenv(const char* name)`. So yes, you can of course write `1.0` or even `1e10` in JSON for numbers, and you can write `true` and `false` for booleans etc - but eventually it has to become an actual environment variable, and for that it needs to be made into a string.

On the other side, Python doesn't stringify anything, because Python receives environment variables from the OS as strings. Thus, if you wrote something like:
```py
if os.environ["FOO"]: ...
```
then what you're actually checking for is whether the value is an empty string or not, not whether it's boolean true/false. If we stringify true/false as "true"/"false" or "True"/"False", both of those values would cause the conditional to evaluate to true! The usual convention for environment variables that are boolean flags is to use 1 and 0 - but that would also be strings in practice, "1" and "0" - and, again, both values would be true for the purpose of such check.

If you actually want to interpret the environment variable as a boolean in Python, you have to parse explicitly, e.g. assuming 0/1:
```py
if int(os.environ["FOO"]): ...
```
but this won't work if we render JSON true & false as strings "true" and "false". On the other hand, it's also not uncommon to see something like:
```py
if os.environ["FOO"] == "true"
```
but this is a case-sensitive comparison, so "True" would be treated as false. If you do it case-insensitive, then "1" is still false, unless you also special-case it.

Note, by the way, that Python itself will not allow you to *set* non-string values, either:
```
>>> os.environ["FOO"] = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\3.8-64\lib\os.py", line 678, in __setitem__
    value = self.encodevalue(value)
  File "C:\Python\3.8-64\lib\os.py", line 734, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bool
```
thus dodging the ambiguity of stringification.

**Comment by int19h** [comment]
We're going to require "env" to be strings to be consistent with OS and Python. However, we'll do better validation on the extension side, so that you get squiggles for non-string values while editing launch.json.
