### ISSUE TITLE
debug Internal error

### ISSUE THREAD

**Issue by gnilsson2** [microsoft/ptvsd#1970]
[gunnarni@cmsapp02 ay_cms_user_dev.hg BEHAVE] $ /home/gunnarni/main/ay_cms_user_dev.hg/current_CARMSYS/bin/python /home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 33337 /home/gunnarni/main/ay_cms_user_dev.hg/bin/behave/test_behave.py -i finnair_test -v 
Traceback (most recent call last):
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__init__.py", line 15, in <module>
    from ptvsd.attach_server import (  # noqa
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/attach_server.py", line 9, in <module>
    from ptvsd._remote import (
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/_remote.py", line 14, in <module>
    from ptvsd.pydevd_hooks import install
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 16, in <module>
    from ptvsd.daemon import Daemon, DaemonStoppedError, DaemonClosedError
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 13, in <module>
    from .exit_handlers import (
  File "/home/gunnarni/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/exit_handlers.py", line 42
     for sig in self.SIGNALS}
       ^
 SyntaxError: invalid syntax

Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

my lanunch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "args": [  "-i", "finnair_test", "-v"],
            "console": "integratedTerminal"
        }
    ]
}

**Comment by fabioz** [comment]
@gnilsson2, which Python version are you using?

**Comment by gnilsson2** [comment]
Python 2.6.6 (r266:84292, Mar  3 2016, 13:59:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2

**Comment by fabioz** [comment]
Sorry about the delay in getting back to you.

The problem is that `ptvsd` only supports Python 2.7 onwards (note that there are no plans to add support for Python 2.6... the recommendation is that you upgrade to a newer Python version).
