### ISSUE TITLE
Cannot find Deepcopy when running Python 3.5.4 64-bit, with VS Code 1.41.0.

### ISSUE THREAD

**Issue by ismailfaruk** [microsoft/ptvsd#1990]
Tried: **from copy import deepcopy**. Work with Python 3.7.3. It was running with Python 3.5.4 until the recent VS Code update.
```
Traceback (most recent call last):
  File "c:\Users\isfar\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py", line 21, in <module>
    import ptvsd
  File "c:\Users\isfar\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__init__.py", line 13, in <module>
    from ._vendored import force_pydevd
  File "c:\Users\isfar\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\force_pydevd.py", line 18, in <module>
    pydevd_constants = import_module('_pydevd_bundle.pydevd_constants')
  File "C:\Users\isfar\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\isfar\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_constants.py", line 205, in <module>
    from _pydev_imps._pydev_saved_modules import thread
  File "c:\Users\isfar\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_saved_modules.py", line 22, in <module>
    import xmlrpc.server as _pydev_SimpleXMLRPCServer
  File "C:\Users\isfar\AppData\Local\Programs\Python\Python35\lib\xmlrpc\server.py", line 108, in <module>
    from http.server import BaseHTTPRequestHandler
  File "C:\Users\isfar\AppData\Local\Programs\Python\Python35\lib\http\server.py", line 103, in <module>
    import copy
  File "C:\Users\isfar\AppData\Local\Programs\Python\Python35\lib\copy.py", line 5, in <module>
    from copy import deepcopy
ImportError: cannot import name 'deepcopy'
```

**Comment by int19h** [comment]
This part of the error:
```
  File "C:\Users\isfar\AppData\Local\Programs\Python\Python35\lib\copy.py", line 5, in <module>
    from copy import deepcopy
```
implies that there's something wrong with copy.py in your Python installation - here's how that file looks in a stock version of Python 3.5:
https://github.com/python/cpython/blob/e5f6aba872e66bfd86eb592214696a519cded197/Lib/copy.py
(note that line 5 isn't even executable code!)

Can you try uninstalling and re-installing your Python? It might be worth to make sure that copy.py gets deleted correctly when you uninstall.

**Comment by fabioz** [comment]
Closing (seems to be a corrupt Python install).
