### ISSUE TITLE
Could not connect to 127.0.0.1: 50083

### ISSUE THREAD

**Issue by jheffez** [microsoft/ptvsd#1995]
Getting the above when debug (F5) a file. 
Running without debug (Ctrl F5) works (no error).
Debugging another file in the same folder is fine.

Windows 10, Python 3.7.5
vscode: 1.4.1.0
Python extension 2019.10.44104

non-debug command:
```
(sb) C:\Users\UserX\py>cmd /C "set "PTVSD_SESSION_ID=1" && set "PTVSD_LAUNCHER_PORT=50369" && c:\Users\UserX\py\sb\Scripts\python.exe c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\launcher c:\Users\UserX\py\files\Stable-baselines\optune2.py "`
```
Debug command:
```
(sb) C:\Users\UserX\py>cmd /C "set "PTVSD_SESSION_ID=1" && set "PTVSD_LAUNCHER_PORT=50118" && c:\Users\UserX\py\sb\Scripts\python.exe c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\launcher c:\Users\UserX\py\files\Stable-baselines\optune2.py "
**Could not connect to 127.0.0.1: 50117**

Traceback (most recent call last):
  File "c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 486, in start_client
    s.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\_vendored\pydevd\pydevd.py", line 2380, in settrace
    ide_access_token,
  File "c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\_vendored\pydevd\pydevd.py", line 2442, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\_vendored\pydevd\pydevd.py", line 1147, in connect
    s = start_client(host, port)
  File "c:\Users\UserX\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\ptvsd-cp37-cp37m-win_amd64\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 486, in start_client
    s.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```
Launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        },
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "enter-your-module-name-here",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "django": true
        },
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        },
        {
            "name": "Python: Current File (External Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "externalTerminal"
        }
    ]
}
```

**Comment by int19h** [comment]
This is a dup of #1930. We already have a fix for this, but the version of ptvsd with the fix hasn't shipped yet.

In the meantime, you can work around this by copying python.exe from your global Python installation into the venv Scripts folder, replacing the stub that is already there.

Alternatively, you can opt out of ptvsd 5 by disabling Python -> Experiments: Enabled in VSCode settings.
