### ISSUE TITLE
IronPython support

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#203]
Ensure that it works, and add it to the list of supported targets (i.e. make sure we run our tests against it etc).

**Comment by huguesv** [comment]
I get an "Unknown command" message box when I start debugging.

Here's the debug adapter host log:
```
 2> DebugAdapterHost version: 15.7.20222.2 commit:14b9b7a72cfaa4eeaadbe629b1b02155d924f94b
 2> [DebugAdapter] --> C (initialize-1): {"command":"initialize","arguments":{"clientID":"visualstudio","adapterID":null,"locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path","supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsHandshakeRequest":true},"seq":1,"type":"request"}
 2> [DebugAdapter] <--   E (legacyLocalConnected): {"seq": 0, "type": "event", "body": {"processGuid": "a9886501-f1d8-4536-9243-61ad20dd64c2", "result": 0}, "event": "legacyLocalConnected"}
 2> No handler registered for event of type 'legacyLocalConnected'!
 2> [DebugAdapter] <--   R (initialize-1): {"success": false, "seq": 1, "message": "Unknown command", "type": "response", "command": "initialize", "body": {}, "request_seq": 1}
 2> ERROR: Protocol error

ProtocolException: Unknown command

 2> ERROR: Unknown command
```

**Comment by huguesv** [comment]
Right now in VS for IronPython the old debugger starts when experimental debugger is intended to start, leading to VS debug adapter host getting really confused when it sees legacy debugger messages.
https://github.com/Microsoft/PTVS/issues/3899

**Comment by huguesv** [comment]
If I bypass that issue, here's the get from adapter host log:
```
 2> DebugAdapterHost version: 15.7.20222.2 commit:14b9b7a72cfaa4eeaadbe629b1b02155d924f94b
 2> [DebugAdapter] --> C (initialize-1): {"command":"initialize","arguments":{"clientID":"visualstudio","adapterID":null,"locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path","supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsHandshakeRequest":true},"seq":1,"type":"request"}
 2> [DebugAdapter] <--   E (exited): {"seq": 0, "type": "event", "body": {"exitCode": 1}, "event": "exited"}
 2> [DebugAdapter] <--   E (terminated): {"seq": 1, "type": "event", "body": {}, "event": "terminated"}
 2> [DebugAdapter] --> C (disconnect-2): {"command":"disconnect","arguments":{},"seq":2,"type":"request"}
 2> [DebugAdapter] <--   R (disconnect-2): {"success": false, "seq": 2, "message": "Traceback (most recent call last):\n  File \"C:\\Projects\\GitHub\\Microsoft\\ptvsd\\ptvsd\\ipcjson.py\", line 332, in on_request\n    target(request, args)\n  File \"C:\\Projects\\GitHub\\Microsoft\\ptvsd\\ptvsd\\wrapper.py\", line 652, in on_disconnect\n    if self.start_reason == 'launch':\nAttributeError: 'VSCodeMessageProcessor' object has no attribute 'start_reason'\n", "type": "response", "command": "disconnect", "body": {}, "request_seq": 2}
 2> Stopping due to fatal error: ProtocolException: Traceback (most recent call last):
  File "C:\Projects\GitHub\Microsoft\ptvsd\ptvsd\ipcjson.py", line 332, in on_request
    target(request, args)
  File "C:\Projects\GitHub\Microsoft\ptvsd\ptvsd\wrapper.py", line 652, in on_disconnect
    if self.start_reason == 'launch':
AttributeError: 'VSCodeMessageProcessor' object has no attribute 'start_reason'

 2> ERROR: Protocol error

ProtocolException: Traceback (most recent call last):
File "C:\Projects\GitHub\Microsoft\ptvsd\ptvsd\ipcjson.py", line 332, in on_request
target(request, args)
File "C:\Projects\GitHub\Microsoft\ptvsd\ptvsd\wrapper.py", line 652, in on_disconnect
if self.start_reason == 'launch':
AttributeError: 'VSCodeMessageProcessor' object has no attribute 'start_reason'

 2> ERROR: Debug Adapter did not respond to initial requests.
 2> ERROR: Traceback (most recent call last):
  File "C:\Projects\GitHub\Microsoft\ptvsd\ptvsd\ipcjson.py", line 332, in on_request
    target(request, args)
  File "C:\Projects\GitHub\Microsoft\ptvsd\ptvsd\wrapper.py", line 652, in on_disconnect
    if self.start_reason == 'launch':
AttributeError: 'VSCodeMessageProcessor' object has no attribute 'start_reason'
 2> ERROR: Exception while reporting error.

ComponentException: Exception of type 'Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.AD7.Definition.ComponentException' was thrown.

HResult: 0x80010108
```

**Comment by huguesv** [comment]
![image](https://user-images.githubusercontent.com/1696845/37547679-5d3c9cc2-2930-11e8-9285-e2ccdbac15dd.png)

**Comment by huguesv** [comment]
`platform.system() == 'cli'` so it's going in the non-windows code path in `start_client`.

```
    if platform.system() != 'Windows':
        signal.signal(
            signal.SIGHUP,
            (lambda signum, frame: signal_handler(signum, frame, proc)),
        )
```

There's a couple of other checks like that in ptvsd that will likely cause trouble.

**Comment by int19h** [comment]
Should we just feature test `SIGHUP`?

**Comment by huguesv** [comment]
I tried changing it to `hasattr(signal, 'SIGHUP')` and it's hanging a bit further now.

**Comment by huguesv** [comment]
I changed `on_initialize` a bit:
```
        cmd = pydevd_comm.CMD_VERSION
        os_id = 'WINDOWS' if platform.system() == 'Windows' or platform.system() == 'cli' else 'UNIX'
        print(os_id)
        msg = '1.1\t{}\tID'.format(os_id)
        yield self.pydevd_request(cmd, msg)
        print('after pydevd_request')
        self.send_response(
            request,
            supportsExceptionInfoRequest=True,
            supportsConfigurationDoneRequest=True,
            supportsConditionalBreakpoints=True,
            supportsSetVariable=True,
            supportsExceptionOptions=True,
            supportsEvaluateForHovers=True,
            supportsValueFormattingOptions=True,
            exceptionBreakpointFilters=[
                {
                    'filter': 'raised',
                    'label': 'Raised Exceptions',
                    'default': 'false'
                },
                {
                    'filter': 'uncaught',
                    'label': 'Uncaught Exceptions',
                    'default': 'true'
                },
            ],
        )
        self.send_event('initialized')
```

and `pydevd_request`:
```
    def pydevd_request(self, loop, cmd_id, args):
        # TODO: docstring
        print('PydevdSocket.pydevd_request: {0}'.format(cmd_id))
        seq, s = self.make_packet(cmd_id, args)
        fut = loop.create_future()
        with self.lock:
            self.requests[seq] = loop, fut
            print('writing to pipe')
            os.write(self.pipe_w, s.encode('utf8'))
        print('about to return')
        return fut
```


pydevd never receives the command `CMD_VERSION`, and `print('after pydevd_request')` doesn't execute.

`print('writing to pipe')` and `print('about to return')` both execute.

**Comment by zooba** [comment]
We should use `sys.platform` not `platform.system()`. The `platform` module provides diagnostic/identifying information, rather than decision making info (for example, `sys.getwindowsversion()` returns the version Windows is treating the process as, while `platform.version()` returns the OS version - try it on Python 2.7 or with compatibility mode enabled).

I would argue that `platform.system()` on IronPython should still return Windows/UNIX rather than "cli". Or perhaps the .NET Framework/Core title.
