### ISSUE TITLE
Fatal Python error: PyCOND_WAIT(gil_cond) failed

### ISSUE THREAD

**Issue by Haibao425** [microsoft/ptvsd#2049]
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.58038
- OS and version: MacOS: 10.15.2
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server

## Expected behaviour

Run Debug, Debug current file, and there are not any errors show in terminal window.

## Actual behaviour

Python report "Fatal Python error: PyCOND_WAIT(gil_cond) failed"

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run a python file with F5.
```
When I click Debug->Start Debugging for my simple python file, it report Fatal Python error: PyCOND_WAIT(gil_cond) failed.

If I clear the DEBUG CONSOLE window, and then sometimes the issue is gone.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

[2020-01-16 16:45:37.968] [renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2819:336)
at async R.terminate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5113:637)
[2020-01-16 16:45:52.621] [renderer1] [error] Server[1] disconnected unexpectedly: Error: Server[1] disconnected unexpectedly
at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
at processTicksAndRejections (internal/process/task_queues.js:89:5)
at async R.fetchThreads (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:411)
at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:917
[2020-01-16 16:46:01.919] [renderer1] [error] Server[1] disconnected unexpectedly: Error: Server[1] disconnected unexpectedly
at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
at processTicksAndRejections (internal/process/task_queues.js:89:5)
at async R.fetchThreads (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:411)
at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:917

Thread 0x0000700005770000 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551 in wait
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 179 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x000070000526d000 (most recent call first):
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 270 in _read_line
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 287 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x0000700004d6a000 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/queue.py", line 173 in get
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 398 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x0000000114feedc0 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 171 in islink
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 429 in _joinrealpath
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 395 in realpath
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 356 in _NormPath
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 343 in _NormPaths
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 715 in get_abs_path_real_path_and_base_from_file
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 741 in get_abs_path_real_path_and_base_from_frame
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_bundle/pydevd_trace_dispatch
```

2nd stack trace:

```
bash-3.2$ env PTVSD_LAUNCHER_PORT=52193 /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 /Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFil
es/lib/python/new_ptvsd/no_wheels/ptvsd/launcher /Users/haibaoli/Projects/Python/module1/main.py --runs 5
Fatal Python error: PyCOND_WAIT(gil_cond) failed

Thread 0x00007000085a6000 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551 in wait
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 225 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line
156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007000080a3000 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551 in wait
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 179 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line
156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x0000700007ba0000 (most recent call first):
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 270 in _read_line
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 287 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x000070000769d000 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/queue.py", line 173 in get
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 398 in _on_run
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x000000010b63cdc0 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 171 in islink
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 429 in _joinrealpath
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 395 in realpath
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 356 in _NormPath
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 343 in _NormPaths
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 715 in get_abs_path_real_path_and_base_from_file
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 741 in get_abs_path_real_path_and_base_from_frame
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 427 in call
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1260 in enumerate
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_tracing.py", line 189 in set_trace_to_threads
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 879 in enable_tracing
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 2649 in _locked_settrace
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 2555 in settrace
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/api.py", line 26 in _settrace
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/api.py", line 209 in attach
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/api.py", line 73 in debug
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/init.py", line 109 in attach
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/cli.py", line 182 in setup_debug_server
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/cli.py", line 189 in run_file
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/cli.py", line 361 in main
File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/main.py", line 45 in
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85 in _run_code
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193 in _run_module_as_main
bash-3.2$
```

**Comment by fabioz** [comment]
@Haibao425 do you have something special in your code? (can you share it?)

The place where it seems to crash is inside an `os.lstat(path)` call (on both stack traces -- which hints it's some issue in Python itself -- my guess right now is that it's in the particular build you're using).

Can you check with a different Python build to see if you get the same error?

**Comment by Haibao425** [comment]
import re
import math
import numpy as np
import sys
from enum import Enum
from sys import exc_info
import numpy

class Base:
  def __init__(self):
    pass

  def __init__(self, name):
    print("init Base")
    self.__name = name

  def PrintName(self):
    print("Parent Class")
    print(self.__name)


class Child(Base):
  def __init__(self, name, age):
    print("init Child")
    self.__age = age
    super(Child, self).__init__(name)

  def PrintChildName(self):
    print("Child Class")
    print(self.__age)
    self.PrintName()


child = Child("haibao", "35")
child.PrintChildName()

__patternIpAddress = r"(?P<IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):\d{1,4}"
__patternAttachedDevice = r"(?P<SN>\w{9,})\s+device"
__patternAttachedDeviceWithPort = r"(?P<SN>\w{9,}?)\s+device\s+[uU][sS][bB]:(?P<USBPORT>\d+-\d+\.\d+)\s+.*"

print("List of device attached:\n98021FFBA0003L device\n98021FFBA0003L device\n192.168.1.14:5555 device. \n192.168.1.15:5555 listed.")

resultsIp = re.findall(re.compile(__patternIpAddress, re.S), "List of device attached:\n98021FFBA0003L device\n98021FFBA0003L device\n192.168.1.14:5555 device. \n192.168.1.15:5555 listed.")
resultsSn = re.findall(re.compile(__patternAttachedDevice, re.S), "List of device attached:\n98021FFBA0003L device\n98021FFBA0003L device\n192.168.1.14:5555 device. \n192.168.1.15:5555 listed.")

resultsIp1 = re.search(re.compile(__patternIpAddress, re.S), "List of device attached:\n98021FFBA0003L device\n98021FFBA0003L device\n192.168.1.14:5555 device. \n192.168.1.15:5555 listed.")
resultsSn1 = re.search(re.compile(__patternAttachedDevice, re.S), "List of device attached:\n98021FFBA0003L device\n98021FFBA0003L device\n192.168.1.14:5555 device. \n192.168.1.15:5555 listed.")
resultsUsbPort = re.findall(re.compile(__patternAttachedDeviceWithPort, re.S), "List of device attached:\n015d2994ec2xxx         device Usb:2-1.5 product:nakasi model:Nexus_7 device:grouper")

print(len(resultsUsbPort))

if "015d2994ec2xxx" in resultsUsbPort:
  print("Found!")

if "192.168.1.14" in resultsIp:
  print("connected")

print("List of device attached:\n98021FFBA0003L device\n98021FFBA0003L device\n192.168.1.14:5555 device. \n192.168.1.15:5555 listed.")

**Comment by Haibao425** [comment]
> @Haibao425 do you have something special in your code? (can you share it?)
> 
> The place where it seems to crash is inside an `os.lstat(path)` call (on both stack traces -- which hints it's some issue in Python itself -- my guess right now is that it's in the particular build you're using).
> 
> Can you check with a different Python build to see if you get the same error?

I pasted my code already, please try it, I met the issue every time, I could execute the code after I cleared the terminal window couple times later, but I do not think it is related with terminal window, I'd rather believe that GIL was not released correctly in time after I had run the code.

**Comment by fabioz** [comment]
I think I found the culprit... I'll start to work on a fix.

**Comment by fabioz** [comment]
This is already fixed and will be available in the next release.

As a note, this issue only affects older versions of Python (Python 2.7 up to Python 3.6) -- so, if you can upgrade to use Python 3.7 or Python 3.8 this should work in the ptvsd version you already have there.

**Comment by oji** [comment]
Hi @fabioz, can you confirm in which version was fixed? I updated to `5.0.0a12` and still hangs a lot when starting. (I'm using python 3.6).

**Comment by kangkang59812** [comment]
repost. This error makes me crazy.

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by fabioz** [comment]
@karthiknadig do you know at which release https://github.com/microsoft/debugpy/commit/2364dc2e6c9fe5b08dc8478559a389de406513fd landed?
