### ISSUE TITLE
Using gevent in conftest breaks debugging

### ISSUE THREAD

**Issue by kondratyev-nv** [microsoft/ptvsd#2054]
## Environment data

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.0-9-generic snap

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.58038
- OS and version: Ubuntu 20.04
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.6

## Expected behaviour

Tests can be successfully debuged with pauses on breakpoints.

## Actual behaviour

Running tests works fine. However, debug fails with the following error
```
ImportError while loading conftest '/<some-path>/vscode-python-test-gevent-bug/app/tests/conftest.py'.
RuntimeError: cannot release un-acquired lock
```

## Steps to reproduce:

1. Clone the code from the sample project https://github.com/mcauto/vscode-python-test-gevent-bug/ (Also, see https://github.com/mcauto/vscode-python-test-gevent-bug/pull/1 for the steps to configure the environment).
2. Open Test Explorer
3. Run all tests (should work fine)
4. Debug test. Debug stops. Open Debug Console. Something similar to the following error should be printed
```
ImportError while loading conftest '/<some-path>/vscode-python-test-gevent-bug/app/tests/conftest.py'.
RuntimeError: cannot release un-acquired lock
```

## Logs

In the `Output`→`Python Test Log`:
```
python /<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir /<some-path>/vscode-python-test-gevent-bug -s --cache-clear app
```

**Comment by fabioz** [comment]
@kondratyev-nv have you used the `gevent` flag?

See: https://code.visualstudio.com/docs/python/debugging#_gevent

**Comment by kondratyev-nv** [comment]
Well, I'm trying to debug tests via Test Explorer, so launch.json should not be required. This is why I'm not sure if this is an issue with the ptvsd or the Python Extension. I've also tried to set the environment variables in .env file
```
DEBUG=true
GEVENT_SUPPORT=True
```
I also tried to add debug configuration to debug tests 
```
{
    "name": "Python: Module",
    "type": "python",
    "request": "launch",
    "module": "pytest",
    "django": true,
    "gevent": true,
}
```
I'm having the same issue but in the other form
```
/<some-path>/vscode-python-test-gevent-bug/.venv/bin/python /<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 38365 -m pytest 
=============================================== test session starts ===============================================
platform linux -- Python 3.7.6, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
django: settings: confs.settings (from ini)
rootdir: /<some-path>/vscode-python-test-gevent-bug, inifile: pytest.ini
plugins: cov-2.8.1, django-3.8.0
collected 0 items / 1 error                                                                                       

===================================================== ERRORS ======================================================
__________________________________________ ERROR collecting test session __________________________________________
.venv/lib/python3.7/site-packages/_pytest/config/__init__.py:459: in _importconftest
    return self._conftestpath2mod[key]
E   KeyError: PosixPath('/<some-path>/vscode-python-test-gevent-bug/app/tests/conftest.py')

During handling of the above exception, another exception occurred:
.venv/lib/python3.7/site-packages/_pytest/config/__init__.py:465: in _importconftest
    mod = conftestpath.pyimport()
.venv/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:152: in __exit__
    ???
<frozen importlib._bootstrap>:107: in release
    ???
E   RuntimeError: cannot release un-acquired lock

During handling of the above exception, another exception occurred:
.venv/lib/python3.7/site-packages/py/_path/common.py:383: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
.venv/lib/python3.7/site-packages/py/_path/common.py:435: in gen
    for p in self.gen(subdir):
.venv/lib/python3.7/site-packages/py/_path/common.py:424: in gen
    dirs = self.optsort([p for p in entries
.venv/lib/python3.7/site-packages/py/_path/common.py:425: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
.venv/lib/python3.7/site-packages/_pytest/main.py:626: in _recurse
    ihook = self.gethookproxy(dirpath)
.venv/lib/python3.7/site-packages/_pytest/main.py:445: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
.venv/lib/python3.7/site-packages/_pytest/config/__init__.py:437: in _getconftestmodules
    mod = self._importconftest(conftestpath)
.venv/lib/python3.7/site-packages/_pytest/config/__init__.py:473: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/<some-path>/vscode-python-test-gevent-bug/app/tests/conftest.py'), (<class 'RuntimeError'>, RuntimeError('cannot release un-acquired lock'), <traceback object at 0x7f0d92e606e0>))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 1 error in 0.86s =================================================
E00001.895: (while handling ('CMD_EXIT', 26))
            Error handling pydevd event: 
            
            Traceback (most recent call last):
              File "/<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/wrapper.py", line 966, in on_pydevd_event
                f = self.pydevd_events[cmd_id]
            KeyError: 129
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "/<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/wrapper.py", line 968, in on_pydevd_event
                raise UnsupportedPyDevdCommandError(cmd_id)
            ptvsd.wrapper.UnsupportedPyDevdCommandError: unsupported pydevd command 129
            

E00001.897: (while handling ('CMD_EXIT', 26))
            Error handling pydevd message: 
            
            Traceback (most recent call last):
              File "/<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/wrapper.py", line 966, in on_pydevd_event
                f = self.pydevd_events[cmd_id]
            KeyError: 129
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "/<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/session.py", line 187, in handle_pydevd_message
                return self._msgprocessor.on_pydevd_event(cmdid, seq, text)
              File "/<some-path>/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/wrapper.py", line 968, in on_pydevd_event
                raise UnsupportedPyDevdCommandError(cmd_id)
            ptvsd.wrapper.UnsupportedPyDevdCommandError: unsupported pydevd command 129
            

```

**Comment by fabioz** [comment]
I see the issue now... This is only supported in ptvsd 5.x.

See: https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267 on how to opt into using the new version.

**Comment by kondratyev-nv** [comment]
@fabioz Awesome, it works! Will it be included in the next Python Extension version?

**Comment by fabioz** [comment]
I'm not sure about the release on the Python Extension... @karthiknadig, do you have more info?

**Comment by int19h** [comment]
Yep, we are shipping the new debugger with the extension. The reason why you need insiders for this right now is because that one has the ability to opt into using the new debugger all the time; but the next stable release of the extension will have that also.
