### ISSUE TITLE
KeyError: 'PTVSD_LAUNCHER_PORT' happened when debug with "sudo"

### ISSUE THREAD

**Issue by cranechu** [microsoft/ptvsd#2081]
## Environment data

- PTVSD version: 5.0.0a12
- OS and version: Fedora 31, Linux kernel 5.4.17-200.fc31.x86_64
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.6
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I tried to debug a python file with "sudo" by modifying launch.json, but I got the error message below. 
I tried it twice.

``` shell
laptop:~/repo_debug_sudo_pytest▶ sudo /bin/python /home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher /home/cranechu/repo_debug_sudo_pytest/test.py 
E+00000.031: Error parsing 'PTVSD_LAUNCHER_PORT':
             
             Traceback (most recent call last):
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 36, in option
                 return type(os.environ.pop(name, *args))
               File "/usr/lib64/python3.7/_collections_abc.py", line 795, in pop
                 value = self[key]
               File "/usr/lib64/python3.7/os.py", line 679, in __getitem__
                 raise KeyError(key) from None
             KeyError: 'PTVSD_LAUNCHER_PORT'
             
             Stack where logged:
               File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
                 "__main__", mod_spec)
               File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
                 exec(code, run_globals)
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 80, in <module>
                 main()
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 40, in main
                 launcher_port = option("PTVSD_LAUNCHER_PORT", int)
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 38, in option
                 raise log.exception("Error parsing {0!r}:", name)
             

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 80, in <module>
    main()
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 40, in main
    launcher_port = option("PTVSD_LAUNCHER_PORT", int)
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 38, in option
    raise log.exception("Error parsing {0!r}:", name)
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 36, in option
    return type(os.environ.pop(name, *args))
  File "/usr/lib64/python3.7/_collections_abc.py", line 795, in pop
    value = self[key]
  File "/usr/lib64/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PTVSD_LAUNCHER_PORT'

laptop:~/repo_debug_sudo_pytest▶ env PTVSD_LAUNCHER_PORT=37493 sudo /bin/python /home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher /home/cranechu/repo_debug_sudo_pytest/test.py 
E+00000.042: Error parsing 'PTVSD_LAUNCHER_PORT':
             
             Traceback (most recent call last):
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 36, in option
                 return type(os.environ.pop(name, *args))
               File "/usr/lib64/python3.7/_collections_abc.py", line 795, in pop
                 value = self[key]
               File "/usr/lib64/python3.7/os.py", line 679, in __getitem__
                 raise KeyError(key) from None
             KeyError: 'PTVSD_LAUNCHER_PORT'
             
             Stack where logged:
               File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
                 "__main__", mod_spec)
               File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
                 exec(code, run_globals)
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 80, in <module>
                 main()
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 40, in main
                 launcher_port = option("PTVSD_LAUNCHER_PORT", int)
               File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 38, in option
                 raise log.exception("Error parsing {0!r}:", name)
             

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 80, in <module>
    main()
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 40, in main
    launcher_port = option("PTVSD_LAUNCHER_PORT", int)
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 38, in option
    raise log.exception("Error parsing {0!r}:", name)
  File "/home/cranechu/.vscode/extensions/ms-python.python-2020.2.62710/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 36, in option
    return type(os.environ.pop(name, *args))
  File "/usr/lib64/python3.7/_collections_abc.py", line 795, in pop
    value = self[key]
  File "/usr/lib64/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PTVSD_LAUNCHER_PORT'

laptop:~/repo_debug_sudo_pytest▶ 
```

## Expected  behavior

Debug should work with sudo enabled. 

## Steps to reproduce:
1. git clone https://github.com/cranechu/debug_python_with_sudo
2. cd debug_python_with_sudo
3. code .
4. open test.py
5. "F5" to start debug

Here is the copy of launch.json in this minimized repository. "sudo" is manually added. 

``` json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal", 
            "sudo": true
        }
    ]
}
```

**Comment by int19h** [comment]
I think this is happening because `sudo` does not propagate the environment by default, as a matter of security. It needs to be `sudo -E`, and the user must have the appropriate permission.

The real problem, though, is that the adapter uses `sudo` when spawning launcher it all. It doesn't actually need to do that, because the launcher will do it when it spawns the debuggee.

**Comment by SilverJan** [comment]
@int19h when will this be available in VS Code?

**Comment by int19h** [comment]
It will be available in an insider build once https://github.com/microsoft/vscode-python/pull/10290 is merged.
