### ISSUE TITLE
Wrong when use vs code & ptvsd.py to  debug a python file, which included python multiprocessing code

### ISSUE THREAD

**Issue by Dingseewhole** [microsoft/ptvsd#2136]
environment
vs code == 1.49.1(windows)
PTVSD == 4.3.2
python ==3.7.5
code environment= ubuntun and docker
_______________________________________________________________________________________
When I try to use **vs code** and **ptvsd.py** to debug a **python** code, which included some **multiprocessing.py** part. The code will **timeout** when it goes to the multiprocessing part, and report:
" Traceback (most recent call last):
Error in atexit._run_exitfuncs: 
RuntimeError: already started"
You can see the wrong detail **WRONG TWO** in the end.

After I saw some old issue, I try to add code  `multiprocessing.set_start_method('spawn',True)` before using multiprocessing part
But after I do that the vs code debug  shows：“OSError: [Errno 98] Address already in use”

I think there are something wrong when I use both 'multiprocessing.set_start_method('spawn',True)' **and** `ptvsd.enable_attach(address = ('0.0.0.0', 8888))`
`ptvsd_enable_attach(address)`
Because when I use vs code and ptvsd to debug a python code, which without multiprocessing everything works. 
And without vs code &PTVSD, the multiprocessing code works too.
You can see the wrong detail **WRONG TWO** in the end.

___________________________________**WRONG TWO**_______________________________
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 412, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 248, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 528, in new_fork
    _on_forked_process()
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 50, in _on_forked_process
    pydevd.settrace_forked()
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2427, in settrace_forked
    patch_multiprocessing=True,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/pydevd_hooks.py", line 136, in _start_client
    return start_client(daemon, h, p)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 62, in <lambda>
    start_client=(lambda daemon, h, port: start_daemon()),
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 50, in start_daemon
    _, next_session = daemon.start_server(addr=(host, port))
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/daemon.py", line 158, in start_server
    with self.started():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/daemon.py", line 110, in started
    self.start()
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/daemon.py", line 145, in start
    raise RuntimeError('already started')
RuntimeError: already started
Unhandled exception in thread started by Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7efe4d55acd0>

____________________________________**WRONG TWO**________________________
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dingsh/LightGCN-restart-0826/code/main_dsh.py", line 22, in <module>
    ptvsd.enable_attach(address = ('0.0.0.0', 8888))
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 79, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/pydevd_hooks.py", line 136, in _start_client
    return start_client(daemon, h, p)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 62, in <lambda>
    start_client=(lambda daemon, h, port: start_daemon()),
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 50, in start_daemon
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dingsh/LightGCN-restart-0826/code/main_dsh.py", line 22, in <module>
    ptvsd.enable_attach(address = ('0.0.0.0', 8888))
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 79, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/pydevd_hooks.py", line 136, in _start_client
    self._server = create_server(addr.host, addr.port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/socket.py", line 79, in create_server
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dingsh/LightGCN-restart-0826/code/main_dsh.py", line 22, in <module>
    ptvsd.enable_attach(address = ('0.0.0.0', 8888))
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 79, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/pydevd_hooks.py", line 136, in _start_client
    return start_client(daemon, h, p)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 62, in <lambda>
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dingsh/LightGCN-restart-0826/code/main_dsh.py", line 22, in <module>
    ptvsd.enable_attach(address = ('0.0.0.0', 8888))
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 79, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/pydevd_hooks.py", line 136, in _start_client
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dingsh/LightGCN-restart-0826/code/main_dsh.py", line 22, in <module>
    ptvsd.enable_attach(address = ('0.0.0.0', 8888))
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_remote.py", line 79, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    self._server = create_server(addr.host, addr.port)
  File "/usr/local/lib/python3.7/dist-packages/ptvsd/socket.py", line 79, in create_server
    server.bind((host, port))
OSError: [Errno 98] Address already in use

**Comment by Dingseewhole** [comment]
My vscode is1.49.1
python is 3.7.5
ptvsd is 4.3.2

**Comment by int19h** [comment]
Can you please try with https://github.com/microsoft/debugpy, and file an issue there if it's still a problem? debugpy is a replacement for ptvsd, and we are not actively fixing bugs in the latter.

**Comment by Dingseewhole** [comment]
Hi int19th, thanks for your replay.
I have already tried the **debugpy**, and everything works now!
It's so nice to use such a nice python package, and I must go to star the debugpy programme : )
