### ISSUE TITLE
Error while detaching from remote

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#236]
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\pyenv\py3664\lib\site-packages\ptvsd\ipcjson.py", line 263, in send_event
    body=kwargs,
  File "C:\pyenv\py3664\lib\site-packages\ptvsd\ipcjson.py", line 102, in _send
Exception in thread ptvsd.Server:
Traceback (most recent call last):
  File "C:\pyenv\py3664\lib\site-packages\ptvsd\ipcjson.py", line 292, in process_one_message
    msg = self.__message.pop(0)
IndexError: pop from empty list
```

**Comment by DonJayamanne** [comment]
I'm not getting this error in VSC.

**Comment by DonJayamanne** [comment]
@karthiknadig Please test with the latest version of PTVSD, this may have been resolved with the recent changes made by Eric.

**Comment by karthiknadig** [comment]
Yep. Cannot repro with the latest.
