### ISSUE TITLE
Path matching tests fail when running in windows

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#243]
Powershell repro steps: (make sure you follow the casing as in instructions)
1. clone master to `C:\GIT\ptvsd`
2. start powershell: `cd c:\git\ptvsd`
3. start command prompt in powershell window: `cmd`
4. run the test: `py -3 -m tests --quick`

PYTHONPATH repro steps: (make sure you follow the casing as in instructions)
1. clone master to `C:\GIT\ptvsd`
2. open command prompt and run: `set PYTHONPATH:c:\git\ptvsd`
3. run the test: `py -3 -m tests --quick`

```
C:\>py -3 -m tests --quick
(will look for tests under C:\git\ptvsd\tests\ptvsd)
running tests...
warning: Debugger speedups using cython not found. Run '"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" "C:\git\ptvsd\ptvsd\pydevd\setup_cython.py" build_ext --inplace' to build.
...FF.F..........ssss.s..s....sssssssssss.........s.sssss........ss.s...s......
======================================================================
FAIL: test_path_names_lowercase_enabled (tests.ptvsd.test_pathutils.PathUtilTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\git\ptvsd\tests\ptvsd\test_pathutils.py", line 66, in test_path_names_lowercase_enabled
    tool.un_normcase(file_path.lower()))
AssertionError: 'C:\\git\\ptvsd\\tests\\ptvsd\\test_pathutils.py' != 'C:\\GIT\\ptvsd\\tests\\ptvsd\\test_pathutils.py'
- C:\git\ptvsd\tests\ptvsd\test_pathutils.py
?    ^^^
+ C:\GIT\ptvsd\tests\ptvsd\test_pathutils.py
?    ^^^
 
 
======================================================================
FAIL: test_path_names_normcased (tests.ptvsd.test_pathutils.PathUtilTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\git\ptvsd\tests\ptvsd\test_pathutils.py", line 32, in test_path_names_normcased
    tool.un_normcase(os.path.normcase(file_path)))
AssertionError: 'C:\\git\\ptvsd\\tests\\ptvsd\\test_pathutils.py' != 'C:\\GIT\\ptvsd\\tests\\ptvsd\\test_pathutils.py'
- C:\git\ptvsd\tests\ptvsd\test_pathutils.py
?    ^^^
+ C:\GIT\ptvsd\tests\ptvsd\test_pathutils.py
?    ^^^
 
 
======================================================================
FAIL: test_path_names_uppercase_enabled (tests.ptvsd.test_pathutils.PathUtilTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\git\ptvsd\tests\ptvsd\test_pathutils.py", line 49, in test_path_names_uppercase_enabled
    tool.un_normcase(file_path.upper()))
AssertionError: 'C:\\git\\ptvsd\\tests\\ptvsd\\test_pathutils.py' != 'C:\\GIT\\ptvsd\\tests\\ptvsd\\test_pathutils.py'
- C:\git\ptvsd\tests\ptvsd\test_pathutils.py
?    ^^^
+ C:\GIT\ptvsd\tests\ptvsd\test_pathutils.py
?    ^^^

```

**Comment by ericsnowcurrently** [comment]
I don't have a Windows machine to debug this.

**Comment by ericsnowcurrently** [comment]
@karthiknadig is this still an issue?  I was unable to repro (on Windows).

**Comment by DonJayamanne** [comment]
@ericsnowcurrently 
Ensure you set the `PYTHONPATH` in lowercase as follows:

> open command prompt and run: set PYTHONPATH:c:\git\ptvsd

**Comment by ericsnowcurrently** [comment]
Ah, right.  I can repro now.
