### ISSUE TITLE
SystemError: 'error return without exception set' while running tests in in VS

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#314]
```
Hello world
Exception ignored in: <generator object using_format at 0x0000023729859728>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000237298597D8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000237298598E0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000237298599E8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000023729859AF0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000023729859CA8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000023729859D58>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000023729859EB8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ptvsd\wrapper.py", line 787, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
```

**Comment by karthiknadig** [comment]
This occurs sometimes when running `DebugProjectUITestsExeprimental.ExpressionEvaluation` tests in VS.

**Comment by int19h** [comment]
The interesting thing about this error message is that it indicates a bug somewhere in C code - it's an exception that happens when a C function called by Python returns non-zero (indicating error), but doesn't set the current exception information.

Given that it's happening on the line where no such code is explicitly invoked, I suspect we're triggering some issue in pydevd optimized tracing code. 

This is likely to be a huge pain to debug...

**Comment by DonJayamanne** [comment]
Changed the milestone to reflect the milestone assigned in https://github.com/Microsoft/ptvsd/issues/397#event-1608759093

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/275844/python-debug-adapter-exited-unexpectedly.html

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/248606/you-guys-have-ruined-visual-studio-1571.html

**Comment by karthiknadig** [comment]
I have not seen this being reported on v4.1.1a5 or later. Reopen if seen again.

**Comment by georgealverson** [comment]
Just upgraded to VS 15.7.6:

Exception ignored in: <generator object using_format at 0x000001D8FFCFDBF8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set

**Comment by karthiknadig** [comment]
@georgealverson This issue should be resolved in the later versions of ptvsd `>=4.1.1a8`. It should be available in VS 15.8

**Comment by pjm4github** [comment]
Now seeing this problem in pandas when I'm stopped in the debugger in PyCharm.
In[4]: pd.__version__
Out[4]: '0.24.2'

 Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F570>
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F308>
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534FA40>
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F780>
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534FAF0>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
SystemError: error return without exception set
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F360>
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F048>
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F308>
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F570>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Exception ignored in: <generator object _trim_zeros.<locals>._cond.<locals>.<genexpr> at 0x000001470534F728>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set
Traceback (most recent call last):
  File "C:\Users\pmoran\jira\slf\venv\lib\site-packages\pandas\io\formats\format.py", line 1423, in <genexpr>
    return (len(finite) > 0 and all(x.endswith('0') for x in finite) and
SystemError: error return without exception set

**Comment by nietras** [comment]
I am getting this issue in VS2019 16.4 still.
