### ISSUE TITLE
TypeError an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#385]
Error in version: 4.1.1a1
```python
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 814, in pydevd_notify
    return self._pydevd_notify(cmd_id, args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 384, in pydevd_notify
    os.write(self.pipe_w, s.encode('utf8'))
TypeError: an integer is required (got type NoneType)
```

**Comment by int19h** [comment]
Since the root cause here is trying to use the pipe after it has been disposed of, this might also be affected by the lifetime management changes in https://github.com/Microsoft/ptvsd/pull/381/

**Comment by karthiknadig** [comment]
I have not seen this issue since #381
