### ISSUE TITLE
LogpointTests failing on Windows

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#392]
On Windows:
```
======================================================================
FAIL: test_basic (tests.highlevel.test_live_pydevd.LogpointTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\GIT\ptvsd\tests\highlevel\test_live_pydevd.py", line 268, in test_basic
    self.new_event('output', **dict(category='stdout', output='1+2=3' + os.linesep)), # noqa
  File "C:\GIT\ptvsd\tests\highlevel\__init__.py", line 788, in assert_vsc_received
    self.assertEqual(received, expected)
AssertionError: Lists differ: [Even[1452 chars]='output', body={'category': 'stdout', 'output': '1+2=3\n'})] != [Even[1452 chars]='output', body={'category': 'stdout', 'output': '1+2=3\r\n'})]

First differing element 9:
Event(seq=9, event='output', body={'category': 'stdout', 'output': '1+2=3\n'})
Event(seq=9, event='output', body={'category': 'stdout', 'output': '1+2=3\r\n'})

  [Event(seq=0, event='output', body={'category': 'telemetry', 'output': 'ptvsd', 'data': {'version': '4.1.1a2+4.gaffbf99'}}),
   Response(seq=1, request_seq=0, command='initialize', success=True, message='', body={'supportsExceptionInfoRequest': True, 'supportsConfigurationDoneRequest': True, 'supportsConditionalBreakpoints': True, 'supportsHitConditionalBreakpoints': True, 'supportsSetVariable': True, 'supportsExceptionOptions': True, 'supportsEvaluateForHovers': True, 'supportsValueFormattingOptions': True, 'supportsSetExpression': True, 'supportsModulesRequest': True, 'supportsLogPoints': True, 'exceptionBreakpointFilters': [{'filter': 'raised', 'label': 'Raised Exceptions', 'default': False}, {'filter': 'uncaught', 'label': 'Uncaught Exceptions', 'default': True}]}),
   Event(seq=2, event='initialized', body={}),
   Response(seq=3, request_seq=1, command='attach', success=True, message='', body={}),
   Response(seq=4, request_seq=2, command='setBreakpoints', success=True, message='', body={'breakpoints': [{'id': 1, 'verified': True, 'line': '4'}]}),
   Response(seq=5, request_seq=3, command='configurationDone', success=True, message='', body={}),
   Event(seq=6, event='process', body={'name': 'C:\\Users\\karth\\AppData\\Local\\Temp\\workspace-qp7h6f2r\\spam.py', 'systemProcessId': 7924, 'isLocalProcess': True, 'startMethod': 'attach'}),
   Event(seq=7, event='exited', body={'exitCode': 0}),
   Event(seq=8, event='terminated', body={}),
-  Event(seq=9, event='output', body={'category': 'stdout', 'output': '1+2=3\n'})]
+  Event(seq=9, event='output', body={'category': 'stdout', 'output': '1+2=3\r\n'})]
?                                                                            ++
```

On Linux (WSL): The output here changes with each run.
```
======================================================================
FAIL: test_basic (tests.highlevel.test_live_pydevd.LogpointTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/GIT/ptvsd/tests/highlevel/test_live_pydevd.py", line 268, in test_basic
    self.new_event('output', **dict(category='stdout', output='1+2=3' + os.linesep)), # noqa
  File "/mnt/c/GIT/ptvsd/tests/highlevel/__init__.py", line 788, in assert_vsc_received
    self.assertEqual(received, expected)
AssertionError: Lists differ: [Even[1187 chars]y={'startMethod': 'attach', 'systemProcessId':[472 chars]r'})] != [Even[1187 chars]y={'systemProcessId': 67, 'startMethod': 'atta[243 chars]t'})]

First list contains 1 additional elements.
First extra element 10:
Event(seq=10, event='output', body={'output': "/mnt/c/GIT/ptvsd/ptvsd/wrapper.py:808: UserWarning: timed out waiting for disconnect request\n  warnings.warn('timed out waiting for disconnect request')\n", 'category': 'stderr'})

  [Event(seq=0, event='output', body={'output': 'ptvsd', 'data': {'version': '4.1.1a2+4.gaffbf99.dirty'}, 'category': 'telemetry'}),
   Response(seq=1, request_seq=0, command='initialize', success=True, message='', body={'supportsLogPoints': True, 'supportsEvaluateForHovers': True, 'supportsSetVariable': True, 'supportsExceptionInfoRequest': True, 'exceptionBreakpointFilters': [{'filter': 'raised', 'label': 'Raised Exceptions', 'default': False}, {'filter': 'uncaught', 'label': 'Uncaught Exceptions', 'default': True}], 'supportsSetExpression': True, 'supportsModulesRequest': True, 'supportsHitConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsConditionalBreakpoints': True, 'supportsValueFormattingOptions': True, 'supportsExceptionOptions': True}),
   Event(seq=2, event='initialized', body={}),
   Response(seq=3, request_seq=1, command='attach', success=True, message='', body={}),
   Response(seq=4, request_seq=2, command='setBreakpoints', success=True, message='', body={'breakpoints': [{'id': 1, 'verified': True, 'line': '4'}]}),
   Response(seq=5, request_seq=3, command='configurationDone', success=True, message='', body={}),
-  Event(seq=6, event='process', body={'startMethod': 'attach', 'systemProcessId': 67, 'name': '/tmp/workspace-uem1gno3/spam.py', 'isLocalProcess': True}),
?                                      -------------------------

+  Event(seq=6, event='process', body={'systemProcessId': 67, 'startMethod': 'attach', 'name': '/tmp/workspace-uem1gno3/spam.py', 'isLocalProcess': True}),
?                                                            +++++++++++++++++++++++++

   Event(seq=7, event='exited', body={'exitCode': 0}),
   Event(seq=8, event='terminated', body={}),
-  Event(seq=9, event='output', body={'output': '1+2=3\n', 'category': 'stdout'}),
?                                                                                ^

+  Event(seq=9, event='output', body={'output': '1+2=3\n', 'category': 'stdout'})]
?                                                                                ^

-  Event(seq=10, event='output', body={'output': "/mnt/c/GIT/ptvsd/ptvsd/wrapper.py:808: UserWarning: timed out waiting for disconnect request\n  warnings.warn('timed out waiting for disconnect request')\n", 'category': 'stderr'})]

```

**Comment by DonJayamanne** [comment]
I'm confused by the issue, is this an issue with Windows or Wsl or both. It would be better to create septate issues if we have two issues here.

**Comment by karthiknadig** [comment]
The test fails to succeed on both. The reason for failure may be different. Since we don't support WSL yet (given we don't have WSL in our CI) we can ignore the WSL part of the issue. Consider this a windows only issue.

I will create a separate issue to handle WSL support.
