### ISSUE TITLE
ConnectionResetError when running Django app

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#395]
I Often see this while running Django web app:
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49277)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\pyenv\py3664\lib\site-packages\django\core\servers\basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
```

**Comment by karthiknadig** [comment]
Not able to repro. Note: Even though i see this in the console, it does not affect application run. Reopen if this is seen again.
