### ISSUE TITLE
Intermittent error triggering a TypeError

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#396]
```python
Traceback (most recent call last):
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 796, in done
    fut.result()
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\futures.py", line 149, in callback
    x = next(it)
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 1044, in on_threads
    _, _, resp_args = yield self.pydevd_request(cmd, '')
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 821, in pydevd_request
    return self._pydevd_request(self.loop, cmd_id, args)
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 392, in pydevd_request
    os.write(self.pipe_w, s.encode('utf8'))
TypeError: an integer is required (got type NoneType)
```

I can't reproduce consistently. Was running the following code:
```python
x = 1
y = 2
x = 3
print("Hello, Douglas Adams!")
```

**Comment by karthiknadig** [comment]
Dupe #385?

**Comment by brettcannon** [comment]
@karthiknadig I will go with "yes" 😉
