### ISSUE TITLE
Error while debugging python code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#397]
Windows 10
Anaconda 5.1.0 (Python 3.6.4 64bit)
PTVSD 4.1.1.a1
* Add break point to the lint `time.sleep`
* Start debugging
* When breakpoint hits, press `Continue`
* Eventually the exception will occur

**Code:**
```
import time
import sys
print("Hello")

for i in range(10):
    time.sleep(0.1)
    print(i)
```

**Error:**
```
Exception ignored in: <generator object using_format at 0x0000023C5A5A6BA0>
Traceback (most recent call last):
  File "C:\Users\donja\.vscode-insiders\extensions\pythonVSCode\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000023C5A5F6308>
Traceback (most recent call last):
  File "C:\Users\donja\.vscode-insiders\extensions\pythonVSCode\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000023C5A5F6678>
Traceback (most recent call last):
  File "C:\Users\donja\.vscode-insiders\extensions\pythonVSCode\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
```

**Comment by DonJayamanne** [comment]
Hmm, happening pretty consistently on my personal PC. Will test on work PC tomorrow.

**Comment by int19h** [comment]
Closing as dupe.
