### ISSUE TITLE
Error while debugging django

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#406]
Instructions can be found here https://github.com/mozillalives/django-vscode-demo

* Python 3.6 on Mac ( not tested on other OS nor other versions of Python)
* Install the requirements in requirements.txt
* Set a breakpoint in exampleproject/views.py on line 5
* Launch the Python: Django debug configuration
* Make a post request to http://localhost:8000
* Continue debugging
* The following error is displayed:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/django-vscode-demo/.venv2/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/django-vscode-demo/.venv2/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/django-vscode-demo/.venv2/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/django-vscode-demo/exampleproject/views.py", line 5, in index
    body = request.body
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/IssueRepos/django-vscode-demo/.venv2/lib/python3.6/site-packages/django/http/request.py", line 264, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
[03/May/2018 18:29:20] "GET / HTTP/1.1" 500 69296
```

**Comment by MikhailArkhipov** [comment]
Looks similar to #395

**Comment by DonJayamanne** [comment]
No it isn't.

**Comment by karthiknadig** [comment]
The issue is in our `safe_repr` code. Specifically in `is_long_iter`. @int19h Any suggestion on how to fix the problem? This is the problem stack:
```
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\pyenv\py3664\lib\site-packages\django\core\servers\basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\pyenv\py3664\lib\site-packages\django\contrib\staticfiles\handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "C:\pyenv\py3664\lib\site-packages\django\core\handlers\wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "C:\pyenv\py3664\lib\site-packages\django\core\handlers\base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "C:\pyenv\py3664\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\pyenv\py3664\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\pyenv\py3664\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kanadig\source\repos\DjangoTest\DjangoTest\app\views.py", line 14, in home
    body = req1.body
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 621, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 785, in do_wait_suspend
    self.process_internal_commands()
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 540, in process_internal_commands
    int_cmd.do_it(self)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 1102, in do_it
    xml += pydevd_xml.frame_vars_to_xml(frame.f_locals, hidden_ns)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_xml.py", line 260, in frame_vars_to_xml
    xml += var_to_xml(v, str(k))
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_xml.py", line 286, in var_to_xml
    str_from_provider = _str_from_providers(v, _type, typeName)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_xml.py", line 205, in str_from_providers
    return provider.get_str(o)
  File "C:\GIT\ptvsd\ptvsd\wrapper.py", line 99, in get_str
    return self._repr(val)
  File "C:\GIT\ptvsd\ptvsd\safe_repr.py", line 74, in __call__
    return ''.join(self._repr(obj, 0))
  File "C:\GIT\ptvsd\ptvsd\safe_repr.py", line 109, in _repr
    if self._is_long_iter(obj):
  File "C:\GIT\ptvsd\ptvsd\safe_repr.py", line 162, in _is_long_iter
    return any(i > self.maxcollection[level] or self._is_long_iter(item, level + 1) for i, item in enumerate(obj))  # noqa
  File "C:\GIT\ptvsd\ptvsd\safe_repr.py", line 162, in <genexpr>
    return any(i > self.maxcollection[level] or self._is_long_iter(item, level + 1) for i, item in enumerate(obj))  # noqa
  File "C:\pyenv\py3664\lib\site-packages\django\http\request.py", line 347, in xreadlines
    buf = self.readline()
```
