### ISSUE TITLE
Errors in debugger when debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#411]
**Note:** This is an error reported by a user of the VS Code experimental debugger.

Original error reported here https://github.com/Microsoft/vscode-python/issues/177#issuecomment-386674497

`
Traceback (most recent call last): File "/home/thiago/.vscode/extensions/ms-python.python-2018.4.0/pythonFiles/experimental/ptvsd/ptvsd/wrapper.py", line 796, in done fut.result() File "/home/thiago/.vscode/extensions/ms-python.python-2018.4.0/pythonFiles/experimental/ptvsd/ptvsd/futures.py", line 40, inresult reraise(self._exc_info) File "/home/thiago/.vscode/extensions/ms-python.python-2018.4.0/pythonFiles/experimental/ptvsd/ptvsd/reraise3.py", line 8, inreraise raise exc_info[1].with_traceback(exc_info[2]) File "/home/thiago/.vscode/extensions/ms-python.python-2018.4.0/pythonFiles/experimental/ptvsd/ptvsd/futures.py", line 149, in callback x = next(it) File "/home/thiago/.vscode/extensions/ms-python.python-2018.4.0/pythonFiles/experimental/ptvsd/ptvsd/wrapper.py", line 1229, in on_variables pyd_var = self.var_map.to_pydevd(vsc_var) File "/home/thiago/.vscode/extensions/ms-python.python-2018.4.0/pythonFiles/experimental/ptvsd/ptvsd/wrapper.py", line 215, in to_pydevd return self._vscode_to_pydevd[vscode_id] KeyError: 125
`

**Comment by karthiknadig** [comment]
This could happen because Scopes request failed for some reason and the following variables request failed because of that. Or Variables request occurred before Scopes request. Another possibility is that it was a collection object that did not get added to the variables map.

Either way I think we should fail the request with `send_error_response` if we cannot find it in the `var_map`.
