### ISSUE TITLE
Error debugging

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#417]
From https://developercommunity.visualstudio.com/content/problem/248606/you-guys-have-ruined-visual-studio-1571.html

See the internal bug 612876, in the diagnostics tab, for the project sources and screenshot.

Now I cannot debug my program.
```
pydev debugger: starting

pydev debugger: warning: trying to add breakpoint to file that does not exist: h:\ml\capsule network\capsnet-keras-br2\capsulenet.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: h:\ml\capsule network\capsnet-keras-br2\capsulenet.py (will have no effect)
Using TensorFlow backend.
Namespace(batch_size=100, debug=False, digit=1, epochs=5, lam_recon=0.392, lr=0.001, lr_decay=0.9, routings=3, save_dir='./result', shift_fraction=0.1, testing=False, weights='result/trained_model.h5')

model:
    BoxRatio  Thrust  Velocity  OnBalRun  vwapGain  Altitude
0     1.443   0.020     0.393     1.069     0.492         0
1     1.252   0.224     0.343     1.062     0.479         0
2     0.491  -0.136     1.035     2.136     0.421         0
3     0.413  -0.017     1.181     2.883     0.412         0
4     0.148  -0.205     0.967     1.512     0.508         0

test:
        BoxRatio  Thrust  Velocity  OnBalRun  vwapGain  Altitude
12860     0.517   0.181     1.065     2.814     0.795         0
8393      0.401  -0.192     1.122     1.458     0.605         0
7540      0.622  -0.338     0.435     1.624     0.546         0
6823      0.283  -0.355     0.458     1.192     0.492         0
2309      0.232  -0.298     0.946     1.456     0.433         0
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Exception ignored in: <generator object using_format at 0x0000027170553F10>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000027170553EB8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000027170553D58>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000027170553BF8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000027170553678>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271705536D0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000027170312D58>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x0000027170312D00>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271779D3360>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271779D3308>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271779D31A8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271779D33B8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271779D36D0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x00000271779D39E8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
```

**Comment by karthiknadig** [comment]
Looks like the same as https://github.com/Microsoft/ptvsd/issues/397. @int19h
