### ISSUE TITLE
IronPython: 'module' object has no attribute 'SIGHUP'

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#436]
ptvsd fails to start on IronPython with this error:
```
Traceback (most recent call last):
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\ptvsd_launcher.py", line 111, in <module>
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\Packages\ptvsd\debugger.py", line 36, in debug
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\Packages\ptvsd\_main.py", line 47, in run_file
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\Packages\ptvsd\daemon.py", line 53, in __init__
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\Packages\ptvsd\daemon.py", line 95, in install_exit_handlers
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\Packages\ptvsd\_main.py", line 95, in _run
  File "c:\users\kanadig\appdata\local\microsoft\visualstudio\15.0_8875dd93exp\extensions\microsoft corporation\python\15.8.0\Packages\ptvsd\pydevd_hooks.py", line 52, in install
AttributeError: 'module' object has no attribute 'SIGHUP'
```

**Comment by karthiknadig** [comment]
Another location with `SIGHUP` issue:
![image](https://user-images.githubusercontent.com/3840081/40509470-7875c546-5f4e-11e8-9d8e-db02985f3d27.png)

**Comment by karthiknadig** [comment]
We no longer register this signal in `ptvsd`, fixed in branch `dbg_adapter_refactor`.
