### ISSUE TITLE
Start without debugging crashes in VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#464]
* Create a file with a print statement
* Run the file without debugging `Debug->Start without debugging`

**Error in terminal window:**
```
$ cd /Users/don/Desktop/Development/pythonStuff/issueRepos/issue202WrongVarDbg ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" "PYTHONPATH=/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd" python -m ptvsd --nodebug --host localhost --port 56669 /Users/don/Desktop/Development/pythonStuff/issueRepos/issue202WrongVarDbg/one.py
Traceback (most recent call last):
  File "/Users/don/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/don/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 202, in <module>
    main(args.address, args.name, args.kind, extra, nodebug=args.nodebug)
  File "/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 195, in main
    run_main(addr, name, kind, *extra)
  File "/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd/ptvsd/_main.py", line 24, in run_main
    no_debug_runner(address, name, kind == 'module', *extra, **kwargs)
  File "/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd/ptvsd/runner.py", line 31, in run
    if not start_message_processor(*address):
  File "/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd/ptvsd/runner.py", line 54, in start_message_processor
    start_client(daemon, host, port_num)
  File "/Users/don/.vscode-insiders/extensions/pythonVSCode/pythonFiles/experimental/ptvsd/ptvsd/pydevd_hooks.py", line 68, in start_client
    pydevd, start_session = daemon.start_client((host, port))
AttributeError: 'Daemon' object has no attribute 'start_client'
```

**This used to work.**

**Comment by ericsnowcurrently** [comment]
The problem is that in ptvsd/runner.py we copied code instead of subclassing.  I'll work on a fix.
