### ISSUE TITLE
Tests fail on windows due to change in sequence

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#478]
```
======================================================================
FAIL: test_locals (tests.highlevel.test_messages.VariablesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\GIT\ptvsd\tests\highlevel\test_messages.py", line 453, in test_locals
    self.expected_pydevd_request('{}\t2\tFRAME'.format(thread.id)),
  File "C:\GIT\ptvsd\tests\highlevel\__init__.py", line 923, in assert_received
    self.assertEqual(received, expected)
AssertionError: Lists differ: [Message(cmdid=<CMD_GET_FRAME 114>, seq=1000000005, payload='5\t2\tFRAME')] != [Message(cmdid=<CMD_GET_FRAME 114>, seq=1000000004, payload='5\t2\tFRAME')]

First differing element 0:
Message(cmdid=<CMD_GET_FRAME 114>, seq=1000000005, payload='5\t2\tFRAME')
Message(cmdid=<CMD_GET_FRAME 114>, seq=1000000004, payload='5\t2\tFRAME')

- [Message(cmdid=<CMD_GET_FRAME 114>, seq=1000000005, payload='5\t2\tFRAME')]
?                                                  ^

+ [Message(cmdid=<CMD_GET_FRAME 114>, seq=1000000004, payload='5\t2\tFRAME')]
?                                                  ^


----------------------------------------------------------------------
Ran 100 tests in 17.598s

FAILED (failures=41, skipped=14)
```

All of the 41 failed tests have the same issue.

**Comment by karthiknadig** [comment]
Fixed via https://github.com/Microsoft/ptvsd/pull/467/commits/d78dbd2316113457036a8ca477ee19ac4d476385
