### ISSUE TITLE
Printed traceback has too many newlines

### ISSUE THREAD

**Issue by zooba** [Microsoft/ptvsd#482]
This is exactly as it appeared in the Output window in VS when I started debugging and then hit Ctrl+C in the debuggee.

It's not entirely clear who printed which traceback, but the first one is the correct style.

```
Loaded '__main__'
Traceback (most recent call last):
File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 643, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 825, in do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
Traceback (most recent call last):
File "c:\VS\15.8.0\ptvsd_launcher.py", line 111, in <module>

vspd.debug(filename, port_num, debug_id, debug_options, run_as)

File "C:\MyProject\env\lib\site-packages\ptvsd\debugger.py", line 37, in debug

run(address, filename, *args, **kwargs)

File "C:\MyProject\env\lib\site-packages\ptvsd\_local.py", line 48, in run_file

run(argv, addr, **kwargs)

File "C:\MyProject\env\lib\site-packages\ptvsd\_local.py", line 99, in _run

_pydevd.main()

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 1719, in main

globals = debugger.run(setup['file'], None, None, is_module)

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 1073, in run

return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 1080, in _exec

pydev_imports.execfile(file, globals, locals)  # execute the script

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile

exec(compile(contents+"\n", file, 'exec'), glob, loc)

File "C:\MyProject\module1.py", line 20, in <module>

sys.exit(int(main() or 0))

File "C:\MyProject\module1.py", line 14, in main

do_my_sleep(10)

File "C:\MyProject\module1.py", line 14, in main

do_my_sleep(10)

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 643, in trace_dispatch

self.do_wait_suspend(thread, frame, event, arg)

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 134, in do_wait_suspend

self._args[0].do_wait_suspend(*args, **kwargs)

File "C:\MyProject\env\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 825, in do_wait_suspend

time.sleep(0.01)

KeyboardInterrupt

The program 'python.exe' has exited with code 0 (0x0).
```

**Comment by karthiknadig** [comment]
This is the `Tee` output in VS right?

**Comment by zooba** [comment]
I guess? Pretty sure I saw the same in the console before it disappeared though.

**Comment by zooba** [comment]
Looks like tee is doubling spaces in some messages but not others. Just saw it for some `print` output as well.

**Comment by DonJayamanne** [comment]
@zooba @karthiknadig Please could you re-test in VS with `PTVSD==4.1.1a1`
I believe this is a regression and related to https://github.com/Microsoft/ptvsd/issues/489.

**Comment by karthiknadig** [comment]
It is a regression, I had commented that they are related.

**Comment by DonJayamanne** [comment]
> this is the same as #489

Yes, but are they the same?
If they are, then we should close one of them.

**Comment by karthiknadig** [comment]
The behavior seems opposite. In one case they are missing newlines and in another it is add extra. If this does not repro in VSC the same way, then they are two different issues. I have not seen this VSC so far, so I am suspecting they are related but not same.
