### ISSUE TITLE
ptvsd clients can't detect if enable_attach successfully binds to a port

### ISSUE THREAD

**Issue by jamding** [microsoft/ptvsd#572]
## Environment data

- PTVSD version: 4.1.1a9
- OS and version: RHEL7
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.6
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Attempting to try a range of ports to bind to:
```
    for attempt in range(attempts):
        target_port = starting_port + attempt
        try:
            ptvsd.enable_attach(address=('127.0.0.1', target_port), redirect_output=False)
        except socket.error as e:
            if e.errno == 48 or e.errno == 98:
                print("Port {} is already in use", target_port)
                continue
        return target_port
```
but never enters the except block because a daemon thread constructs the server. 
https://github.com/Microsoft/ptvsd/blob/v4.1.1a9/ptvsd/_remote.py#L29

## Expected  behavior

Should be able to catch address in use errors and retry on a different address

Actually, it looks like this is already fixed on `master`: https://github.com/Microsoft/ptvsd/blob/master/ptvsd/_remote.py#L18, feel free to close out if this is the case.

**Comment by karthiknadig** [comment]
This was fixed a while ago. We will continue to support this going forward with the Out-of-proc debug adapter.
```
Traceback (most recent call last):
  File "test_jump.py", line 5, in <module>
    ptvsd.enable_attach(address=('localhost', 5678))
  File "C:\Python37\lib\site-packages\ptvsd\attach_server.py", line 101, in enable_attach
    ptvsd_enable_attach(address)
  File "C:\Python37\lib\site-packages\ptvsd\_remote.py", line 79, in enable_attach
    patch_multiprocessing=ptvsd.options.multiprocess)
  File "C:\Python37\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "C:\Python37\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "C:\Python37\lib\site-packages\ptvsd\_vendored\pydevd\pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "C:\Python37\lib\site-packages\ptvsd\pydevd_hooks.py", line 136, in _start_client
    return start_client(daemon, h, p)
  File "C:\Python37\lib\site-packages\ptvsd\_remote.py", line 62, in <lambda>
    start_client=(lambda daemon, h, port: start_daemon()),
  File "C:\Python37\lib\site-packages\ptvsd\_remote.py", line 50, in start_daemon
    _, next_session = daemon.start_server(addr=(host, port))
  File "C:\Python37\lib\site-packages\ptvsd\daemon.py", line 161, in start_server
    self._server = create_server(addr.host, addr.port)
  File "C:\Python37\lib\site-packages\ptvsd\socket.py", line 79, in create_server
    server.bind((host, port))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by karthiknadig** [comment]
Additionally you can also do this:
```py
print(ptvsd.enable_attach(address=('localhost', 0)))
```
That will print the output of `getsockname`:
```
('localhost', 56448)
```
