### ISSUE TITLE
Running a python 2.7 program to completion ends with an error

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#59]
When running a python program to completion (without any breakpoints), the program ends with an error output.

* Python program has a simple print statement `print("hello world")`
* Debug the above program without any break points
* It runs to completion with the following printed in the terminal window:
```shell
Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython.pyx", line 1065, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__ (_pydevd_bundle/pydevd_cython.c:20641)
  File "/Users/donjayamanne/anaconda3/envs/py27/lib/python2.7/site-packages/pydevd.py", line 270, in not_in_scope
    return pydevd_utils.not_in_project_roots(filename)
AttributeError: 'NoneType' object has no attribute 'not_in_project_roots'
Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython.pyx", line 1065, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__ (_pydevd_bundle/pydevd_cython.c:20641)
  File "/Users/donjayamanne/anaconda3/envs/py27/lib/python2.7/site-packages/pydevd.py", line 270, in not_in_scope
    return pydevd_utils.not_in_project_roots(filename)
AttributeError: 'NoneType' object has no attribute 'not_in_project_roots'
```

**Note: This works perfectly well in Python 3.6**

**Comment by DonJayamanne** [comment]
No longer reproducible, could have been fixed with https://github.com/Microsoft/ptvsd/pull/140
