### ISSUE TITLE
Launching a Python module using `-m` with `ptvsd.enable_attach` in __init__ fails

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#592]
## Environment data

- PTVSD version: Master
- OS and version: Mac (may not be OS specific)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio:N/A

## Actual behavior

```
Traceback (most recent call last):
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/tests/resources/system_tests/test_exceptions/mymod_attach1/__init__.py", line 4, in <module>
    ptvsd.enable_attach((sys.argv[1], sys.argv[2]))
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/attach_server.py", line 71, in enable_attach
    redirect_output=redirect_output,
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/_remote.py", line 27, in enable_attach
    **kwargs
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/pydevd_hooks.py", line 95, in install
    if __main__ is not pydevd and __main__.__file__ == pydevd.__file__:
AttributeError: module '__main__' has no attribute '__file__'
```

## Expected  behavior

Should not error out

## Steps to reproduce:

* Create a python module
* Add the following code in the `__init__.py`
```python
import sys
import ptvsd
ptvsd.enable_attach(('localhost', 9876))
ptvsd.wait_for_attach()

try:
    raise ArithmeticError('Hello')
except Exception:
    pass
sys.stdout.write('end')
```
* Start the module `python -m xyz`
That's when it goes kaboom

**Comment by karthiknadig** [comment]
This is not OS Specific. Occurs on Windows as well.
