### ISSUE TITLE
VSTS CI Mac Tests hangs 

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#614]
The following test hangs:
test_exception_breakpoints (tests.highlevel.test_live_pydevd.BreakpointTests) ...

For some reason the tests running on Mac hang (randomly) at the same place, even though the test is disabled:

```
2018-07-09T17:07:01.9310680Z   test_attach_exit_during_session (tests.highlevel.test_lifecycle.LifecycleTests) ... SKIP (0.000s)
2018-07-09T17:07:04.0875620Z   test_attach_from_unix_os (tests.highlevel.test_lifecycle.LifecycleTests) ... OK (2.160s)
2018-07-09T17:07:05.9403340Z   test_attach_from_windows_os (tests.highlevel.test_lifecycle.LifecycleTests) ... OK (2.172s)
2018-07-09T17:07:05.9418780Z   test_launch (tests.highlevel.test_lifecycle.LifecycleTests) ... OK (0.024s)
2018-07-09T17:07:06.2616890Z   test_breakpoints_single_file (tests.highlevel.test_live_pydevd.BreakpointTests) ... OK (0.321s)
2018-07-09T17:36:51.8228630Z ##[debug]Re-evaluate condition on job cancellation for step: 'Run Tests'.
2018-07-09T17:36:51.8246340Z ##[debug]Skip Re-evaluate condition on agent shutdown.
2018-07-09T17:36:51.8438370Z   test_exception_breakpoints (tests.highlevel.test_live_pydevd.BreakpointTests) ... 
2018-07-09T17:36:52.0201090Z ##[error]The operation was canceled.
2018-07-09T17:36:52.0271590Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
```

https://ptvsd.visualstudio.com/ptvsd/ptvsd%20Team/_build/results?buildId=337&view=logs

## Notes:
* The test has been disabled, yet it hangs just when attempting to run that test.
* We must add timeouts for these tests, as done in the system tests.

/cc @ericsnowcurrently @karthiknadig @d3r3kk 
Thoughts?

**Comment by DonJayamanne** [comment]
Found the cause, we have a dead lock (guess this was obvious from the fact that the tests were  not running)

**Comment by DonJayamanne** [comment]
**Here's the stack trace**
* I've modified tests to capture exceptions and print stack trace:

```
2018-07-12T16:39:44.0527140Z ERROR [10.178s]: test_no_breakpoints (tests.highlevel.test_live_pydevd.BreakpointTests)
2018-07-12T16:39:44.0543980Z ----------------------------------------------------------------------
2018-07-12T16:39:44.0560370Z Traceback (most recent call last):
2018-07-12T16:39:44.0575590Z   File "/Users/vsts/agent/2.136.1/work/1/s/tests/highlevel/test_live_pydevd.py", line 187, in launched
2018-07-12T16:39:44.0590620Z     self.fix.binder.wait_until_done()
2018-07-12T16:39:44.0606520Z   File "/Users/vsts/agent/2.136.1/work/1/s/tests/helpers/pydevd/_binder.py", line 145, in wait_until_done
2018-07-12T16:39:44.0624230Z     'wait_until_done timed out after {} secs'.format(timeout))
2018-07-12T16:39:44.0640690Z Exception: wait_until_done timed out after 10.0 secs
2018-07-12T16:39:44.0648360Z 
2018-07-12T16:39:44.0663260Z During handling of the above exception, another exception occurred:
2018-07-12T16:39:44.0670990Z 
2018-07-12T16:39:44.0685710Z Traceback (most recent call last):
2018-07-12T16:39:44.0700640Z   File "/Users/vsts/agent/2.136.1/work/1/s/tests/highlevel/test_live_pydevd.py", line 307, in test_no_breakpoints
2018-07-12T16:39:44.0715730Z     received = self.vsc.received
2018-07-12T16:39:44.0731040Z   File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
2018-07-12T16:39:44.0745870Z     next(self.gen)
2018-07-12T16:39:44.0760730Z   File "/Users/vsts/agent/2.136.1/work/1/s/tests/highlevel/test_live_pydevd.py", line 199, in launched
2018-07-12T16:39:44.0775760Z     raise Exception(message)
2018-07-12T16:39:44.0790520Z Exception: 
2018-07-12T16:39:44.0804940Z     Session Messages:
2018-07-12T16:39:44.0821500Z     -----------------
2018-07-12T16:39:44.0837100Z     
2018-07-12T16:39:44.0844700Z 
2018-07-12T16:39:44.0859010Z     Original Error:
2018-07-12T16:39:44.0874890Z     ---------------
2018-07-12T16:39:44.0890600Z     Traceback (most recent call last):
2018-07-12T16:39:44.0906080Z   File "/Users/vsts/agent/2.136.1/work/1/s/tests/highlevel/test_live_pydevd.py", line 187, in launched
2018-07-12T16:39:44.0921220Z     self.fix.binder.wait_until_done()
2018-07-12T16:39:44.0936080Z   File "/Users/vsts/agent/2.136.1/work/1/s/tests/helpers/pydevd/_binder.py", line 145, in wait_until_done
2018-07-12T16:39:44.0952930Z     'wait_until_done timed out after {} secs'.format(timeout))
2018-07-12T16:39:44.0968980Z Exception: wait_until_done timed out after 10.0 secs
```
