### ISSUE TITLE
Error seen while running as module in python 2.7

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#656]
## Environment data

- PTVSD version: master
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

```
Traceback (most recent call last):
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command.py", line 758, in process_net_command
    pydevd_utils.set_project_roots(text.split(u'\t'))
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_utils.py", line 225, in set_project_roots
    project_roots = _set_roots(project_roots, _PROJECT_ROOTS_CACHE)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_utils.py", line 172, in _set_roots
    new_roots.append(_normpath(root))
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_utils.py", line 19, in _normpath
    return pydevd_file_utils.get_abs_path_real_path_and_base_from_file(filename)[0]
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 451, in get_abs_path_real_path_and_base_from_file
    abs_path, real_path = _NormPaths(f)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 204, in _NormPaths
    abs_path = _NormPath(filename, os.path.abspath)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 220, in _NormPath
    if r[ind] == "!":
IndexError: string index out of range
```

## Expected  behavior

Error should not be seen.

## Steps to reproduce:

Use the following launch configuration:

1. Create a dir `pyscratch`
2. Create a file in the above dir `mymod` with following contents:
```pyhton
print('done')
```
3. Open the directory in VSC
4. Add the following launch configuration to `launch.json` in VSC.
```json
        {
            "name": "Python Experimental: Module",
            "type": "pythonExperimental",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "env": {"PYTHONPATH":"${workspaceFolder}"},
            "envFile": "${workspaceFolder}/.env",
            "debugStdLib": false,
            "module": "mymod",
            "args": [
                "--arg1", "--arg2", "arg3"
            ]
        },
```
5. Start debugging using the `Python Experimental: Module` config.

## Logs:
These are the args to pass to ptvsd.main()
```
['C:\\GIT\\ptvsd\\ptvsd\\__main__.py', '--port', '49268', '--client', 'localhost', '--qt-support=auto', '--module', '--file', 'mymod:', '--arg1', '--arg2', 'arg3']
```

/cc @fabioz

**Comment by karthiknadig** [comment]
Closing this one since the other one has priority and details assigned to it.
