### ISSUE TITLE
Debug/non-debug runs sometimes fail when the port is in use

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#677]
## Environment data

- PTVSD version: master
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): any
- Using VS Code or Visual Studio: VSC

## Actual behavior
```
Could not connect to localhost: 53789
Traceback (most recent call last):
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1699, in main
    debugger.connect(host, port)
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 322, in connect
    s = start_client(host, port)
  File "C:\GIT\ptvsd\ptvsd\pydevd_hooks.py", line 81, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "C:\GIT\ptvsd\ptvsd\pydevd_hooks.py", line 61, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "C:\GIT\ptvsd\ptvsd\daemon.py", line 199, in start_client
    connect(client, addr)
  File "C:\GIT\ptvsd\ptvsd\socket.py", line 174, in connect
    sock.connect(addr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

## Expected behavior

Should not fail with error

**Comment by karthiknadig** [comment]
Note:  you can use `netstat -a -b -o` to find the ports in use and the corresponding process owning the port.

**Comment by karthiknadig** [comment]
I have not seen this in a while.
