### ISSUE TITLE
Attach to pid fails on Linux

### ISSUE THREAD

**Issue by andyneff** [microsoft/ptvsd#863]
## Environment data

- PTVSD version: 4.1.3
- OS and version: Fedora 28 and Debian 9
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.15, 3.6.6, 3.7.0
- Using VS Code or Visual Studio: VS Code, but not even connected at this point

## Actual behavior

1. `pipenv run python -m ptvsd --port 5678 --host localhost --pid 25226`

### Python 2.7 Fedora 28 host and Fedora 28 docker

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python2.7/site-packages/ptvsd/__main__.py", line 227, in <module>
    main()
  File "/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python2.7/site-packages/ptvsd/__main__.py", line 223, in main
    wait=args.wait)
  File "/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python2.7/site-packages/ptvsd/__main__.py", line 212, in handle_args
    attach_main(addr, name, *extra, **kwargs)
  File "/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python2.7/site-packages/ptvsd/_attach.py", line 42, in attach_main
    run_python_code(pid, code, connect_debugger_tracing=True)
  File "/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 400, in run_python_code_linux
    assert '\'' not in python_code, 'Having a single quote messes with our command.'
AssertionError: Having a single quote messes with our command.
```

### Python 3.6 on Fedora 28 host and Fedora 28 docker

```
Attaching with arch: i386:x86-64
Running: gdb --nw --nh --nx --pid 25226 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture i386:x86-64' --eval-command='call dlopen("/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='call (int)DoAttach(0, "
ptvsd_path = bytearray([47, 104, 111, 109, 101, 47, 97, 110, 100, 121, 47, 46, 108, 111, 99, 97, 108, 47, 115, 104, 97, 114, 101, 47, 118, 105, 114, 116, 117, 97, 108, 101, 110, 118, 115, 47, 115, 104, 109, 45, 68, 45, 74, 103, 98, 105, 71, 85, 47, 108, 105, 98, 47, 112, 121, 116, 104, 111, 110, 51, 46, 54, 47, 115, 105, 116, 101, 45, 112, 97, 99, 107, 97, 103, 101, 115, 47, 112, 116, 118, 115, 100, 47, 95, 95, 105, 110, 105, 116, 95, 95, 46, 112, 121, 47, 46, 46, 47, 46, 46]).decode("utf-8")
hostname = bytearray([108, 111, 99, 97, 108, 104, 111, 115, 116]).decode("utf-8")

import sys
sys.path.insert(0, ptvsd_path)
import ptvsd
del sys.path[0]

from ptvsd._remote import attach
attach((hostname, 5678))
", 0)' --command='/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/linux/gdb_threads_settrace.py'
Running gdb in target process.
stdout: b'[Thread debugging using libthread_db enabled]\nUsing host libthread_db library "/lib64/libthread_db.so.1".\n0x00007fa038ecc787 in select () from /lib64/libc.so.6\nThe target architecture is assumed to be i386:x86-64\n'
stderr: b'Missing separate debuginfo for /home/andy/.local/share/virtualenvs/shm-D-JgbiGU/bin/python3\nTry: dnf --enablerepo=\'*debug*\' install /usr/lib/debug/.build-id/d0/2c81c699b2af6fc112a219a6f80d58f2ddedce.debug\n\'dlopen@@GLIBC_2.2.5\' has unknown return type; cast the call to its declared return type\nNo symbol table is loaded.  Use the "file" command.\nTraceback (most recent call last):\n  File "/home/andy/.local/share/virtualenvs/shm-D-JgbiGU/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/linux/gdb_threads_settrace.py", line 14, in <module>\n    show_debug_info, is_debug))\ngdb.error: No symbol table is loaded.  Use the "file" command.\n'
```

### In python 3.7.0 docker (debian 9) and python 3.6.6 docker (debian 9)

```
Attaching with arch: i386:x86-64
Running: gdb --nw --nh --nx --pid 423 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture i386:x86-64' --eval-command='call dlopen("/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='call (int)DoAttach(0, "
ptvsd_path = bytearray([47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 108, 105, 98, 47, 112, 121, 116, 104, 111, 110, 51, 46, 55, 47, 115, 105, 116, 101, 45, 112, 97, 99, 107, 97, 103, 101, 115, 47, 112, 116, 118, 115, 100, 47, 95, 95, 105, 110, 105, 116, 95, 95, 46, 112, 121, 47, 46, 46, 47, 46, 46]).decode("utf-8")
hostname = bytearray([108, 111, 99, 97, 108, 104, 111, 115, 116]).decode("utf-8")

import sys
sys.path.insert(0, ptvsd_path)
import ptvsd
del sys.path[0]

from ptvsd._remote import attach
attach((hostname, 5678))
", 0)' --command='/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/linux/gdb_threads_settrace.py'
Running gdb in target process.
warning: Debugger speedups using cython not found. Run '"/usr/local/bin/python" "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/setup_cython.py" build_ext --inplace' to build.
stdout: b'[Thread debugging using libthread_db enabled]\nUsing host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".\n0x00007f94c9a4b3a3 in __select_nocancel () at ../sysdeps/unix/syscall-template.S:84\nThe target architecture is assumed to be i386:x86-64\n$1 = -1480553904\n$2 = 13\n'
stderr: b'84\t../sysdeps/unix/syscall-template.S: No such file or directory.\nNewline characters may not appear in string constants.\n'
```

## Expected  behavior

Attach to process

### Debian 9 docker python 3.7.0

1. `docker run -it --rm --cap-add SYS_PTRACE -p 5678:5678 python:3.7 bash`
1. `apt-get update; apt-get install -y gdb`
1. `pip install ptvsd`
1. `PYTHONPATH=/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/ python -c $'import time\nwhile 1:\n  time.sleep(1); print(".")' &`
1. `python -m ptvsd --port 5678 --pid 413`

**NOTE**: I don't actually know why the `PYTHONPATH` is needed in the debian dockers, but that's not my current issue

### Fedora 28 docker python 3.6.6

1. `docker run -it --rm --cap-add SYS_PTRACE -p 5678:5678 fedora:28 bash`
1. `dnf install -y gdb python3-pip`
1. `pip3 install ptvsd`
1. `python3 -c $'import time\nwhile 1:\n  time.sleep(1); print(".")' &`
1. `python3 -m ptvsd --port 5678 --pid 90`

### Fedora 28 docker python 2.7.15

1. `docker run -it --rm --cap-add SYS_PTRACE -p 5678:5678 fedora:28 bash`
1. `dnf install -y gdb python2-pip`
1. `pip2 install ptvsd`
1. `python2 -c $'import time\nwhile 1:\n  time.sleep(1); print(".")' &`
1. `python2 -m ptvsd --port 5678 --pid 90`

**Comment by karthiknadig** [comment]
@fabioz now that #1520 is done this should be done right?

**Comment by fabioz** [comment]
Yes, this should be fixed in https://github.com/microsoft/ptvsd/commit/76863a93402926d3e83310a30015cec9a639d1c0
