### ISSUE TITLE
Request: ipv6 address support

### ISSUE THREAD

**Issue by showgood163** [microsoft/ptvsd#918]
## Environment data

- PTVSD version: 4.1.3
- OS and version: arch linux
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.0
- Using VS Code or Visual Studio: VS Code

## Actual behavior

feed the ptvsd.enable_attach with ipv6 address using the code below

```
import ptvsd

# Allow other computers to attach to ptvsd at this IP address and port.
ptvsd.enable_attach(address=('2001:123:345::7666', 3000), redirect_output=True)

# Pause the program until a remote debugger is attached
ptvsd.wait_for_attach()
```

and causes error

```
Traceback (most recent call last):
  File "attempt.py", line 4, in <module>
    ptvsd.enable_attach(address=('2001:123:345::7666', 3000), redirect_output=True)
  File "/usr/lib/python3.7/site-packages/ptvsd/attach_server.py", line 72, in enable_attach
    redirect_output=redirect_output,
  File "/usr/lib/python3.7/site-packages/ptvsd/_remote.py", line 85, in enable_attach
    suspend=False)
  File "/usr/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1313, in settrace
    stop_at_frame,
  File "/usr/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1362, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 355, in connect
    s = start_client(host, port)
  File "/usr/lib/python3.7/site-packages/ptvsd/pydevd_hooks.py", line 85, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "/usr/lib/python3.7/site-packages/ptvsd/_remote.py", line 72, in <lambda>
    start_client=(lambda daemon, h, port: start_daemon()),
  File "/usr/lib/python3.7/site-packages/ptvsd/_remote.py", line 64, in start_daemon
    _, next_session = daemon.start_server(addr=(host, port))
  File "/usr/lib/python3.7/site-packages/ptvsd/daemon.py", line 157, in start_server
    self._server = create_server(addr.host, addr.port)
  File "/usr/lib/python3.7/site-packages/ptvsd/socket.py", line 77, in create_server
    server.bind((host, port))
socket.gaierror: [Errno -9] Address family for hostname not supported
```

## Expected  behavior

everything works fine

## Steps to reproduce:

as said above

**Comment by gramster** [comment]
No upvotes (apart from Don); closing for now.
