### ISSUE TITLE
Exception when typing in the Debug Console

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#920]
## Environment data

- PTVSD version: 4.1.3
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 4.5.11 (py == 3.6.6)
- Using VS Code or Visual Studio: conda

See https://github.com/Microsoft/vscode-python/issues/2860 for more details

**Comment by karthiknadig** [comment]
```
(base) D:\Source\Repos\vscode_bug>cd d:\Source\Repos\vscode_bug && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\ProgramData\Anaconda3\python.exe c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd_launcher.py 54696 d:\Source\Repos\vscode_bug\vscode_debug_test.py "
Traceback (most recent call last):
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevconsole.py", line 449, in get_interpreter
    interpreterInterface = getattr(__builtin__, 'interpreter')
AttributeError: module 'builtins' has no attribute 'interpreter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 1419, in do_it
    msg = _pydev_completer.generate_completions_as_xml(frame, self.act_tok)
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\_pydev_completer.py", line 167, in generate_completions_as_xml
    completions = pydevconsole.get_completions(act_tok, act_tok, updated_globals, frame.f_locals)
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevconsole.py", line 460, in get_completions
    interpreterInterface = get_interpreter()
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevconsole.py", line 451, in get_interpreter
    interpreterInterface = InterpreterInterface(None, None, threading.currentThread())
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\pydev_ipython_console.py", line 25, in __init__
    self.interpreter = get_pydev_frontend(host, client_port)
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\pydev_ipython_console_011.py", line 491, in get_pydev_frontend
    _PyDevFrontEndContainer._instance = _PyDevFrontEnd()
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\pydev_ipython_console_011.py", line 340, in __init__
    self.ipython = PyDevTerminalInteractiveShell.instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 425, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 488, in __init__
    self.init_completer()
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\pydev_ipython_console_011.py", line 262, in init_completer
    self.Completer = self._new_completer_600()
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\pydev_ipython_console_011.py", line 224, in _new_completer_600
    parent=self
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_bundle\pydev_ipython_console_011.py", line 95, in __init__
    IPCompleter.__init__(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\completer.py", line 1110, in __init__
    self.dict_key_matches,
AttributeError: can't set attribute

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 1292, in done
    fut.result()
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\futures.py", line 155, in callback
    x = it.send(fut.result())
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 2272, in on_completions
    xml = self.parse_xml_response(resp_args)
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 1345, in parse_xml_response
    return untangle.parse(io.BytesIO(args.encode('utf8'))).xml
  File "c:\Users\gloch\.vscode\extensions\ms-python.python-2018.9.0\pythonFiles\experimental\ptvsd\ptvsd\untangle.py", line 198, in parse
    parser.parse(filename)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error
```

**Comment by fabioz** [comment]
This can be closed now (see discussion on: https://github.com/Microsoft/vscode-python/issues/2860 -- problem was in a specific version of IPython itself and is fixed by upgrading IPython).

**Comment by foobar8675** [comment]
I'm seeing this error right now and was wondering if others running iPython are?

```
mattc$ conda list | grep python
ipython                   7.11.1           py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
python                    3.7.6                h359304d_2  
python-dateutil           2.8.1                      py_0  
(fastai2) Matt-MacBookPro:Practical-Deep-Learning-for-Coders-2
```
