### ISSUE TITLE
AttributeError: 'thread' has no attribute 'frame'

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#923]
## Environment data

- PTVSD version: 4.1.3, also tested master branch
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7, django 1.11.6
- Using VS Code or Visual Studio: VS

## Actual behavior

Does stop break on template breakpoint
Console output:
```
Traceback (most recent call last):
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 801, in make_thread_stack_str
    abs_path_real_path_and_base = get_abs_path_real_path_and_base_from_frame(curr_frame)
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 546, in get_abs_path_real_path_and_base_from_frame
    ret = get_abs_path_real_path_and_base_from_file(f)
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 524, in get_abs_path_real_path_and_base_from_file
    abs_path, real_path = _NormPaths(f)
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 229, in _NormPaths
    raise AssertionError('Paths passed to _NormPaths must be str. Found: %s (%s)' % (filename, type(filename)))
AssertionError: Paths passed to _NormPaths must be str. Found: c:\users\huvalo\source\repos\djangowebproject10\djangowebproject10\app\templates\app\contact.html (<type 'unicode'>)
Traceback (most recent call last):
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\wrapper.py", line 1327, in done
    fut.result()
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\futures.py", line 149, in callback
    x = next(it)
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\wrapper.py", line 2472, in on_pydevd_thread_suspend
    xframes = list(xml.thread.frame)
  File "C:\Projects\GitHub\microsoft\ptvsd\ptvsd\untangle.py", line 87, in __getattr__
    "'%s' has no attribute '%s'" % (self._name, key)
AttributeError: 'thread' has no attribute 'frame'

```

## Expected  behavior

Stop at breakpoint

## Steps to reproduce:
1. New project, Django Web Project
2. Install django as per requirements.txt: `django >= 1.9, <2`
3. Set breakpoint in contact.html on either or both of these lines:
```
<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>
```
4. Debug and open the contact page

**Comment by karthiknadig** [comment]
Not able to repro this with latest version. Please reopen if it occurs again.
