### ISSUE TITLE
Broken pipe error when debugging Multi-proc app

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#927]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio:VSC

## Actual behavior

Got an error

## Expected  behavior

No errors

## Steps to reproduce:
1. Start python program as follows:
`python -m ptvsd --multiprocess --port 9898 --server-host 0.0.0.0 --wait multiProcDbg.py`

2. Attach to the above program in VSC
3. Hit continue, and kaboom!

```python
import multiprocessing
import platform
import sys
import time

def child_of_child(q):
    print('entering child of child')
    assert q.get() == 2
    q.put(3)
    breakpoint()

    print('leaving child of child')

def child(q):
    print('entering child')
    assert q.get() == 1
    breakpoint()

    for i in range(100):
        breakpoint()
        time.sleep(1)
        print('waiting')

    print('spawning child of child')
    p = multiprocessing.Process(target=child_of_child, args=(q,))
    p.start()
    p.join()

    assert q.get() == 3
    q.put(4)
    print('leaving child')


print('spawning child')
multiprocessing.set_start_method('spawn')
q = multiprocessing.Queue()
p = multiprocessing.Process(target=child, args=(q,))
p.start()
print('child spawned')

for i in range(100):
    breakpoint()
    time.sleep(1)
    print('waiting')

q.put(1)
q.put(2)
p.join()
q.close()
```

```
$ python -m ptvsd --multiprocess --port 9898 --server-host 0.0.0.0 --wait multiProcDbg.py
spawning child
child spawned
Could not connect to None: 0
Traceback (most recent call last):
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1756, in main
    debugger.connect(host, port)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 364, in connect
    s = start_server(port)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/pydevd_hooks.py", line 122, in <lambda>
    _start_server = (lambda p: start_server(daemon, addr.host, p))
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/pydevd_hooks.py", line 27, in start_server
    sock, next_session = daemon.start_server((host, port))
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/daemon.py", line 200, in start_server
    multiproc.notify_root(port)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/multiproc.py", line 144, in notify_root
    'port': port,
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/messaging.py", line 304, in send_request
    self._requests[seq] = request
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/messaging.py", line 295, in _send_message
    self.stream.write_json(message)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/messaging.py", line 124, in write_json
    self._writer.write(header)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 607, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
waiting
```

**Comment by int19h** [comment]
Can you remind me if this error occurred before you added `set_start_method('spawn')`?

**Comment by DonJayamanne** [comment]
No it was after

**Comment by int19h** [comment]
I can't repro the original issue on any OS.

However, the original code is wrong - the part that is outside of the functions *must* be under `if __name__ == '__main__'` for the multiprocessing module to work correctly in spawn mode, as described [in the docs](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods). If you don't do that, you get "RuntimeError: context has already been set", because the line with `set_start_method` ends up getting run twice in the child process.

If code is fixed accordingly, then everything appears to run correctly - child processes get spawned, breakpoints in them are hit etc.

@DonJayamanne, can you check if it still repros for you with the above fix?

**Comment by karthiknadig** [comment]
Closing this as no-repro. Please reopen if seen again.
