### ISSUE TITLE
Exception seen occasionally while running `pytest` tests

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#929]
## Environment data

- PTVSD version: master
- OS and version: linux
- Python version (& distribution if applicable, e.g. Anaconda): 3.5
- Using VS Code or Visual Studio: console

Exception seen while running tests:
```
PASSED@37.993224: Waiting for ptvsd#61236 (pid=495) to terminate
Exception in thread ptvsd.vsc_messaging:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/GIt/ptvsd/ptvsd/messaging.py", line 394, in _process_incoming_messages
    message = self.stream.read_json()
  File "/mnt/c/GIt/ptvsd/pytests/helpers/messaging.py", line 52, in read_json
    value = self.stream.read_json()
  File "/mnt/c/GIt/ptvsd/ptvsd/messaging.py", line 108, in read_json
    return json.loads(body)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by karthiknadig** [comment]
Does not occur anymore. Reopen if seen again
