### ISSUE TITLE
PTSVD outputs errors when debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#938]
## Environment data

- PTVSD version: Master
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.5
- Using VS Code or Visual Studio: VSC

## Actual behavior

Errors displayed in terminal window:
```
Traceback (most recent call last):
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/wrapper.py", line 1327, in done
    fut.result()
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/futures.py", line 40, in result
    reraise(self._exc_info)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/futures.py", line 149, in callback
    x = next(it)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/wrapper.py", line 1939, in on_evaluate
    pyd_tid, pyd_fid = self.frame_map.to_pydevd(vsc_fid)
  File "/Users/donjayamanne/Desktop/Development/vscode/ptvsd/ptvsd/wrapper.py", line 272, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
KeyError: 1
```

## Expected  behavior

XXX

## Steps to reproduce:
1. Use the following code:
```python
#!/usr/bin/python3
import os
import subprocess
import sys

# Executes a command given an optional stdin byte string and returns a return code, stdout and stderr from the application
# Example:
# p4filename = "\"" + os.path.join(Variable.getvarvalue("P4PATH"), Variable.getvarvalue("P4FILE")) + "\""
# (retCode, stdout, stderr) = ExecuteCommand(p4filename + " set", None, mystring.encode('utf-8'))
def ExecuteCommand(cmd, cwd = None, stdin_bytes = None):
    if stdin_bytes != None and type(stdin_bytes) != bytes:
        print("ExecuteCommand stdin_bytes must be of type bytes.\n\tIf you have passed a string use your string.encode('UTF-8') to convert the string to a byte array of UFT-8 characters.")
        print("Type passed - %s" % type(stdin_bytes))
        sys.exit(1)
    stdout = ""
    stderr = ""

    if cwd is not None:
        cwd = os.path.realpath(cwd)
        if not os.path.exists(cwd):
            print( "***ERROR*** - Current working directory [%s] does not exist and therefore cannot execute command [%s]" % (cwd, cmd), {"status": "failed"})
            sys.exit(1)
    try:
        process = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True, cwd=cwd)
        (stdout, stderr) = process.communicate(input=stdin_bytes)
        return (process.returncode, stdout.decode("cp437"), stderr.decode("cp437"))
    except OSError as ex:
        return (ex.errno, "", ex.strerror)

(retcode, stdout, stderr) = ExecuteCommand("echo HelloWorld")
print(retcode)
print(stdout)
print(stderr)

sys.exit(retcode)
```
2. Add a breakpoint to the first line
3. Start debugging.
4. Kaboom

**Comment by int19h** [comment]
Can you share the launch.json snippet for your repro?

**Comment by kerbrose** [comment]
got an error almost the same when remote debugging an app inside a docker image
ptvsd/wrapper.py", line 311, in to_pydevd
    return self._vscode_to_pydevd[vscode_id]
realized the difference between the line numbers of your post and mine. the reason was ptvsd module of the docker was 4.2.2 however the latest was 4.2.7 so I just upgraded the ptvsd module & it works fine now.
thanks to ptvsd team
