### ISSUE TITLE
Requesting completions in debug console raises exception if no completions are available

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#978]
## Environment data

- PTVSD version: 4.1.3
- OS and version: Any
- Python version (& distribution if applicable, e.g. Anaconda): Conda
- Using VS Code or Visual Studio: VS Code

When requesting completions in console and no completions are available the traceback below appears in the terminal:

```
Traceback (most recent call last):
  File "/home/aulty/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd/ptvsd/wrapper.py", line 1292, in done
    fut.result()
  File "/home/aulty/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd/ptvsd/futures.py", line 40, in result
    reraise(self._exc_info)
  File "/home/aulty/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd/ptvsd/reraise3.py", line 8, in reraise
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/aulty/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd/ptvsd/futures.py", line 155, in callback
    x = it.send(fut.result())
  File "/home/aulty/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd/ptvsd/wrapper.py", line 2274, in on_completions
    for item in list(xml.comp):
  File "/home/aulty/.vscode/extensions/ms-python.python-2018.9.0/pythonFiles/experimental/ptvsd/ptvsd/untangle.py", line 87, in __getattr__
    "'%s' has no attribute '%s'" % (self._name, key)
AttributeError: 'xml' has no attribute 'comp'
```

Originally reported as a comment in: https://github.com/Microsoft/vscode-python/issues/2860#issuecomment-430838762

**Comment by fabioz** [comment]
@karthiknadig Sorry hadn't seen that... as there's a pull request referencing this one, maybe #970 should be closed instead.
