### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#987]
## Environment data

- PTVSD version: master
- OS and version: Centos/7
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: VSC

## Actual behavior

Calling `ptvsd.enable_attach()` throws this error.
```
Traceback (most recent call last):
  File "./scratch.py", line 3, in <module>
    ptvsd.enable_attach()
  File "/vagrant/ptvsd/attach_server.py", line 72, in enable_attach
    redirect_output=redirect_output,
  File "/vagrant/ptvsd/_remote.py", line 85, in enable_attach
    suspend=False)
  File "/vagrant/ptvsd/_vendored/pydevd/pydevd.py", line 1488, in settrace
    stop_at_frame,
  File "/vagrant/ptvsd/_vendored/pydevd/pydevd.py", line 1582, in _locked_settrace
    debugger.set_tracing_for_untraced_contexts(ignore_frame=get_frame())
  File "/vagrant/ptvsd/_vendored/pydevd/pydevd.py", line 722, in set_tracing_for_untraced_contexts
    for t in threads:
  File "/vagrant/ptvsd/_vendored/pydevd/pydevd.py", line 722, in set_tracing_for_untraced_contexts
    for t in threads:
TypeError: 'NoneType' object is not callable
```
I suspect that this might not be the right stack for this.

## Expected  behavior

Should not throw error

**Comment by Goom11** [comment]
I am also experiencing this not on Linux, on Mac OS X. I am running Microsoft/vscode-python version 2018.9.1 and Microsoft/ptvsd version 4.2.0.

**Comment by karthiknadig** [comment]
@Goom11 Are you seeing a similar callstack?

**Comment by Goom11** [comment]
Yes, very similar callstack. This is an issue on master but not on version 4.1.4. Simplest repro is _probably_ just a simple python script that does
```
import sys
sys.path.append('path to ptvsd v4.2.0')
import ptvsd
ptvsd.enable_attach()
```
I don't know python well so I'm not capable of debugging this issue.

**Comment by int19h** [comment]
This came up in a test run on Linux (`test_autokill` from https://github.com/Microsoft/ptvsd/pull/994):

```
@00.016028: ptvsd#47017 ERR Exception in thread ptvsd.stopping:
@00.016104: ptvsd#47017 ERR Traceback (most recent call last):
@00.016175: ptvsd#47017 ERR   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
@00.016208: ptvsd#47017 ERR     self.run()
@00.016271: ptvsd#47017 ERR   File "/usr/lib/python2.7/threading.py", line 743, in run
@00.016305: ptvsd#47017 ERR     def run(self):
@00.016434: ptvsd#47017 ERR   File "/home/int19h/src/ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 75, in trace_dispatch
@00.016488: ptvsd#47017 ERR     name = splitext(basename(filename))[0]
@00.016537: ptvsd#47017 ERR TypeError: 'NoneType' object is not callable
```

Happens on both 2.7 and 3.7.

**Comment by karthiknadig** [comment]
@int19h could this be the pipe we use to communicate with pydevd that is broken? I see different stacks each time:
```
2018-11-08T20:58:19.0491030Z @00.047363: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/__main__.py", line 269, in <module>
2018-11-08T20:58:19.0491100Z @00.047441: ptvsd#50247 ERR     main()
2018-11-08T20:58:19.0491160Z @00.047631: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/__main__.py", line 265, in main
2018-11-08T20:58:19.0491230Z @00.047720: ptvsd#50247 ERR     wait=args.wait)
2018-11-08T20:58:19.0491290Z @00.047921: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/__main__.py", line 258, in handle_args
2018-11-08T20:58:19.0491370Z @00.048059: ptvsd#50247 ERR     debug_main(addr, name, kind, *extra, **kwargs)
2018-11-08T20:58:19.0491430Z @00.048300: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_local.py", line 43, in debug_main
2018-11-08T20:58:19.0491510Z @00.048455: ptvsd#50247 ERR     run_module(address, name, *extra, **kwargs)
2018-11-08T20:58:19.0491580Z @00.048664: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_local.py", line 68, in run_module
2018-11-08T20:58:19.0491650Z @00.048774: ptvsd#50247 ERR     run(argv, addr, **kwargs)
2018-11-08T20:58:19.0491710Z @00.048982: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_local.py", line 140, in _run
2018-11-08T20:58:19.0491780Z @00.049074: ptvsd#50247 ERR     _pydevd.main()
2018-11-08T20:58:19.0491850Z @00.049303: ptvsd#50247 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_vendored/pydevd/pydevd.py", line 1925, in main
2018-11-08T20:58:19.0491920Z @00.049419: ptvsd#50247 ERR     debugger.connect(host, port)
2018-11-08T20:58:19.0492420Z @00.049556: ptvsd#50247 ERR TypeError: 'NoneType' object is not callable
```

**Comment by int19h** [comment]
You mean the dummy socket we pass to it? I don't see how that could have anything to do with it not being callable.

**Comment by int19h** [comment]
Another unusual stack from a test run, for future reference.
```
2018-11-17T07:01:23.4596570Z @00.057308: ptvsd#51467 ERR Traceback (most recent call last):
2018-11-17T07:01:23.4596650Z @00.057594: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/__main__.py", line 269, in <module>
2018-11-17T07:01:23.4596770Z @00.057691: ptvsd#51467 ERR     main()
2018-11-17T07:01:23.4596860Z @00.057965: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/__main__.py", line 265, in main
2018-11-17T07:01:23.4596930Z @00.058154: ptvsd#51467 ERR     wait=args.wait)
2018-11-17T07:01:23.4597060Z @00.058399: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/__main__.py", line 258, in handle_args
2018-11-17T07:01:23.4597140Z @00.058581: ptvsd#51467 ERR     debug_main(addr, name, kind, *extra, **kwargs)
2018-11-17T07:01:23.4597280Z @00.058811: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_local.py", line 45, in debug_main
2018-11-17T07:01:23.4597360Z @00.058977: ptvsd#51467 ERR     run_file(address, name, *extra, **kwargs)
2018-11-17T07:01:23.4597500Z @00.059213: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_local.py", line 79, in run_file
2018-11-17T07:01:23.4597580Z @00.059414: ptvsd#51467 ERR     run(argv, addr, **kwargs)
2018-11-17T07:01:23.4597640Z @00.059676: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_local.py", line 140, in _run
2018-11-17T07:01:23.4597790Z @00.059791: ptvsd#51467 ERR     _pydevd.main()
2018-11-17T07:01:23.4597860Z @00.060090: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_vendored/pydevd/pydevd.py", line 1934, in main
2018-11-17T07:01:23.4598480Z @00.060295: ptvsd#51467 ERR     globals = debugger.run(setup['file'], None, None, is_module)
2018-11-17T07:01:23.4598580Z @00.060556: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_vendored/pydevd/pydevd.py", line 1283, in run
2018-11-17T07:01:23.4598790Z @00.060818: ptvsd#51467 ERR     return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
2018-11-17T07:01:23.4598890Z @00.061089: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_vendored/pydevd/pydevd.py", line 1290, in _exec
2018-11-17T07:01:23.4599060Z @00.061304: ptvsd#51467 ERR     pydev_imports.execfile(file, globals, locals)  # execute the script
2018-11-17T07:01:23.4599890Z @00.061702: ptvsd#51467 ERR   File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-vsts/pytest-0/test_set_variable_file_launch_0/code_to_debug.py", line 6, in <module>
2018-11-17T07:01:23.4600080Z @00.061912: ptvsd#51467 ERR     ptvsd.break_into_debugger()
2018-11-17T07:01:23.4600160Z @00.062178: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/attach_server.py", line 121, in break_into_debugger
2018-11-17T07:01:23.4600300Z @00.062345: ptvsd#51467 ERR     stop_at_frame=sys._getframe().f_back,
2018-11-17T07:01:23.4600380Z @00.062589: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_remote.py", line 29, in _pydevd_settrace
2018-11-17T07:01:23.4600520Z @00.062767: ptvsd#51467 ERR     _pydevd.settrace(**kwargs)
2018-11-17T07:01:23.4600600Z @00.063052: ptvsd#51467 ERR   File "/Users/vsts/agent/2.141.2/work/1/s/ptvsd/_vendored/pydevd/pydevd.py", line 1491, in settrace
2018-11-17T07:01:23.4600670Z @00.063194: ptvsd#51467 ERR     _set_trace_lock.release()
2018-11-17T07:01:23.4601260Z @00.063387: ptvsd#51467 ERR TypeError: 'NoneType' object is not callable
```

**Comment by offero** [comment]
Same here. Very similar traceabacks.

 ```
 File "myprogram.py", line 577, in <module>
    ptvsd.enable_attach(address=('0.0.0.0', 3000))
  File "/Users/offero/.virtualenvs/myvenv/lib/python2.7/site-packages/ptvsd/attach_server.py", line 72, in enable_attach
    redirect_output=redirect_output,
  File "/Users/offero/.virtualenvs/myvenv/lib/python2.7/site-packages/ptvsd/_remote.py", line 85, in enable_attach
    suspend=False)
  File "/Users/offero/.virtualenvs/myvenv/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1488, in settrace
    stop_at_frame,
  File "/Users/offero/.virtualenvs/myvenv/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1582, in _locked_settrace
    debugger.set_tracing_for_untraced_contexts(ignore_frame=get_frame())
  File "/Users/offero/.virtualenvs/myvenv/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 722, in set_tracing_for_untraced_contexts
    for t in threads:
  File "/Users/offero/.virtualenvs/myvenv/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 722, in set_tracing_for_untraced_contexts
    for t in threads:
TypeError: 'NoneType' object is not callable

```

**Comment by salvatore-giammanco** [comment]
Same here
```
Traceback (most recent call last):
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 140, in _run
    _pydevd.main()
  File "/Users/salvatoregiammanco/.vscode/extensions/ms-python.python-2018.11.0/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1925, in main
    debugger.connect(host, port)
TypeError: 'NoneType' object is not callable
```

**Comment by mfeblowitz** [comment]
Seems like it might have something to do with a corrupt workspace (or configurations associated with the workspace). I closed the workspace, opened the folder, and was able to run debug without error.

**Comment by DonJayamanne** [comment]
Dup of https://github.com/Microsoft/vscode-python/issues/3520

**Comment by DonJayamanne** [comment]
Sorry, wrong issue.

**Comment by fabioz** [comment]
Taking a look at the messages, it seems there are 2 different reports here...

The one in https://github.com/Microsoft/ptvsd/issues/987#issuecomment-437163663 is actually an issue when daemon threads are alive during the interpreter shutdown (as a part of the shutdown process Python sets module attributes to None) .

-- besides showing a stacktrace those shouldn't be a huge problem... in the latest master I've already included some changes to protect from that i.e.: https://github.com/Microsoft/ptvsd/commit/3c83d6be7e6c0584cd9f1555beef10ed59299ab9#diff-a83460d6996f5357f1ba1c8966fa2c35R178 but as they are something in the interpreter shutdown the breakage is very limited.

The major problem seems to be the other case where `'NoneType' object is not callable` appears out of context... I'm under the impression that the culprit could somehow be something in the cython accelerators (so, if someone that can reliably reproduce the error can rename the related `.pyds` below the `ptvsd` folder in the extension and test, it'd be nice to know).

What I can think of is that the code for the tracing function is becoming None (not really unreasonable under cython) and when Python is about to call the tracing function that exception is raised from spurious places because the tracing has became corrupt. 

-- having said that, in https://github.com/Microsoft/ptvsd/commit/3c83d6be7e6c0584cd9f1555beef10ed59299ab9 I've done some changes which could potentially fix this issue but I'm not 100% sure because I haven't actually been able to reproduce it myself (note that's still unreleased).

**Comment by ftrofin** [comment]
I have the same problem with the latest version: VS Code Mac 1.30.1 on macOS 10.14.1 and Python extension 2018.12.1. This renders debugging Python code basically useless. Please fix!

**Comment by mfeblowitz** [comment]
> I have the same problem with the latest version: VS Code Mac 1.30.1 on macOS 10.14.1 and Python extension 2018.12.1. This renders debugging Python code basically useless. Please fix!

Try a fresh workspace. That helped me.

**Comment by fabioz** [comment]
@ftrofin can you try to set the following environment variables:

```
PYDEVD_USE_CYTHON=NO
PYDEVD_USE_FRAME_EVAL=NO
```

and run again to see if it works? 

-- this will disable the accelerators (where I think the issue lies) and can be used as a workaround until a new release is done.

**Comment by ftrofin** [comment]
I added this in my lauch configuration that I'm debugging:
`           "env": { "PYDEVD_USE_CYTHON": "NO",
                "PYDEVD_USE_FRAME_EVAL": "NO"
            }`
but it didn't make a difference. I am still seeing `'NoneType' object is not callable` randomly

**Comment by fabioz** [comment]
Thanks for reporting back @ftrofin... do you think you can check with the latest master? 

You can create a file with the contents below and run it:

```
import ptvsd
print(ptvsd.__file__)
```

to see where it's installed in your system -- then rename the related folder and put the contents from git on the original folder (the contents from `git/ptvsd/src` should be put at the proper place).

**Comment by ftrofin** [comment]
This is the result of running that file in VSCode:
`/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/__init__.pyc
Traceback (most recent call last):
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/__main__.py", line 265, in main
    wait=args.wait)
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/__main__.py", line 258, in handle_args
    debug_main(addr, name, kind, *extra, **kwargs)
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_local.py", line 45, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_local.py", line 79, in run_file
    run(argv, addr, **kwargs)
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_local.py", line 140, in _run
    _pydevd.main()
  File "/Users/work/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1936, in main
    if setup['cmd-line']:
TypeError: 'NoneType' object is not callable`

**Comment by ftrofin** [comment]
So I did replace that folder with the git master and I still get the dreaded message. The weird thing is that it is random: My script goes through a loop processing some files. Sometimes the error comes up on the first or second file sometimes on the fifth or later. Seems random. The traceback printed also doesn't make sense (because that code has been executed many times already in that run). Very strange.

**Comment by fabioz** [comment]
@ftrofin thanks, that's helpful (I was thinking it was related to cython, so, I was probably chasing a dead in in that route)... I have some hunch about what it could be, so, I'll prepare the code on my side (and if you can run it after I make some changes here, that'd be nice).

Also, just to confirm, you're on Python 2.7 on Linux right? (so far  I think all the reports are for Python 2.7 on Linux or Mac).

**Comment by copperchin** [comment]
I can confirm that this is an issue in a Windows environment as well (Windows 7, Python 2.7), and started cropping up as far back as October 2018.

It's been very difficult to narrow down which conditions this happens under; this has been happening to my coworkers for some time, but only recently have I reproduced the error.  I've even opened the same workspace on the same computer with two different sets of custom environment variables and get one environment that debugs, and one that doesn't, even though the workspace settings and launch config are identical.  It's bewildering.

Hoever, in what seems like all cases, it seems like the debugger works until an exception is hit, at which point we get the `'NoneType' object is not callable` error.  

It's also worth noting that toggling the "Raised Exceptions" or "Uncaught Exceptions" in the Breakpoints view can make-or-break the debugger -- for my coworkers, having "Raised Exceptions" checked may mean that the program never runs (hangs), and having "Uncaught Exceptions" seems to encourage the `'NoneType' object is not callable`, error, even if no exceptions are encountered.

The error message seems related to the way the  SystemExit is handled in pydevd.main() -- in our experience it appears that the program is exiting for a _legitimate_ reason, it's just not giving the actual traceback for the thing that kicked off the exception in the first place.  I did  a little poking around to see what was going on, but got ..discouraged... off when I saw that the code deals with threads ':)  

My naive guess is that the issue lies in the traceback object is spawned in a separate thread and not making it back to the main thread, where it is trying to be printed to the  console?

**Comment by ftrofin** [comment]
@fabioz Yes, Python 2.7 but on Mac, not Linux (See my reported config) https://github.com/Microsoft/ptvsd/issues/987#issuecomment-448428677.
I don't know if you have a different setup but I also get this warning every time I open a python file in VSC (because I'm not using VSC's default interpreter?):
![image](https://user-images.githubusercontent.com/8718388/50360462-f4705c80-0514-11e9-8c9f-0c7d06a8395a.png)

**Comment by karthiknadig** [comment]
@ftrofin That comes from the Python extension, @brettcannon should be able to answer that.

**Comment by fabioz** [comment]
@copperchin thank you very much for the investigation. This issue is my main priority now, so, hopefully this will be solved soon ;)

**Comment by dan-cristian** [comment]
I am getting the same issue on an Ubuntu box with:
- python 2.7
- ptvsd in ./venv/lib/python2.7/site-packages (4.2.0)

I run this
`>>> import ptvsd
>>> ptvsd.enable_attach(address=('0.0.0.0', 5678))`


and get the error:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haiot/PYC/venv/local/lib/python2.7/site-packages/ptvsd/attach_server.py", line 72, in enable_attach
    redirect_output=redirect_output,
  File "/home/haiot/PYC/venv/local/lib/python2.7/site-packages/ptvsd/_remote.py", line 85, in enable_attach
    suspend=False)
  File "/home/haiot/PYC/venv/local/lib/python2.7/site-packages/ptvsd/_vendored/pydevd/pydevd.py", line 1491, in settrace
    _set_trace_lock.release()
TypeError: 'NoneType' object is not callable
`
